import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const detailPanePath = 'src/modules/files/features/detail/FileDetailPane.tsx'
const detailPreviewPath = 'src/modules/files/features/detail/FileDetailPreview.tsx'
const detailPreviewShimPath = 'src/modules/files/components/FileDetailPreview.tsx'
const sourcePreviewPath = 'src/modules/files/features/detail/FileDetailSourceLinkedCardPreview.tsx'
const sourceWorkflowControllerPath = 'src/modules/files/features/detail/useSourceLinkedCardWorkflowController.ts'
const sourceWorkflowModelPath = 'src/modules/files/features/detail/source-linked-card-workflow-model.ts'
const sourcePreviewControllerPath = 'src/modules/files/features/detail/useSourceLinkedCardPreviewController.ts'
const sourcePreviewModelPath = 'src/modules/files/features/detail/source-linked-card-preview-model.ts'
const sourcePreviewShimPath = 'src/modules/files/components/FileDetailSourceLinkedCardPreview.tsx'
const previewPrimitivesPath = 'src/modules/files/ui/FileDetailPreviewPrimitives.tsx'
const previewPrimitivesShimPath = 'src/modules/files/components/FileDetailPreviewPrimitives.tsx'

describe('File detail source-linked card preview architecture boundary', () => {
  it('keeps source-linked card Ingest and approval flow out of the detail-pane container', () => {
    const detailPaneSource = readFileSync(detailPanePath, 'utf8')

    expect(existsSync(detailPreviewPath)).toBe(true)
    expect(existsSync(sourcePreviewPath)).toBe(true)
    expect(existsSync(sourceWorkflowControllerPath)).toBe(true)
    expect(existsSync(sourceWorkflowModelPath)).toBe(true)
    expect(existsSync(sourcePreviewControllerPath)).toBe(true)
    expect(existsSync(sourcePreviewModelPath)).toBe(true)
    expect(existsSync(detailPreviewShimPath)).toBe(true)
    expect(existsSync(sourcePreviewShimPath)).toBe(true)
    if (!existsSync(detailPreviewPath) || !existsSync(sourcePreviewPath) || !existsSync(sourceWorkflowControllerPath) || !existsSync(sourceWorkflowModelPath) || !existsSync(sourcePreviewControllerPath) || !existsSync(sourcePreviewModelPath) || !existsSync(detailPreviewShimPath) || !existsSync(sourcePreviewShimPath)) return

    const detailPreviewSource = readFileSync(detailPreviewPath, 'utf8')
    const sourcePreviewSource = readFileSync(sourcePreviewPath, 'utf8')
    const sourceWorkflowControllerSource = readFileSync(sourceWorkflowControllerPath, 'utf8')
    const sourceWorkflowModelSource = readFileSync(sourceWorkflowModelPath, 'utf8')
    const sourcePreviewControllerSource = readFileSync(sourcePreviewControllerPath, 'utf8')
    const sourcePreviewModelSource = readFileSync(sourcePreviewModelPath, 'utf8')
    const detailPreviewShimSource = readFileSync(detailPreviewShimPath, 'utf8')
    const sourcePreviewShimSource = readFileSync(sourcePreviewShimPath, 'utf8')

    expect(detailPaneSource).toContain("from './FileDetailPreview'")
    expect(detailPaneSource).not.toContain("from '../../components/FileDetailPreview'")
    expect(detailPaneSource).not.toContain("from './FileDetailSourceLinkedCardPreview'")
    expect(detailPaneSource).not.toMatch(/\nfunction SourceLinkedCardPreview\(/)
    expect(detailPaneSource).not.toContain('useCreateSourceUpdateProposal')
    expect(detailPaneSource).not.toContain('useRefreshSourceLinkedCard')
    expect(detailPaneSource).not.toContain('useRequestSourceIngestRange')
    expect(detailPaneSource).not.toContain('usePendingSourceUpdateProposals')
    expect(detailPaneSource).not.toContain('useApprovalByTarget')
    expect(detailPaneSource).not.toContain('useResolveInboxApproval')
    expect(detailPaneSource).not.toContain('parseSourceIngestManifestTurtle')
    expect(detailPaneSource).not.toContain('createSourceUpdateProposal')

    expect(detailPreviewSource).toContain("from './FileDetailSourceLinkedCardPreview'")
    expect(sourcePreviewSource).toMatch(/\nexport function SourceLinkedCardPreview\(/)
    expect(sourcePreviewSource).toContain("from './useSourceLinkedCardPreviewController'")
    expect(sourcePreviewSource).toContain('useSourceLinkedCardPreviewController')
    expect(sourcePreviewSource).not.toContain('useState')
    expect(sourcePreviewSource).not.toContain('formatDateTime')
    expect(sourcePreviewSource).not.toContain('resourceMetaTailId')
    expect(sourcePreviewSource).not.toContain('const rows')
    expect(sourcePreviewSource).not.toContain('useToast')
    expect(sourcePreviewSource).not.toContain('useCreateSourceUpdateProposal')
    expect(sourcePreviewSource).not.toContain('useRefreshSourceLinkedCard')
    expect(sourcePreviewSource).not.toContain('useRequestSourceIngestRange')
    expect(sourcePreviewSource).not.toContain('usePendingSourceUpdateProposals')
    expect(sourcePreviewSource).not.toContain('useFilesApprovalByTarget')
    expect(sourcePreviewSource).not.toContain('useResolveFilesInboxApproval')
    expect(sourcePreviewSource).not.toContain('useFilesStore')
    expect(sourcePreviewSource).not.toContain('@/modules/inbox/collections')
    expect(sourcePreviewSource).not.toMatch(/\buseApprovalByTarget\b/)
    expect(sourcePreviewSource).not.toMatch(/\buseResolveInboxApproval\b/)
    expect(sourcePreviewSource).not.toContain('parseSourceIngestManifestTurtle')
    expect(sourcePreviewSource).not.toContain('createSourceUpdateProposal')
    expect(sourcePreviewSource).not.toContain('pendingRanges.length')
    expect(sourcePreviewSource).not.toContain('expectedSourceProposal')
    expect(sourcePreviewSource).not.toContain('sourceCreatePending')
    expect(sourcePreviewSource).not.toContain('pendingSourceProposalsLoading')
    expect(sourcePreviewSource).not.toContain('resolveSourceApprovalPending')
    expect(sourcePreviewSource).not.toContain('requestSourceIngestRangePending')
    expect(sourcePreviewSource).not.toContain('sourceProposal?.proposedContent')
    expect(sourcePreviewSource).not.toContain('source.sourceActionError')
    expect(sourcePreviewSource).not.toContain('source.sourceActionError ?')
    expect(sourcePreviewSource).not.toContain('preview.sourceDetailsOpen ?')
    expect(sourcePreviewSource).not.toContain('preview.hasPendingIngestRanges ?')
    expect(sourcePreviewSource).not.toContain('preview.stagedIngestContent ?')
    expect(sourcePreviewSource).not.toContain('file.previewText')
    expect(sourcePreviewSource).not.toContain('!source.descriptor')
    expect(sourcePreviewSource).not.toContain('!source.bodyUri')
    expect(sourcePreviewSource).toContain('const content = preview.content')
    expect(sourcePreviewSource).toContain('content.kind')
    expect(sourcePreviewSource).toContain('preview.actionError')
    expect(sourcePreviewSource).toContain('preview.detailsPanel')
    expect(sourceWorkflowControllerSource).toContain('export function useSourceLinkedCardWorkflowController')
    expect(sourceWorkflowControllerSource).toContain('useCreateSourceUpdateProposal')
    expect(sourceWorkflowControllerSource).toContain('useRefreshSourceLinkedCard')
    expect(sourceWorkflowControllerSource).toContain('useRequestSourceIngestRange')
    expect(sourceWorkflowControllerSource).toContain('usePendingSourceUpdateProposals')
    expect(sourceWorkflowControllerSource).toContain('useFilesApprovalByTarget')
    expect(sourceWorkflowControllerSource).toContain('useResolveFilesInboxApproval')
    expect(sourceWorkflowControllerSource).toContain('parseSourceIngestManifestTurtle')
    expect(sourceWorkflowControllerSource).not.toContain("from '../../domain/source/source-approval-model'")
    expect(sourceWorkflowControllerSource).not.toContain('createSourceUpdateProposal({')
    expect(sourceWorkflowControllerSource).toContain("from './source-linked-card-workflow-model'")
    expect(sourceWorkflowControllerSource).not.toMatch(/\nfunction sourceLinkedCardBodyName\(/)
    expect(sourceWorkflowControllerSource).not.toMatch(/\nfunction sourceLinkedCardSubject\(/)
    expect(sourceWorkflowControllerSource).not.toContain('.filter((proposal)')
    expect(sourceWorkflowControllerSource).not.toContain('sort((left, right)')
    expect(sourceWorkflowControllerSource).not.toContain('FileEditorSheet')
    expect(sourceWorkflowControllerSource).not.toContain('RichTextFileEditor')
    expect(sourceWorkflowModelSource).toContain('export function getSourceLinkedCardSubject')
    expect(sourceWorkflowModelSource).toContain('export function projectExpectedSourceUpdateProposal')
    expect(sourceWorkflowModelSource).toContain('createSourceUpdateProposal')
    expect(sourceWorkflowModelSource).toContain('export function selectCurrentSourceUpdateProposal')
    expect(sourceWorkflowModelSource).toContain('export function projectSourceLinkedCardBodyFile')
    expect(sourceWorkflowModelSource).toContain('export function projectSourceLinkedCardBodyPreviewText')
    expect(sourceWorkflowModelSource).not.toContain('useToast')
    expect(sourceWorkflowModelSource).not.toContain('useState')
    expect(sourceWorkflowModelSource).not.toContain('useMemo')
    expect(sourcePreviewControllerSource).toContain('export function useSourceLinkedCardPreviewController')
    expect(sourcePreviewControllerSource).toContain('useSourceLinkedCardWorkflowController')
    expect(sourcePreviewControllerSource).toContain("from './source-linked-card-preview-model'")
    expect(sourcePreviewControllerSource).toContain('createSourceLinkedCardPreviewState')
    expect(sourcePreviewControllerSource).toContain('projectSourceLinkedCardPreviewSheetOpen')
    expect(sourcePreviewControllerSource).toContain('projectSourceLinkedCardPreviewSourceDetailsToggled')
    expect(sourcePreviewControllerSource).toContain('projectSourceLinkedCardPrimaryActions')
    expect(sourcePreviewControllerSource).toContain('projectSourceLinkedCardIngestRangeActions')
    expect(sourcePreviewControllerSource).toContain('projectSourceLinkedCardPreviewContent')
    expect(sourcePreviewControllerSource).toContain('projectSourceLinkedCardActionError')
    expect(sourcePreviewControllerSource).toContain('projectSourceLinkedCardDetailRows')
    expect(sourcePreviewControllerSource).toContain('projectSourceLinkedCardDetailsPanel')
    expect(sourcePreviewControllerSource).toContain('projectSourceLinkedCardEditorSheet')
    expect(sourcePreviewControllerSource).not.toContain('formatDateTime')
    expect(sourcePreviewControllerSource).not.toContain('createSourceLinkedCardDetailRows')
    expect(sourcePreviewControllerSource).not.toContain('formatSourceLinkedCardIngestChunkProgress')
    expect(sourcePreviewControllerSource).not.toContain('pendingRanges.length')
    expect(sourcePreviewControllerSource).not.toContain('pendingRanges.map')
    expect(sourcePreviewControllerSource).not.toContain('sourceProposal?.proposedContent')
    expect(sourcePreviewControllerSource).toMatch(/\n\s*const \[previewState, setPreviewState\] = useState\(createSourceLinkedCardPreviewState\)/)
    expect(sourcePreviewControllerSource).not.toMatch(/\n\s*const \[sheetOpen, setSheetOpen\] = useState\(false\)/)
    expect(sourcePreviewControllerSource).not.toMatch(/\n\s*const \[sourceDetailsOpen, setSourceDetailsOpen\] = useState\(false\)/)
    expect(sourcePreviewControllerSource).not.toContain("content.kind === 'ready'")
    expect(sourcePreviewControllerSource).not.toContain('file: content.bodyFile')
    expect(sourcePreviewControllerSource).not.toContain('stagedSourceText: stagedIngestContent')
    expect(sourcePreviewControllerSource).not.toMatch(/\nfunction resourceMetaTailId\(/)
    expect(sourcePreviewControllerSource).not.toMatch(/\nfunction formatIngestChunkProgress\(/)
    expect(sourcePreviewControllerSource).toContain('projectFileEditorRichTextSourceInput')
    expect(sourcePreviewControllerSource).toContain('hasPendingIngestRanges')
    expect(sourcePreviewControllerSource).not.toContain('FileEditorSheet')
    expect(sourcePreviewControllerSource).not.toContain('RichTextFileEditor')
    expect(sourcePreviewModelSource).toContain('export function createSourceLinkedCardActionErrorId')
    expect(sourcePreviewModelSource).toContain('export type SourceLinkedCardPreviewState')
    expect(sourcePreviewModelSource).toContain('export function createSourceLinkedCardPreviewState')
    expect(sourcePreviewModelSource).toContain('export function projectSourceLinkedCardPreviewSheetOpen')
    expect(sourcePreviewModelSource).toContain('export function projectSourceLinkedCardPreviewSourceDetailsToggled')
    expect(sourcePreviewModelSource).toContain('export function formatSourceLinkedCardIngestChunkProgress')
    expect(sourcePreviewModelSource).toContain('export function projectSourceLinkedCardPrimaryActions')
    expect(sourcePreviewModelSource).toContain('export function projectSourceLinkedCardIngestRangeActions')
    expect(sourcePreviewModelSource).toContain('export function projectSourceLinkedCardPreviewContent')
    expect(sourcePreviewModelSource).toContain('export function projectSourceLinkedCardActionError')
    expect(sourcePreviewModelSource).toContain('export function projectSourceLinkedCardStagedIngestContent')
    expect(sourcePreviewModelSource).toContain('export function projectSourceLinkedCardDetailRows')
    expect(sourcePreviewModelSource).toContain('export function projectSourceLinkedCardDetailsPanel')
    expect(sourcePreviewModelSource).toContain('export function projectSourceLinkedCardEditorSheet')
    expect(sourcePreviewModelSource).not.toContain('useState')
    expect(sourcePreviewModelSource).not.toContain('useMemo')
    expect(sourcePreviewModelSource).not.toContain('FileEditorSheet')
    expect(sourcePreviewModelSource).not.toContain('RichTextFileEditor')
    expect(sourcePreviewSource).not.toContain('FileDetailPane')
    expect(detailPreviewShimSource).toMatch(/^export \* from '..\/features\/detail\/FileDetailPreview'\n?$/)
    expect(sourcePreviewShimSource).toMatch(/^export \* from '..\/features\/detail\/FileDetailSourceLinkedCardPreview'\n?$/)
  })

  it('keeps shared detail preview primitives outside both container and source-card preview modules', () => {
    const detailPaneSource = readFileSync(detailPanePath, 'utf8')

    expect(existsSync(detailPreviewPath)).toBe(true)
    expect(existsSync(previewPrimitivesPath)).toBe(true)
    expect(existsSync(previewPrimitivesShimPath)).toBe(true)
    if (!existsSync(detailPreviewPath) || !existsSync(previewPrimitivesPath) || !existsSync(previewPrimitivesShimPath)) return

    const detailPreviewSource = readFileSync(detailPreviewPath, 'utf8')
    const sourcePreviewSource = existsSync(sourcePreviewPath) ? readFileSync(sourcePreviewPath, 'utf8') : ''
    const primitivesSource = readFileSync(previewPrimitivesPath, 'utf8')
    const primitivesShimSource = readFileSync(previewPrimitivesShimPath, 'utf8')

    expect(detailPaneSource).toContain("from './FileDetailPreview'")
    expect(detailPaneSource).not.toContain("from '../../components/FileDetailPreview'")
    expect(detailPaneSource).not.toContain("from './FileDetailPreviewPrimitives'")
    expect(detailPreviewSource).toContain("from '../../ui/FileDetailPreviewPrimitives'")
    expect(sourcePreviewSource).toContain("from '../../ui/FileDetailPreviewPrimitives'")
    expect(detailPreviewSource).not.toContain("from '../../components/FileDetailPreviewPrimitives'")
    expect(sourcePreviewSource).not.toContain("from '../../components/FileDetailPreviewPrimitives'")
    expect(detailPaneSource).not.toMatch(/\nfunction ModeCard\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction RawTextBlock\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction DetailRows\(/)
    expect(sourcePreviewSource).not.toMatch(/\nfunction ModeCard\(/)
    expect(sourcePreviewSource).not.toMatch(/\nfunction RawTextBlock\(/)
    expect(sourcePreviewSource).not.toMatch(/\nfunction DetailRows\(/)

    expect(primitivesSource).toMatch(/\nexport function ModeCard\(/)
    expect(primitivesSource).toMatch(/\nexport function RawTextBlock\(/)
    expect(primitivesSource).toMatch(/\nexport function DetailRows\(/)
    expect(primitivesSource).not.toContain('resourceMetaTailId')
    expect(primitivesSource).not.toContain('formatIngestChunkProgress')
    expect(primitivesSource).not.toContain('Ingest')
    expect(primitivesSource).not.toContain('meta')
    expect(primitivesSource).not.toContain('useFilesStore')
    expect(primitivesShimSource).toMatch(/^export \* from '..\/ui\/FileDetailPreviewPrimitives'\n?$/)
  })
})
