import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const detailPanePath = 'src/modules/files/features/detail/FileDetailPane.tsx'
const detailPreviewPath = 'src/modules/files/features/detail/FileDetailPreview.tsx'
const detailPreviewModelPath = 'src/modules/files/features/detail/file-detail-preview-model.ts'
const editablePreviewControllerPath = 'src/modules/files/features/detail/useEditableFilePreviewController.ts'
const authenticatedImagePreviewControllerPath = 'src/modules/files/features/detail/useAuthenticatedImagePreviewController.ts'
const detailPreviewShimPath = 'src/modules/files/components/FileDetailPreview.tsx'

describe('FileDetailPreview architecture boundary', () => {
  it('keeps preview mode dispatch and concrete preview renderers out of the detail-pane shell', () => {
    const detailPaneSource = readFileSync(detailPanePath, 'utf8')

    expect(existsSync(detailPreviewPath)).toBe(true)
    expect(existsSync(detailPreviewModelPath)).toBe(true)
    expect(existsSync(editablePreviewControllerPath)).toBe(true)
    expect(existsSync(authenticatedImagePreviewControllerPath)).toBe(true)
    expect(existsSync(detailPreviewShimPath)).toBe(true)
    if (!existsSync(detailPreviewPath) || !existsSync(detailPreviewModelPath) || !existsSync(editablePreviewControllerPath) || !existsSync(authenticatedImagePreviewControllerPath) || !existsSync(detailPreviewShimPath)) return

    const detailPreviewSource = readFileSync(detailPreviewPath, 'utf8')
    const detailPreviewModelSource = readFileSync(detailPreviewModelPath, 'utf8')
    const editablePreviewControllerSource = readFileSync(editablePreviewControllerPath, 'utf8')
    const authenticatedImagePreviewControllerSource = readFileSync(authenticatedImagePreviewControllerPath, 'utf8')
    const detailPreviewShimSource = readFileSync(detailPreviewShimPath, 'utf8')

    expect(detailPaneSource).toContain("from './FileDetailPreview'")
    expect(detailPaneSource).not.toContain("from '../../components/FileDetailPreview'")
    expect(detailPaneSource).not.toMatch(/\nfunction PreviewTab\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction EditableFilePreview\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction SidecarPreview\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction ReadonlyPreview\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction AuthenticatedImagePreview\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction LineageTab\(/)
    expect(detailPaneSource).not.toContain('useBlobResource')
    expect(detailPaneSource).not.toContain("from './LockedVocabTablePreview'")
    expect(detailPaneSource).not.toContain("from './StructuredTablePreview'")
    expect(detailPaneSource).not.toContain("from './FileEditorSheet'")
    expect(detailPaneSource).not.toContain("from './FolderDetailPreview'")
    expect(detailPaneSource).not.toContain("from './FileDetailSourceLinkedCardPreview'")
    expect(detailPaneSource).not.toContain("from './FileDetailPreviewPrimitives'")

    expect(detailPreviewSource).toMatch(/\nexport function FileDetailPreview\(/)
    expect(detailPreviewSource).toMatch(/\nexport function FileDetailLineage\(/)
    expect(detailPreviewSource).toContain('getFilesEntryOpenMode')
    expect(detailPreviewSource).toContain('StructuredResourcePreview')
    expect(detailPreviewSource).toContain('LockedVocabTablePreview')
    expect(detailPreviewSource).toContain('FolderDetailPreview')
    expect(detailPreviewSource).toContain('FileEditorSheet')
    expect(detailPreviewSource).toContain('SourceLinkedCardPreview')
    expect(detailPreviewSource).toContain("from './file-detail-preview-model'")
    expect(detailPreviewSource).toContain('projectEditableFilePreviewModel')
    expect(detailPreviewSource).toContain('projectFileDetailLineageModel')
    expect(detailPreviewSource).toContain('projectReadonlyFilePreviewModel')
    expect(detailPreviewSource).toContain('projectAuthenticatedImagePreviewRenderState')
    expect(detailPreviewSource).toContain('projectFileDetailSidecarPreviewModel')
    expect(detailPreviewSource).toContain('sidecarPreview.showRows')
    expect(detailPreviewSource).not.toContain('sidecarPreview.rows.length')
    expect(detailPreviewSource).not.toContain("label === 'provider'")
    expect(detailPreviewSource).not.toContain('resolveFilesSidecarPlacement')
    expect(detailPreviewSource).not.toContain("semanticKind === 'access-policy-sidecar'")
    expect(detailPreviewSource).not.toContain("semanticKind === 'meta-sidecar'")
    expect(detailPreviewSource).not.toContain('formatBytes')
    expect(detailPreviewSource).not.toContain('formatDateTime')
    expect(detailPreviewSource).not.toContain('getFilesEntrySemanticLabel')
    expect(detailPreviewSource).not.toContain('getFilesOpenModeLabel')
    expect(detailPreviewSource).not.toContain('getFilesEntrySemanticPolicy')
    expect(detailPreviewSource).not.toContain('资源类别')
    expect(detailPreviewSource).not.toContain("label === '处理语义'")
    expect(detailPreviewSource).not.toContain("label === 'URI'")
    expect(detailPreviewSource).not.toMatch(/\n\s*const fileFacts = /)
    expect(detailPreviewSource).not.toMatch(/if \(file\.previewText\)/)
    expect(detailPreviewSource).not.toContain("file.mimeType?.startsWith('image/')")
    expect(detailPreviewSource).not.toContain("file.previewUnavailableReason ?? '当前资源暂不支持内联预览。'")
    expect(detailPreviewSource).not.toContain("file.previewUnavailableReason ?? '当前图像暂时不能内联预览。'")
    expect(detailPreviewSource).not.toContain("file.mimeType ?? '未知类型'")
    expect(detailPreviewSource).toContain("from './useEditableFilePreviewController'")
    expect(detailPreviewSource).toContain('useEditableFilePreviewController')
    expect(detailPreviewSource).toContain("from './useAuthenticatedImagePreviewController'")
    expect(detailPreviewSource).toContain('useAuthenticatedImagePreviewController')
    expect(detailPreviewSource).not.toContain('imagePreview.isLoading')
    expect(detailPreviewSource).not.toContain('imagePreview.objectUrl')
    expect(detailPreviewSource).not.toContain('imagePreview.error')
    expect(detailPreviewSource).not.toContain('useBlobResource')
    expect(detailPreviewSource).not.toContain('URL.createObjectURL')
    expect(detailPreviewSource).not.toContain('URL.revokeObjectURL')
    expect(detailPreviewSource).not.toContain('useFilesStore')
    expect(detailPreviewSource).not.toContain('editableFileSheetOpenRequestUri')
    expect(detailPreviewSource).not.toContain('consumeEditableFileSheetOpenRequest')
    expect(detailPreviewSource).not.toContain('useFileDetail')
    expect(detailPreviewSource).not.toContain('useFavoriteList')
    expect(detailPreviewSource).not.toContain('ResourceMetaDrawer')
    expect(detailPreviewSource).not.toContain('ResourceSidecarActions')
    expect(detailPreviewSource).not.toContain('FileDetailPane')
    expect(editablePreviewControllerSource).toContain('export function useEditableFilePreviewController')
    expect(editablePreviewControllerSource).toContain('useFilesStore')
    expect(editablePreviewControllerSource).toContain('editableFileSheetOpenRequestUri')
    expect(editablePreviewControllerSource).toContain('consumeEditableFileSheetOpenRequest')
    expect(editablePreviewControllerSource).not.toContain('FileEditorSheet')
    expect(editablePreviewControllerSource).not.toContain('Button')
    expect(authenticatedImagePreviewControllerSource).toContain('export function useAuthenticatedImagePreviewController')
    expect(authenticatedImagePreviewControllerSource).toContain('useBlobResource')
    expect(authenticatedImagePreviewControllerSource).toContain('URL.createObjectURL')
    expect(authenticatedImagePreviewControllerSource).toContain('URL.revokeObjectURL')
    expect(authenticatedImagePreviewControllerSource).not.toContain('<img')
    expect(authenticatedImagePreviewControllerSource).not.toContain('FileText')
    expect(detailPreviewModelSource).toContain('export function projectFileDetailSidecarPreviewModel')
    expect(detailPreviewModelSource).toContain("kind: 'provider'")
    expect(detailPreviewModelSource).toContain('export function projectEditableFilePreviewModel')
    expect(detailPreviewModelSource).toContain("kind: 'uri'")
    expect(detailPreviewModelSource).toContain('export function projectFileDetailLineageModel')
    expect(detailPreviewModelSource).toContain('semanticSection')
    expect(detailPreviewModelSource).toContain('export function projectReadonlyFilePreviewModel')
    expect(detailPreviewModelSource).toContain('export function projectAuthenticatedImagePreviewRenderState')
    expect(detailPreviewModelSource).toContain('resolveFilesSidecarPlacement')
    expect(detailPreviewModelSource).not.toContain('useState')
    expect(detailPreviewModelSource).not.toContain('<')
    expect(detailPreviewShimSource).toMatch(/^export \* from '..\/features\/detail\/FileDetailPreview'\n?$/)
  })
})
