import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const treePanePath = 'src/modules/files/features/tree/FilesTreePane.tsx'
const treePaneControllerPath = 'src/modules/files/features/tree/useFilesTreePaneController.ts'
const treeModelPath = 'src/modules/files/domain/resource/tree-model.ts'

describe('FilesTreePane architecture boundary', () => {
  it('keeps tree data, workspace context, and store workflow in a pane controller', () => {
    expect(existsSync(treePanePath)).toBe(true)
    expect(existsSync(treePaneControllerPath)).toBe(true)
    expect(existsSync(treeModelPath)).toBe(true)
    if (!existsSync(treePanePath) || !existsSync(treePaneControllerPath) || !existsSync(treeModelPath)) return

    const treePaneSource = readFileSync(treePanePath, 'utf8')
    const controllerSource = readFileSync(treePaneControllerPath, 'utf8')
    const treeModelSource = readFileSync(treeModelPath, 'utf8')

    expect(treePaneSource).toContain("from './useFilesTreePaneController'")
    expect(treePaneSource).toContain('useFilesTreePaneController')
    expect(treePaneSource).toContain('useFilesTreeChildrenController')
    expect(treePaneSource).not.toContain('useFilesStore')
    expect(treePaneSource).not.toContain('useFilesRootNodes')
    expect(treePaneSource).not.toContain('useContainerChildTreeNodes')
    expect(treePaneSource).not.toContain('useActiveFilesWorkspaceContext')
    expect(treePaneSource).not.toMatch(/\nfunction canExpandTreeNode\(/)
    expect(treePaneSource).not.toMatch(/\n\s*const description = /)
    expect(treePaneSource).not.toMatch(/\n\s*const treeNodes = /)
    expect(treePaneSource).toContain('tree.contentState')
    expect(treePaneSource).toContain('treeChildren.childrenState')
    expect(treePaneSource).not.toContain('tree.isLoading')
    expect(treePaneSource).not.toContain('tree.error')
    expect(treePaneSource).not.toContain('treeChildren.isLoading')
    expect(treePaneSource).toContain('tree.chrome.searchPlaceholder')
    expect(treePaneSource).toContain('tree.chrome.clearSearchLabel')
    expect(treePaneSource).toContain('tree.chrome.emptySearchLabel')
    expect(treePaneSource).toContain('tree.chrome.treeLabel')
    expect(treePaneSource).toContain('tree.chrome.rootLoadingLabel')
    expect(treePaneSource).toContain('tree.chrome.rootErrorLabel')
    expect(treePaneSource).toContain('treeChildren.chrome.childLoadingLabel')
    expect(treePaneSource).toContain('nodeState.toggleLabel')
    expect(treePaneSource).not.toContain('资源范围')
    expect(treePaneSource).not.toContain('收起资源栏')
    expect(treePaneSource).not.toContain('展开资源栏')
    expect(treePaneSource).not.toContain('搜索文件树')
    expect(treePaneSource).not.toContain('文件分组树')
    expect(treePaneSource).not.toContain('正在读取子容器')
    expect(treePaneSource).not.toContain('正在加载容器')
    expect(treePaneSource).not.toContain('读取容器失败')

    expect(controllerSource).toContain('export function useFilesTreePaneController')
    expect(controllerSource).toContain('export function useFilesTreeChildrenController')
    expect(controllerSource).toContain('useFilesStore')
    expect(controllerSource).toContain('useFilesRootNodes')
    expect(controllerSource).toContain('useContainerChildTreeNodes')
    expect(controllerSource).toContain('useFilesTreeSearchEntries')
    expect(controllerSource).toContain('useSelectedFilesLocation')
    expect(controllerSource).toContain('projectFilesTreeNodeViewState')
    expect(controllerSource).toContain('projectFilesTreeSearchResults')
    expect(controllerSource).toContain('projectFilesTreeChromeModel')
    expect(controllerSource).toContain('projectFilesTreeContentState')
    expect(controllerSource).toContain('projectFilesTreeChildrenState')
    expect(controllerSource).not.toContain('canExpandFilesTreeNode')
    expect(controllerSource).not.toContain('当前话题：')
    expect(controllerSource).not.toContain('浏览当前 Pod 容器')
    expect(controllerSource).not.toContain('TreeNodeItem')
    expect(controllerSource).not.toContain('CollapsedTreeRail')
    expect(controllerSource).not.toContain('TreeSectionHeader')
    expect(controllerSource).not.toContain('ScrollArea')

    expect(treeModelSource).toContain('export function canExpandFilesTreeNode')
    expect(treeModelSource).toContain('export function projectFilesTreeContentState')
    expect(treeModelSource).toContain('export function projectFilesTreeChildrenState')
    expect(treeModelSource).toContain('export function projectFilesTreeNodeViewState')
    expect(treeModelSource).toContain('export function projectFilesTreeSearchResults')
    expect(treeModelSource).toContain('export function projectFilesTreeChromeModel')
    expect(treeModelSource).not.toContain('useFilesStore')
    expect(treeModelSource).not.toContain('useFilesRootNodes')
    expect(treeModelSource).not.toContain('useContainerChildTreeNodes')
  })
})
