import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const listPanePath = 'src/modules/files/features/list/FilesListPane.tsx'
const listPaneControllerPath = 'src/modules/files/features/list/useFilesListPaneController.ts'
const listSelectionControllerPath = 'src/modules/files/features/list/useFilesListSelectionController.ts'
const listOperationControllerPath = 'src/modules/files/features/list/useFilesListOperationController.ts'
const listOperationModelPath = 'src/modules/files/domain/list/files-list-operation-model.ts'
const listSelectionModelPath = 'src/modules/files/domain/list/files-list-selection-model.ts'

describe('FilesListPane architecture boundary', () => {
  it('keeps list data, projection, open decision, and platform copy in a pane controller', () => {
    expect(existsSync(listPanePath)).toBe(true)
    expect(existsSync(listPaneControllerPath)).toBe(true)
    if (!existsSync(listPanePath) || !existsSync(listPaneControllerPath)) return

    const listPaneSource = readFileSync(listPanePath, 'utf8')
    const paneControllerSource = readFileSync(listPaneControllerPath, 'utf8')

    expect(listPaneSource).toContain("from './useFilesListPaneController'")
    expect(listPaneSource).toContain('useFilesListPaneController')
    expect(listPaneSource).toContain('listPane.contentState')
    expect(listPaneSource).toContain('listPane.contentState.loadingState')
    expect(listPaneSource).toContain('listPane.scopeHeader')
    expect(listPaneSource).toContain('listPane.toolbarChrome')
    expect(listPaneSource).toContain('toolbarChrome.searchPlaceholder')
    expect(listPaneSource).toContain('toolbarChrome.clearSearchLabel')
    expect(listPaneSource).not.toContain('最近文件')
    expect(listPaneSource).not.toContain('正在读取资源')
    expect(listPaneSource).not.toContain('稍等，正在从当前空间读取内容。')
    expect(listPaneSource).not.toContain('资源工具栏')
    expect(listPaneSource).not.toContain('搜索当前范围...')
    expect(listPaneSource).not.toContain('类型筛选')
    expect(listPaneSource).not.toContain('全部类型')
    expect(listPaneSource).not.toContain('标签筛选')
    expect(listPaneSource).not.toContain('全部标签')
    expect(listPaneSource).not.toContain('useFilesStore')
    expect(listPaneSource).not.toContain('useFilesEntries')
    expect(listPaneSource).not.toContain('useSelectedFilesLocation')
    expect(listPaneSource).not.toContain('copyFilesText')
    expect(listPaneSource).not.toContain('resolveFilesListOpenDecision')
    expect(listPaneSource).not.toContain('projectBrowsableFiles')
    expect(listPaneSource).not.toContain('projectVisibleFiles')
    expect(listPaneSource).not.toContain('getRecentFiles')
    expect(listPaneSource).not.toContain('getVisibleMimeTypeOptions')
    expect(listPaneSource).not.toContain('getVisibleTagOptions')
    expect(listPaneSource).not.toContain('getFilesListErrorState')
    expect(listPaneSource).not.toContain('projectFilesListRow')
    expect(listPaneSource).not.toContain('listPane.selection.kind')
    expect(listPaneSource).not.toContain('listPane.files.length')
    expect(listPaneSource).not.toContain('listPane.isLoading')
    expect(listPaneSource).not.toMatch(/listPane\.error(?!State)/)
    expect(listPaneSource).not.toContain('listPane.hasVisibleFiles')
    expect(listPaneSource).not.toContain('tagOptions.length === 0')
    expect(listPaneSource).not.toMatch(/\n\s*const openFile = /)
    expect(listPaneSource).not.toMatch(/\n\s*const sortList = /)
    expect(listPaneSource).not.toMatch(/\n\s*const copySelectedFileUris = /)
    expect(listPaneSource).not.toMatch(/\n\s*const copyContextFileUris = /)
    expect(listPaneSource).not.toMatch(/\n\s*const emptyState = /)
    expect(listPaneSource).not.toMatch(/\n\s*const errorState = /)

    expect(paneControllerSource).toContain('export function useFilesListPaneController')
    expect(paneControllerSource).toContain('useFilesStore')
    expect(paneControllerSource).toContain('useFilesEntries')
    expect(paneControllerSource).toContain('useSelectedFilesLocation')
    expect(paneControllerSource).toContain('copyFilesText')
    expect(paneControllerSource).toContain('resolveFilesListOpenDecision')
    expect(paneControllerSource).toContain('projectVisibleFiles')
    expect(paneControllerSource).toContain('projectFilesListBaseEntries')
    expect(paneControllerSource).toContain('getVisibleMimeTypeOptions')
    expect(paneControllerSource).toContain('getVisibleTagOptions')
    expect(paneControllerSource).toContain('getFilesListErrorState')
    expect(paneControllerSource).toContain('projectFilesListVisibleRows')
    expect(paneControllerSource).toContain('projectFilesListEmptyStateModel')
    expect(paneControllerSource).toContain('projectFilesListCopyText')
    expect(paneControllerSource).toContain('projectFilesListContentState')
    expect(paneControllerSource).toContain('projectFilesListScopeHeaderModel')
    expect(paneControllerSource).toContain('projectFilesListToolbarChromeModel')
    expect(paneControllerSource).toContain('visibleRows')
    expect(paneControllerSource).toContain('showRecentScopeHeader')
    expect(paneControllerSource).toContain('toolbarChrome')
    expect(paneControllerSource).not.toContain("selection.kind === 'recent'")
    expect(paneControllerSource).toContain('hasVisibleFiles')
    expect(paneControllerSource).toContain('canFilterByTag')
    expect(paneControllerSource).not.toContain("from '../../ui/FilesListRow'")
    expect(paneControllerSource).not.toContain("from 'lucide-react'")
    expect(paneControllerSource).not.toContain('FileText')
    expect(paneControllerSource).not.toContain('FolderOpen')
    expect(paneControllerSource).not.toContain('HardDrive')
    expect(paneControllerSource).not.toContain('projectFilesListRow')
    expect(paneControllerSource).not.toContain('files.map')
    expect(paneControllerSource).not.toContain('filesToCopy.map')
    expect(paneControllerSource).not.toContain('当前话题绑定的是本地目录')
    expect(paneControllerSource).not.toContain('没有匹配的资源')
    expect(paneControllerSource).not.toContain('还没有最近文件')
    expect(paneControllerSource).not.toContain('当前聊天没有关联文件')
    expect(paneControllerSource).not.toContain('当前容器为空')
    expect(paneControllerSource).not.toContain('<FilesListRow')
    expect(paneControllerSource).not.toContain('FilesOperationSheet')
    expect(paneControllerSource).not.toContain('ContextMenuContent')
    expect(paneControllerSource).not.toContain('DropdownMenu')
  })

  it('keeps list selection and context-menu selection state in a feature controller', () => {
    expect(existsSync(listPanePath)).toBe(true)
    expect(existsSync(listPaneControllerPath)).toBe(true)
    expect(existsSync(listSelectionControllerPath)).toBe(true)
    expect(existsSync(listOperationControllerPath)).toBe(true)
    expect(existsSync(listOperationModelPath)).toBe(true)
    expect(existsSync(listSelectionModelPath)).toBe(true)
    if (
      !existsSync(listPanePath)
      || !existsSync(listPaneControllerPath)
      || !existsSync(listSelectionControllerPath)
      || !existsSync(listOperationControllerPath)
      || !existsSync(listOperationModelPath)
      || !existsSync(listSelectionModelPath)
    ) return

    const listPaneSource = readFileSync(listPanePath, 'utf8')
    const paneControllerSource = readFileSync(listPaneControllerPath, 'utf8')
    const selectionControllerSource = readFileSync(listSelectionControllerPath, 'utf8')
    const operationControllerSource = readFileSync(listOperationControllerPath, 'utf8')
    const operationModelSource = readFileSync(listOperationModelPath, 'utf8')
    const selectionModelSource = readFileSync(listSelectionModelPath, 'utf8')

    expect(listPaneSource).toContain("from './useFilesListPaneController'")
    expect(listPaneSource).toContain("from './useFilesListSelectionController'")
    expect(listPaneSource).toContain("from './useFilesListOperationController'")
    expect(listPaneSource).not.toContain('selectionAnchorId')
    expect(listPaneSource).not.toContain('setSelectionAnchorId')
    expect(listPaneSource).not.toContain('contextMenuSelectionTimerRef')
    expect(listPaneSource).not.toContain('contextMenuTargetRef')
    expect(listPaneSource).not.toContain('contextMenuActionTakenRef')
    expect(listPaneSource).not.toContain('setContextMenuTargetUri')
    expect(listPaneSource).not.toContain('event?.shiftKey')
    expect(listPaneSource).not.toContain('event?.metaKey')
    expect(listPaneSource).not.toContain('event?.ctrlKey')
    expect(listPaneSource).not.toContain('selectedVisibleFiles.length')
    expect(listPaneSource).not.toContain('isBatchContext')
    expect(listPaneSource).toContain('listSelection.batchSelectionActions.copyLabel')
    expect(listPaneSource).toContain('listSelection.batchSelectionActions.deleteLabel')
    expect(listPaneSource).not.toContain('复制所选 URI')
    expect(listPaneSource).not.toContain('删除所选项')
    expect(listPaneSource).toContain('contextMenuView.openLabel')
    expect(listPaneSource).toContain('contextMenuView.renameLabel')
    expect(listPaneSource).toContain('contextMenuView.copyToLabel')
    expect(listPaneSource).toContain('contextMenuView.moveToLabel')
    expect(listPaneSource).not.toContain('>打开<')
    expect(listPaneSource).not.toContain('>重命名<')
    expect(listPaneSource).not.toContain('>复制到...</ContextMenuItem>')
    expect(listPaneSource).not.toContain('>移动到...</ContextMenuItem>')
    expect(listPaneSource).not.toMatch(/\n\s*const replaceFileSelection = /)
    expect(listPaneSource).not.toMatch(/\n\s*const selectVisibleFile = /)
    expect(listPaneSource).not.toMatch(/\n\s*const applyContextMenuSelection = /)
    expect(listPaneSource).not.toMatch(/\n\s*const prepareContextMenuSelection = /)
    expect(listPaneSource).not.toMatch(/\n\s*const applyContextMenuSelectionAfterClose = /)
    expect(listPaneSource).not.toMatch(/\n\s*const handleContextMenuOpenChange = /)
    expect(listPaneSource).not.toMatch(/\n\s*const runContextMenuAction = /)
    expect(listPaneSource).not.toMatch(/\n\s*const contextSelectionForFile = /)
    expect(listPaneSource).not.toContain('useCopyFileResource')
    expect(listPaneSource).not.toContain('useMoveFileResource')
    expect(listPaneSource).not.toContain('useDeleteFileResource')
    expect(listPaneSource).not.toContain('resolveFolderChildRenameDestination')
    expect(listPaneSource).not.toContain('resolveFolderChildTransferDestination')
    expect(listPaneSource).not.toMatch(/\ntype FilesListOperation =/)
    expect(listPaneSource).not.toMatch(/\n\s*const operation = /)
    expect(listPaneSource).not.toMatch(/\n\s*const operationValue = /)
    expect(listPaneSource).not.toMatch(/\n\s*const runDeleteFiles = /)
    expect(listPaneSource).not.toMatch(/\n\s*const openOperationAfterMenuClose = /)
    expect(listPaneSource).not.toMatch(/\n\s*const openTransferContextFile = /)
    expect(listPaneSource).not.toMatch(/\n\s*const openRenameContextFile = /)
    expect(listPaneSource).not.toMatch(/\n\s*const openDeleteContextFiles = /)
    expect(listPaneSource).not.toMatch(/\n\s*const transferDestination = /)
    expect(listPaneSource).not.toMatch(/\n\s*const renameDestination = /)
    expect(listPaneSource).not.toMatch(/\n\s*const operationValidationMessage = /)
    expect(listPaneSource).not.toMatch(/\n\s*const confirmOperation = /)
    expect(listPaneSource).not.toMatch(/\n\s*const operationSheetModel = /)

    expect(selectionControllerSource).toContain('export function useFilesListSelectionController')
    expect(selectionControllerSource).toContain("from '../../domain/list/files-list-selection-model'")
    expect(selectionControllerSource).toContain('createFilesListInteractionState')
    expect(selectionControllerSource).toContain('projectFilesListInteractionAnchor')
    expect(selectionControllerSource).toContain('projectFilesListInteractionContextTarget')
    expect(selectionControllerSource).toContain('projectFilesListInteractionReset')
    expect(selectionControllerSource).toContain('projectFilesListSelectionProjection')
    expect(selectionControllerSource).toContain('projectFilesListRangeSelectionUris')
    expect(selectionControllerSource).toContain('projectFilesListContextSelection')
    expect(selectionControllerSource).toContain('projectFilesListContextMenuView')
    expect(selectionControllerSource).toContain('shouldApplyFilesListContextSelection')
    expect(selectionControllerSource).toMatch(/\n\s*const \[interactionState, setInteractionState\] = useState\(createFilesListInteractionState\)/)
    expect(selectionControllerSource).toContain('selectionAnchorId')
    expect(selectionControllerSource).toContain('contextMenuSelectionTimerRef')
    expect(selectionControllerSource).toContain('contextMenuTargetRef')
    expect(selectionControllerSource).toContain('contextMenuActionTakenRef')
    expect(selectionControllerSource).toContain('selectVisibleFile')
    expect(selectionControllerSource).toContain('prepareContextMenuSelection')
    expect(selectionControllerSource).toContain('handleContextMenuOpenChange')
    expect(selectionControllerSource).toContain('runContextMenuAction')
    expect(selectionControllerSource).toContain('contextSelectionForFile')
    expect(selectionControllerSource).toContain('contextMenuViewForFile')
    expect(selectionControllerSource).toContain('batchSelectionLabel')
    expect(selectionControllerSource).toContain('batchSelectionActions')
    expect(selectionControllerSource).toContain('hasSelectedVisibleFiles')
    expect(selectionControllerSource).not.toContain('files.filter')
    expect(selectionControllerSource).not.toContain('files.slice')
    expect(selectionControllerSource).not.toContain('files.findIndex')
    expect(selectionControllerSource).not.toContain('selectedVisibleFiles.length > 1')
    expect(selectionControllerSource).not.toContain('targetFiles.length')
    expect(selectionControllerSource).not.toMatch(/\n\s*const \[selectionAnchorId, setSelectionAnchorId\]/)
    expect(selectionControllerSource).not.toMatch(/\n\s*const \[contextMenuTargetUri, setContextMenuTargetUri\]/)
    expect(selectionControllerSource).not.toContain('复制所选 URI')
    expect(selectionControllerSource).not.toContain('删除所选项')
    expect(selectionControllerSource).not.toContain('useCopyFileResource')
    expect(selectionControllerSource).not.toContain('useMoveFileResource')
    expect(selectionControllerSource).not.toContain('useDeleteFileResource')
    expect(selectionControllerSource).not.toContain('FilesOperationSheet')
    expect(selectionModelSource).toContain('export type FilesListInteractionState')
    expect(selectionModelSource).toContain('export function createFilesListInteractionState')
    expect(selectionModelSource).toContain('export function projectFilesListInteractionAnchor')
    expect(selectionModelSource).toContain('export function projectFilesListInteractionContextTarget')
    expect(selectionModelSource).toContain('export function projectFilesListInteractionReset')
    expect(selectionModelSource).toContain('openLabel')
    expect(selectionModelSource).toContain('renameLabel')
    expect(selectionModelSource).toContain('copyToLabel')
    expect(selectionModelSource).toContain('moveToLabel')
    expect(selectionModelSource).toContain('batchSelectionActions')
    expect(selectionModelSource).not.toContain("from 'react'")
    expect(operationControllerSource).toContain('export function useFilesListOperationController')
    expect(operationControllerSource).toContain("from '../../domain/list/files-list-operation-model'")
    expect(operationControllerSource).toContain('type FilesListOperation')
    expect(operationControllerSource).toContain('createFilesListOperationState')
    expect(operationControllerSource).toContain('projectFilesListOperationOpened')
    expect(operationControllerSource).toContain('projectFilesListOperationReset')
    expect(operationControllerSource).toContain('projectFilesListOperationValuePatch')
    expect(operationControllerSource).toContain('projectFilesListOperationDestination')
    expect(operationControllerSource).toContain('projectFilesListOperationSheetModel')
    expect(operationControllerSource).toContain('projectFilesListOperationConfirmChrome')
    expect(operationControllerSource).toContain('canSubmitFilesListOperationSheet')
    expect(operationControllerSource).toContain('useCopyFileResource')
    expect(operationControllerSource).toContain('useMoveFileResource')
    expect(operationControllerSource).toContain('useDeleteFileResource')
    expect(operationControllerSource).not.toContain("from '../../domain/folder/folder-child-open'")
    expect(operationControllerSource).not.toContain('buildFolderChildCopyName')
    expect(operationControllerSource).not.toContain('resolveFolderChildRenameDestination')
    expect(operationControllerSource).not.toContain('resolveFolderChildTransferDestination')
    expect(operationControllerSource).not.toContain('目标路径没有变化')
    expect(operationControllerSource).not.toContain('目标位置已有同名资源')
    expect(operationControllerSource).not.toContain('当前文件夹已有同名资源')
    expect(operationControllerSource).not.toContain('名称不能包含路径或离开当前文件夹')
    expect(operationControllerSource).not.toContain('operation.files.length >')
    expect(operationControllerSource).not.toContain('operation.files.map')
    expect(operationControllerSource).not.toContain('operationValue.trim().length === 0')
    expect(operationControllerSource).not.toMatch(/\n\s*const \[operation, setOperation\]/)
    expect(operationControllerSource).not.toMatch(/\n\s*const \[operationValue, setOperationValue\]/)
    expect(operationControllerSource).not.toContain('setOperation(null)')
    expect(operationControllerSource).not.toContain("setOperationValue('')")
    expect(operationControllerSource).toContain('operationSheetModel')
    expect(operationControllerSource).toContain('operationConfirmChrome')
    expect(operationControllerSource).toContain('operationConfirmDisabled')
    expect(operationControllerSource).toContain('confirmOperation')
    expect(operationControllerSource).not.toContain('FilesOperationSheet')
    expect(operationModelSource).toContain('export type FilesListOperation')
    expect(operationModelSource).toContain('export type FilesListOperationState')
    expect(operationModelSource).toContain('export function createFilesListOperationState')
    expect(operationModelSource).toContain('export function getFilesListOperationInitialValue')
    expect(operationModelSource).toContain('export function projectFilesListOperationOpened')
    expect(operationModelSource).toContain('export function projectFilesListOperationValuePatch')
    expect(operationModelSource).toContain('export function projectFilesListOperationReset')
    expect(operationModelSource).toContain('export function projectFilesListOperationDestination')
    expect(operationModelSource).toContain('export function canSubmitFilesListOperationSheet')
    expect(operationModelSource).not.toContain('useToast')
    expect(operationModelSource).not.toContain('useState')
    expect(paneControllerSource).not.toContain('FilesOperationSheet')
  })
})
