import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const detailPanePath = 'src/modules/files/features/detail/FileDetailPane.tsx'
const metadataPanelsPath = 'src/modules/files/features/detail/FileDetailMetadataPanels.tsx'
const metadataPredicateControllerPath = 'src/modules/files/features/detail/useDetailMetaPredicateController.ts'
const metadataPanelsModelPath = 'src/modules/files/features/detail/file-detail-metadata-panels-model.ts'
const metadataPanelsShimPath = 'src/modules/files/components/FileDetailMetadataPanels.tsx'
const metadataEditorModelPath = 'src/modules/files/domain/detail/detail-metadata-editor-model.ts'
const rootMetadataEditorModelShimPath = 'src/modules/files/detail-metadata-editor-model.ts'

describe('File detail metadata panels architecture boundary', () => {
  it('keeps RDF metadata editing out of the detail-pane container module', () => {
    const detailPaneSource = readFileSync(detailPanePath, 'utf8')

    expect(existsSync(metadataPanelsPath)).toBe(true)
    expect(existsSync(metadataPredicateControllerPath)).toBe(true)
    expect(existsSync(metadataPanelsModelPath)).toBe(true)
    expect(existsSync(metadataPanelsShimPath)).toBe(true)
    expect(existsSync(metadataEditorModelPath)).toBe(true)
    expect(existsSync(rootMetadataEditorModelShimPath)).toBe(true)
    if (!existsSync(metadataPanelsPath) || !existsSync(metadataPredicateControllerPath) || !existsSync(metadataPanelsModelPath) || !existsSync(metadataPanelsShimPath)) return

    const metadataPanelsSource = readFileSync(metadataPanelsPath, 'utf8')
    const metadataPredicateControllerSource = readFileSync(metadataPredicateControllerPath, 'utf8')
    const metadataPanelsModelSource = readFileSync(metadataPanelsModelPath, 'utf8')
    const metadataPanelsShimSource = readFileSync(metadataPanelsShimPath, 'utf8')
    const metadataEditorModelSource = existsSync(metadataEditorModelPath)
      ? readFileSync(metadataEditorModelPath, 'utf8')
      : ''
    const rootMetadataEditorModelSource = existsSync(rootMetadataEditorModelShimPath)
      ? readFileSync(rootMetadataEditorModelShimPath, 'utf8')
      : ''

    expect(detailPaneSource).toContain("from './FileDetailMetadataPanels'")
    expect(detailPaneSource).not.toContain("from '../../components/FileDetailMetadataPanels'")
    expect(detailPaneSource).not.toMatch(/\nfunction DetailRdfMetadataPanel\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction FileRdfMetadataPanel\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction SourceLinkedCardMetadataPanel\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction SourceLinkedCardDrawerMetadata\(/)
    expect(detailPaneSource).not.toMatch(/\ntype DetailMetaPredicateKey = /)
    expect(detailPaneSource).not.toContain('useCreateStructuredCellChangeProposal')
    expect(detailPaneSource).not.toContain('usePendingStructuredCellChangeProposals')
    expect(detailPaneSource).not.toContain('extractFileMetaPredicateValues')
    expect(detailPaneSource).not.toContain('StructuredPredicateValueEditor')

    expect(metadataPanelsSource).toContain("from './useDetailMetaPredicateController'")
    expect(metadataPanelsSource).toContain("from './file-detail-metadata-panels-model'")
    expect(metadataPanelsSource).toContain("from '../structured/StructuredTableCellPrimitives'")
    expect(metadataPanelsSource).not.toContain("from '../../components/StructuredTableCellPrimitives'")
    expect(metadataPanelsSource).not.toContain("from '../../detail-metadata-editor-model'")
    expect(metadataPanelsSource).not.toContain('typedControls')
    expect(metadataPanelsSource).not.toContain('<select')
    expect(metadataPanelsSource).not.toContain('<input')
    expect(metadataPanelsSource).not.toContain('resolveFilesResourceSidecars')
    expect(metadataPanelsSource).not.toContain('extractFileMetaPredicateValues')
    expect(metadataPanelsSource).not.toContain('parseSourceLinkedCardTurtle')
    expect(metadataPanelsSource).not.toContain('sourceLinkedCardBodyUri')
    expect(metadataPanelsSource).not.toContain('literalDetailCellValue')
    expect(metadataPanelsSource).not.toContain('iriDetailCellValue')
    expect(metadataPanelsSource).toMatch(/\nfunction DetailRdfMetadataPanel\(/)
    expect(metadataPanelsSource).toMatch(/\nexport function FileRdfMetadataPanel\(/)
    expect(metadataPanelsSource).toMatch(/\nexport function SourceLinkedCardMetadataPanel\(/)
    expect(metadataPanelsSource).toMatch(/\nexport function SourceLinkedCardDrawerMetadata\(/)
    expect(metadataPanelsSource).toContain('StructuredPredicateValueEditor')
    expect(metadataPanelsSource).not.toContain('useToast')
    expect(metadataPanelsSource).not.toContain('useFilesCurrentPodRootUri')
    expect(metadataPanelsSource).not.toContain('useCreateStructuredCellChangeProposal')
    expect(metadataPanelsSource).not.toContain('usePendingStructuredCellChangeProposals')
    expect(metadataPanelsSource).not.toContain('createStructuredCellChangeProposal')
    expect(metadataPanelsSource).not.toContain('buildDetailPendingMetaPredicateProposalMap')
    expect(metadataPanelsSource).not.toContain('hydrateDetailMetaPredicateValues')
    expect(metadataPanelsSource).not.toContain('shouldCreateDetailMetaPredicateProposal')
    expect(metadataPanelsSource).not.toContain('detailReviewStatusOptions')
    expect(metadataPanelsSource).not.toContain('detailTagOptions')
    expect(metadataPanelsSource).not.toMatch(/\n\s*const \[[^\]]+\]\s*=\s*useState/)
    expect(metadataPanelsSource).not.toMatch(/\n\s*useEffect\(/)
    expect(metadataPanelsSource).not.toMatch(/\n\s*const [^=]+Ref\s*=\s*useRef/)
    expect(metadataPanelsSource).not.toMatch(/\nfunction sourceLinkedCardBodyUri\(/)
    expect(metadataPanelsSource).not.toMatch(/\nfunction splitTagValue\(/)
    expect(metadataPanelsSource).not.toMatch(/\nfunction literalCellValue\(/)
    expect(metadataPanelsSource).not.toMatch(/\nfunction iriCellValue\(/)
    expect(metadataPanelsSource).not.toMatch(/\nfunction displayLiteralCellValue\(/)
    expect(metadataPanelsSource).not.toMatch(/\nfunction latestDetailPendingProposal\(/)
    expect(metadataPanelsSource).not.toMatch(/\nfunction sameCellValues\(/)
    expect(metadataPanelsSource).not.toContain('SOURCE_LINKED_REVIEW_STATUS_OPTIONS')
    expect(metadataPanelsSource).not.toContain('FileDetailPane')
    expect(metadataPanelsSource).toContain('projectDetailMetaPredicateStatusChrome')
    expect(metadataPanelsSource).not.toContain("status === 'pending'")
    expect(metadataPanelsSource).not.toContain("status === 'error'")
    expect(metadataPanelsSource).not.toContain('待审核更改：${statusLabel}')
    expect(metadataPanelsSource).not.toContain('meta predicate 更改提交失败：${statusLabel}')

    expect(metadataPredicateControllerSource).toContain('export function useDetailMetaPredicateController')
    expect(metadataPredicateControllerSource).toContain('useToast')
    expect(metadataPredicateControllerSource).toContain('useFilesCurrentPodRootUri')
    expect(metadataPredicateControllerSource).toContain('useCreateStructuredCellChangeProposal')
    expect(metadataPredicateControllerSource).toContain('usePendingStructuredCellChangeProposals')
    expect(metadataPredicateControllerSource).toContain('createStructuredCellChangeProposal')
    expect(metadataPredicateControllerSource).toContain('buildDetailPendingMetaPredicateProposalMap')
    expect(metadataPredicateControllerSource).toContain('createDetailMetaPredicateEditorState')
    expect(metadataPredicateControllerSource).toContain('hydrateDetailMetaPredicateValues')
    expect(metadataPredicateControllerSource).toContain('projectDetailMetaPredicateEditorDraft')
    expect(metadataPredicateControllerSource).toContain('projectDetailMetaPredicateEditorHydration')
    expect(metadataPredicateControllerSource).toContain('projectDetailMetaPredicateEditorProposalStatus')
    expect(metadataPredicateControllerSource).toContain('resolveDetailMetaPredicateProposalStatus')
    expect(metadataPredicateControllerSource).toContain('shouldCreateDetailMetaPredicateProposal')
    expect(metadataPredicateControllerSource).toContain('detailReviewStatusOptions')
    expect(metadataPredicateControllerSource).toContain('detailTagOptions')
    expect(metadataPredicateControllerSource).not.toContain('inputClassName')
    expect(metadataPredicateControllerSource).not.toContain('commitValue')
    expect(metadataPredicateControllerSource).not.toContain('commitDraft')
    expect(metadataPredicateControllerSource).not.toContain('setValue')
    expect(metadataPredicateControllerSource).not.toContain('({ ...current, [predicateKey]:')
    expect(metadataPredicateControllerSource).not.toContain('lastHydratedMetaPredicateValuesRef')
    expect(metadataPredicateControllerSource).not.toContain('const [title, setTitle]')
    expect(metadataPredicateControllerSource).not.toContain('const [reviewStatus, setReviewStatus]')
    expect(metadataPredicateControllerSource).not.toContain('const [tags, setTags]')
    expect(metadataPredicateControllerSource).not.toContain('const [relationValue, setRelationValue]')
    expect(metadataPredicateControllerSource).not.toContain('StructuredPredicateValueEditor')

    expect(metadataPanelsModelSource).toContain('export function projectFileRdfMetadataPanelModel')
    expect(metadataPanelsModelSource).toContain('export function projectSourceLinkedCardMetadataPanelModel')
    expect(metadataPanelsModelSource).toContain('export function projectSourceLinkedCardDrawerMetadataPanelModel')
    expect(metadataPanelsModelSource).toContain('export function projectDetailMetaPredicateStatusChrome')
    expect(metadataPanelsModelSource).toContain('resolveFilesResourceSidecars')
    expect(metadataPanelsModelSource).toContain('extractFileMetaPredicateValues')
    expect(metadataPanelsModelSource).toContain('parseSourceLinkedCardTurtle')
    expect(metadataPanelsModelSource).toContain('sourceLinkedCardBodyUri')
    expect(metadataPanelsModelSource).toContain("from '../../domain/detail/detail-metadata-editor-model'")
    expect(metadataPanelsModelSource).not.toContain('typedControls')
    expect(metadataPanelsModelSource).not.toContain('StructuredPredicateValueEditor')
    expect(metadataPanelsModelSource).not.toContain('useDetailMetaPredicateController')

    expect(metadataEditorModelSource).toContain('export function sourceLinkedCardBodyUri')
    expect(metadataEditorModelSource).toContain('export function latestDetailPendingProposal')
    expect(metadataEditorModelSource).toContain('export function shouldCreateDetailMetaPredicateProposal')
    expect(metadataEditorModelSource).toContain('export function createDetailMetaPredicateEditorState')
    expect(metadataEditorModelSource).toContain('export function projectDetailMetaPredicateEditorDraft')
    expect(metadataEditorModelSource).toContain('export function projectDetailMetaPredicateEditorHydration')
    expect(metadataEditorModelSource).toContain('export function projectDetailMetaPredicateEditorProposalStatus')
    expect(metadataEditorModelSource).toContain('export function projectDetailMetaPredicateProposalStatuses')
    expect(metadataEditorModelSource).toContain('export function resolveDetailMetaPredicateProposalStatus')
    expect(metadataEditorModelSource).toContain("from '../proposal/structured-cell-approval-model'")
    expect(metadataEditorModelSource).not.toContain('useState')
    expect(metadataEditorModelSource).not.toContain('useToast')
    expect(metadataEditorModelSource).not.toContain('<StructuredPredicateValueEditor')
    expect(metadataPanelsShimSource).toMatch(/^export \* from '..\/features\/detail\/FileDetailMetadataPanels'\n?$/)
    expect(rootMetadataEditorModelSource).toMatch(/^export \* from '.\/domain\/detail\/detail-metadata-editor-model'\n?$/)
  })
})
