import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const detailPanePath = 'src/modules/files/features/detail/FileDetailPane.tsx'
const detailPreviewPath = 'src/modules/files/features/detail/FileDetailPreview.tsx'
const sourceLinkedCardPreviewPath = 'src/modules/files/features/detail/FileDetailSourceLinkedCardPreview.tsx'
const editorSheetPath = 'src/modules/files/features/editor/FileEditorSheet.tsx'
const documentEditorModalPath = 'src/modules/files/features/editor/DocumentEditorModal.tsx'
const editorSheetControllerPath = 'src/modules/files/features/editor/useFileEditorSheetController.ts'
const editorSheetModelPath = 'src/modules/files/features/editor/file-editor-sheet-model.ts'
const editorMetaTailPath = 'src/modules/files/features/editor/FileEditorSheetMetaTail.tsx'
const editorRawSourcePath = 'src/modules/files/features/editor/FileEditorRawSourceEditor.tsx'
const editorRawSourceControllerPath = 'src/modules/files/features/editor/useFileEditorRawSourceController.ts'
const editorRawSourceModelPath = 'src/modules/files/features/editor/file-editor-raw-source-model.ts'
const folderDetailPath = 'src/modules/files/features/folder/FolderDetailPreview.tsx'

describe('FileEditorSheet architecture boundary', () => {
  it('keeps the editable file sheet out of the detail-pane container module', () => {
    const detailPaneSource = readFileSync(detailPanePath, 'utf8')

    expect(existsSync(detailPreviewPath)).toBe(true)
    expect(existsSync(editorSheetPath)).toBe(true)
    expect(existsSync(documentEditorModalPath)).toBe(true)
    expect(existsSync(editorSheetControllerPath)).toBe(true)
    expect(existsSync(editorSheetModelPath)).toBe(true)
    expect(existsSync(editorMetaTailPath)).toBe(true)
    expect(existsSync(editorRawSourcePath)).toBe(true)
    expect(existsSync(editorRawSourceControllerPath)).toBe(true)
    expect(existsSync(editorRawSourceModelPath)).toBe(true)
    expect(existsSync(folderDetailPath)).toBe(true)
    expect(existsSync(sourceLinkedCardPreviewPath)).toBe(true)
    if (
      !existsSync(detailPreviewPath)
      || !existsSync(editorSheetPath)
      || !existsSync(editorSheetControllerPath)
      || !existsSync(editorSheetModelPath)
      || !existsSync(editorMetaTailPath)
      || !existsSync(editorRawSourcePath)
      || !existsSync(editorRawSourceControllerPath)
      || !existsSync(editorRawSourceModelPath)
      || !existsSync(folderDetailPath)
      || !existsSync(sourceLinkedCardPreviewPath)
    ) return

    const detailPreviewSource = readFileSync(detailPreviewPath, 'utf8')
    const editorSheetSource = readFileSync(editorSheetPath, 'utf8')
    const documentEditorModalSource = readFileSync(documentEditorModalPath, 'utf8')
    const editorSheetControllerSource = readFileSync(editorSheetControllerPath, 'utf8')
    const editorSheetModelSource = readFileSync(editorSheetModelPath, 'utf8')
    const editorMetaTailSource = readFileSync(editorMetaTailPath, 'utf8')
    const editorRawSourceSource = readFileSync(editorRawSourcePath, 'utf8')
    const editorRawSourceControllerSource = readFileSync(editorRawSourceControllerPath, 'utf8')
    const editorRawSourceModelSource = readFileSync(editorRawSourceModelPath, 'utf8')
    const folderDetailSource = readFileSync(folderDetailPath, 'utf8')
    const sourceLinkedCardPreviewSource = readFileSync(sourceLinkedCardPreviewPath, 'utf8')

    expect(detailPaneSource).toContain("from './FileDetailPreview'")
    expect(detailPaneSource).not.toContain("from '../../components/FileDetailPreview'")
    expect(detailPaneSource).not.toContain("from './FileEditorSheet'")
    expect(detailPaneSource).not.toMatch(/\nfunction FileEditorSheet\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction RawSourceEditor\(/)

    expect(detailPreviewSource).toContain("from '../editor/DocumentEditorModal'")
    expect(editorSheetSource).toContain("DocumentEditorModal as FileEditorSheet")
    expect(documentEditorModalSource).toMatch(/\nexport function DocumentEditorModal\(/)
    expect(documentEditorModalSource).toContain("from './useFileEditorSheetController'")
    expect(documentEditorModalSource).toContain('useFileEditorSheetController')
    expect(documentEditorModalSource).toContain("from './FileEditorSheetMetaTail'")
    expect(documentEditorModalSource).toContain('<FileEditorSheetMetaTail')
    expect(documentEditorModalSource).toContain("from './FileEditorRawSourceEditor'")
    expect(documentEditorModalSource).toContain('<FileEditorRawSourceEditor')
    expect(documentEditorModalSource).toContain('editor.richContentState')
    expect(documentEditorModalSource).toContain('editor.rawSourceEditorState')
    expect(documentEditorModalSource).toContain('sourceState={editor.rawSourceEditorState}')
    expect(editorSheetSource).not.toContain('rawResource={editor.rawSourceEditorState.rawResource}')
    expect(editorSheetSource).not.toContain('isLoading={editor.rawSourceEditorState.isLoading}')
    expect(editorSheetSource).not.toContain('error={editor.rawSourceEditorState.error}')
    expect(editorSheetSource).not.toContain('editor.rawQuery')
    expect(editorSheetSource).not.toContain('editor.rawResource')
    expect(editorSheetSource).not.toContain('editor.effectiveSourceText')
    expect(editorSheetSource).not.toMatch(/\nfunction RawSourceEditor\(/)
    expect(editorSheetSource).not.toContain('../../folder-child-open')
    expect(editorSheetSource).not.toContain('../../list-open')
    expect(editorSheetSource).not.toContain('useFileDetail')
    expect(editorSheetSource).not.toContain('useCreateFolderResource')
    expect(editorSheetSource).not.toContain('renderMetaContent')
    expect(editorSheetSource).not.toContain('FileEditorSheetMetaContext')
    expect(editorSheetSource).not.toContain('type ReactNode')
    expect(editorSheetSource).not.toContain('useToast')
    expect(editorSheetSource).not.toContain('useSaveRawTextResource')
    expect(editorSheetSource).not.toContain('useCreateAiChangeProposal')
    expect(editorSheetSource).not.toContain('useCreateSourceUpdateProposal')
    expect(editorSheetSource).not.toContain('useFilesCurrentPodRootUri')
    expect(editorSheetSource).not.toContain('useRawTextResource')
    expect(editorSheetSource).not.toContain('useFilesMetaSidecar')
    expect(editorSheetSource).not.toContain('useFilesStore')
    expect(editorSheetSource).not.toContain('useFilesRouteBridge')
    expect(editorSheetSource).not.toContain('clearStructuredSubjectRoute')
    expect(editorSheetSource).not.toContain('createAiChangeProposal')
    expect(editorSheetSource).not.toContain('createSourceUpdateProposal')

    expect(editorSheetControllerSource).toContain('export function useFileEditorSheetController')
    expect(editorSheetControllerSource).toContain('useToast')
    expect(editorSheetControllerSource).toContain('useSaveRawTextResource')
    expect(editorSheetControllerSource).toContain('useCreateAiChangeProposal')
    expect(editorSheetControllerSource).toContain('useCreateSourceUpdateProposal')
    expect(editorSheetControllerSource).toContain('useFilesCurrentPodRootUri')
    expect(editorSheetControllerSource).toContain('useRawTextResource')
    expect(editorSheetControllerSource).toContain('useFilesMetaSidecar')
    expect(editorSheetControllerSource).toContain('useFilesStore')
    expect(editorSheetControllerSource).toContain('useFilesRouteBridge')
    expect(editorSheetControllerSource).toContain('clearStructuredSubjectRoute')
    expect(editorSheetControllerSource).toContain('createAiChangeProposal')
    expect(editorSheetControllerSource).toContain('createSourceUpdateProposal')
    expect(editorSheetControllerSource).toContain("from './file-editor-sheet-model'")
    expect(editorSheetControllerSource).toContain('createFileEditorSheetState')
    expect(editorSheetControllerSource).toContain('projectFileEditorSheetContentView')
    expect(editorSheetControllerSource).toContain('projectFileEditorSheetReset')
    expect(editorSheetControllerSource).toContain('projectFileEditorRichContentState')
    expect(editorSheetControllerSource).toContain('projectFileEditorRawSourceState')
    expect(editorSheetControllerSource).not.toMatch(/\nfunction resourceMetaTailId\(/)
    expect(editorSheetControllerSource).not.toMatch(/\nfunction getMarkdownNoteTitle\(/)
    expect(editorSheetControllerSource).not.toMatch(/\nfunction replaceMarkdownNoteTitle\(/)
    expect(editorSheetControllerSource).not.toContain("useState<FileEditorContentViewMode>(canUseRichEditor ? 'rich' : 'raw')")
    expect(editorSheetControllerSource).not.toContain("setContentView(canUseRichEditor ? 'rich' : 'raw')")
    expect(editorSheetControllerSource).not.toContain('displaySourceIngestVersion')
    expect(editorSheetControllerSource).not.toContain('DialogContent')
    expect(editorSheetControllerSource).not.toContain('RichTextFileEditor')
    expect(editorSheetControllerSource).not.toContain('FileEditorRawSourceEditor')
    expect(editorSheetControllerSource).not.toContain('FileEditorSheetMetaTail')
    expect(editorSheetModelSource).toContain('export function createFileEditorMetaTailId')
    expect(editorSheetModelSource).toContain('export function createFileEditorSheetState')
    expect(editorSheetModelSource).toContain('export function projectFileEditorSheetContentView')
    expect(editorSheetModelSource).toContain('export function projectFileEditorSheetReset')
    expect(editorSheetModelSource).toContain('export function getFileEditorMarkdownNoteTitle')
    expect(editorSheetModelSource).toContain('export function projectFileEditorSourceLinkedDraft')
    expect(editorSheetModelSource).toContain('export function projectFileEditorRawSourceResource')
    expect(editorSheetModelSource).toContain('export function projectFileEditorRichContentState')
    expect(editorSheetModelSource).toContain('export function projectFileEditorBylineItems')
    expect(editorSheetModelSource).toContain('export function projectFileEditorCapabilities')
    expect(editorSheetModelSource).not.toContain('useToast')
    expect(editorSheetModelSource).not.toContain('useState')
    expect(editorSheetModelSource).not.toContain('useMemo')

    expect(editorMetaTailSource).toContain('export function FileEditorSheetMetaTail')
    expect(editorMetaTailSource).toContain('FileRdfMetadataPanel')
    expect(editorMetaTailSource).toContain('SourceLinkedCardMetadataPanel')
    expect(editorMetaTailSource).not.toContain('renderMetaContent')
    expect(editorMetaTailSource).not.toContain('children')

    expect(editorRawSourceSource).toContain('export function FileEditorRawSourceEditor')
    expect(editorRawSourceSource).toContain("from './useFileEditorRawSourceController'")
    expect(editorRawSourceSource).toContain('useFileEditorRawSourceController')
    expect(editorRawSourceSource).toContain('sourceState')
    expect(editorRawSourceSource).toContain("sourceState.kind === 'loading'")
    expect(editorRawSourceSource).not.toContain('if (isLoading)')
    expect(editorRawSourceSource).not.toContain('error || !rawResource')
    expect(editorRawSourceSource).not.toContain('useSaveRawTextResource')
    expect(editorRawSourceSource).not.toContain('useToast')
    expect(editorRawSourceSource).not.toContain('FilesSaveConflictError')
    expect(editorRawSourceSource).not.toContain('FileEditorSheetMetaTail')
    expect(editorRawSourceControllerSource).toContain('export function useFileEditorRawSourceController')
    expect(editorRawSourceControllerSource).toContain('useSaveRawTextResource')
    expect(editorRawSourceControllerSource).toContain('useToast')
    expect(editorRawSourceControllerSource).toContain("from './file-editor-raw-source-model'")
    expect(editorRawSourceControllerSource).toContain('createFileEditorRawSourceDraftState')
    expect(editorRawSourceControllerSource).toContain('planFileEditorRawSourceSave')
    expect(editorRawSourceControllerSource).toContain('projectFileEditorRawSourceDraftPatch')
    expect(editorRawSourceControllerSource).toContain('projectFileEditorRawSourceHydration')
    expect(editorRawSourceControllerSource).not.toContain('FilesSaveConflictError')
    expect(editorRawSourceControllerSource).not.toContain('draft !== rawResource.content')
    expect(editorRawSourceControllerSource).not.toContain("useState('')")
    expect(editorRawSourceControllerSource).not.toContain('setDraft(projectFileEditorRawSourceDraft(rawResource))')
    expect(editorRawSourceControllerSource).not.toContain('error instanceof FilesSaveConflictError')
    expect(editorRawSourceControllerSource).not.toContain('Textarea')
    expect(editorRawSourceControllerSource).not.toContain('Button')
    expect(editorRawSourceModelSource).toContain('export function projectFileEditorRawSourceDraft')
    expect(editorRawSourceModelSource).toContain('export function createFileEditorRawSourceDraftState')
    expect(editorRawSourceModelSource).toContain('export function projectFileEditorRawSourceDraftPatch')
    expect(editorRawSourceModelSource).toContain('export function projectFileEditorRawSourceHydration')
    expect(editorRawSourceModelSource).toContain('export function isFileEditorRawSourceDirty')
    expect(editorRawSourceModelSource).toContain('export function planFileEditorRawSourceSave')
    expect(editorRawSourceModelSource).toContain('export function projectFileEditorRawSourceState')
    expect(editorRawSourceModelSource).toContain('export function getFileEditorRawSourceResource')
    expect(editorRawSourceModelSource).toContain('export function getFileEditorRawSourceSaveErrorMessage')
    expect(editorRawSourceModelSource).toContain('export function canSubmitFileEditorRawSourceProposal')
    expect(editorRawSourceModelSource).not.toContain('useToast')
    expect(editorRawSourceModelSource).not.toContain('useState')
    expect(editorRawSourceModelSource).not.toContain('useSaveRawTextResource')

    expect(detailPreviewSource).not.toContain('renderMetaContent')
    expect(detailPreviewSource).not.toContain('renderChildMetaContent')
    expect(folderDetailSource).not.toContain('renderChildMetaContent')
    expect(folderDetailSource).not.toContain('FileEditorSheetMetaContext')
    expect(sourceLinkedCardPreviewSource).not.toContain('renderMetaContent')
  })
})
