import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const detailPanePath = 'src/modules/files/features/detail/FileDetailPane.tsx'
const detailPreviewPath = 'src/modules/files/features/detail/FileDetailPreview.tsx'
const folderDetailPath = 'src/modules/files/features/folder/FolderDetailPreview.tsx'
const folderChildPreviewPath = 'src/modules/files/features/folder/FolderChildPreview.tsx'
const folderChildPreviewControllerPath = 'src/modules/files/features/folder/useFolderChildPreviewController.ts'
const folderChildPreviewModelPath = 'src/modules/files/domain/folder/folder-child-preview-model.ts'
const folderColumnViewPath = 'src/modules/files/features/folder/FolderDetailColumnView.tsx'
const folderColumnPanelControllerPath = 'src/modules/files/features/folder/useFolderColumnPanelController.ts'
const folderChildViewsPath = 'src/modules/files/features/folder/FolderDetailChildViews.tsx'
const folderViewControllerPath = 'src/modules/files/features/folder/useFolderDetailViewController.ts'
const folderColumnControllerPath = 'src/modules/files/features/folder/useFolderDetailColumnController.ts'
const folderDescendantColumnControllerPath = 'src/modules/files/features/folder/useFolderDescendantColumnController.ts'
const folderNavigationControllerPath = 'src/modules/files/features/folder/useFolderDetailNavigationController.ts'
const folderSelectionControllerPath = 'src/modules/files/features/folder/useFolderDetailSelectionController.ts'
const folderUploadControllerPath = 'src/modules/files/features/folder/useFolderDetailUploadController.ts'
const folderOperationControllerPath = 'src/modules/files/features/folder/useFolderDetailOperationController.ts'
const folderModelPath = 'src/modules/files/domain/folder/folder-detail-model.ts'
const folderColumnViewShimPath = 'src/modules/files/components/FolderDetailColumnView.tsx'
const folderChildViewsShimPath = 'src/modules/files/components/FolderDetailChildViews.tsx'

describe('FolderDetailPreview architecture boundary', () => {
  it('keeps Finder-style folder detail logic out of the file detail pane shell', () => {
    const detailPaneSource = readFileSync(detailPanePath, 'utf8')

    expect(existsSync(detailPreviewPath)).toBe(true)
    expect(existsSync(folderDetailPath)).toBe(true)
    expect(existsSync(folderChildPreviewPath)).toBe(true)
    expect(existsSync(folderChildPreviewControllerPath)).toBe(true)
    expect(existsSync(folderChildPreviewModelPath)).toBe(true)
    expect(existsSync(folderColumnViewPath)).toBe(true)
    expect(existsSync(folderColumnPanelControllerPath)).toBe(true)
    expect(existsSync(folderChildViewsPath)).toBe(true)
    expect(existsSync(folderViewControllerPath)).toBe(true)
    expect(existsSync(folderColumnControllerPath)).toBe(true)
    expect(existsSync(folderDescendantColumnControllerPath)).toBe(true)
    expect(existsSync(folderNavigationControllerPath)).toBe(true)
    expect(existsSync(folderSelectionControllerPath)).toBe(true)
    expect(existsSync(folderUploadControllerPath)).toBe(true)
    expect(existsSync(folderOperationControllerPath)).toBe(true)
    expect(existsSync(folderModelPath)).toBe(true)
    expect(existsSync(folderColumnViewShimPath)).toBe(true)
    expect(existsSync(folderChildViewsShimPath)).toBe(true)
    if (
      !existsSync(detailPreviewPath)
      || !existsSync(folderDetailPath)
      || !existsSync(folderChildPreviewPath)
      || !existsSync(folderChildPreviewControllerPath)
      || !existsSync(folderChildPreviewModelPath)
      || !existsSync(folderColumnViewPath)
      || !existsSync(folderColumnPanelControllerPath)
      || !existsSync(folderChildViewsPath)
      || !existsSync(folderViewControllerPath)
      || !existsSync(folderColumnControllerPath)
      || !existsSync(folderDescendantColumnControllerPath)
      || !existsSync(folderNavigationControllerPath)
      || !existsSync(folderSelectionControllerPath)
      || !existsSync(folderUploadControllerPath)
      || !existsSync(folderOperationControllerPath)
      || !existsSync(folderModelPath)
      || !existsSync(folderColumnViewShimPath)
      || !existsSync(folderChildViewsShimPath)
    ) return

    const detailPreviewSource = readFileSync(detailPreviewPath, 'utf8')
    const folderDetailSource = readFileSync(folderDetailPath, 'utf8')
    const folderChildPreviewSource = readFileSync(folderChildPreviewPath, 'utf8')
    const folderChildPreviewControllerSource = readFileSync(folderChildPreviewControllerPath, 'utf8')
    const folderChildPreviewModelSource = readFileSync(folderChildPreviewModelPath, 'utf8')
    const folderColumnViewSource = readFileSync(folderColumnViewPath, 'utf8')
    const folderColumnPanelControllerSource = readFileSync(folderColumnPanelControllerPath, 'utf8')
    const folderChildViewsSource = readFileSync(folderChildViewsPath, 'utf8')
    const folderViewControllerSource = readFileSync(folderViewControllerPath, 'utf8')
    const folderColumnControllerSource = readFileSync(folderColumnControllerPath, 'utf8')
    const folderDescendantColumnControllerSource = readFileSync(folderDescendantColumnControllerPath, 'utf8')
    const folderNavigationControllerSource = readFileSync(folderNavigationControllerPath, 'utf8')
    const folderSelectionControllerSource = readFileSync(folderSelectionControllerPath, 'utf8')
    const folderUploadControllerSource = readFileSync(folderUploadControllerPath, 'utf8')
    const folderOperationControllerSource = readFileSync(folderOperationControllerPath, 'utf8')
    const folderModelSource = readFileSync(folderModelPath, 'utf8')
    const folderColumnViewShimSource = readFileSync(folderColumnViewShimPath, 'utf8')
    const folderChildViewsShimSource = readFileSync(folderChildViewsShimPath, 'utf8')

    expect(detailPaneSource).toContain("from './FileDetailPreview'")
    expect(detailPaneSource).not.toContain("from '../../components/FileDetailPreview'")
    expect(detailPaneSource).not.toContain("from './FolderDetailPreview'")
    expect(detailPaneSource).not.toMatch(/\nfunction FolderDetailPreview\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction FolderColumnPanel\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction FolderDescendantColumn\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction FolderChildPreview\(/)
    expect(detailPaneSource).not.toMatch(/\nfunction getFolderChildPreviewSummary\(/)

    expect(detailPreviewSource).toContain("from '../folder/FolderDetailPreview'")
    expect(folderDetailSource).toMatch(/\nexport function FolderDetailPreview\(/)
    expect(folderDetailSource).toContain("from './FolderDetailColumnView'")
    expect(folderDetailSource).toContain("from './FolderDetailChildViews'")
    expect(folderDetailSource).not.toContain("from '../../components/FolderDetailColumnView'")
    expect(folderDetailSource).not.toContain("from '../../components/FolderDetailChildViews'")
    expect(folderDetailSource).not.toMatch(/\nfunction FolderColumnPanel\(/)
    expect(folderDetailSource).not.toMatch(/\nfunction FolderDescendantColumn\(/)
    expect(folderDetailSource).not.toMatch(/\n\s*const childButtonClassName = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const renderChildButton = /)
    expect(folderDetailSource).toContain("from './FolderChildPreview'")
    expect(folderDetailSource).not.toMatch(/\nfunction FolderChildPreview\(/)
    expect(folderDetailSource).not.toMatch(/\nfunction getFolderChildPreviewSummary\(/)
    expect(folderDetailSource).not.toContain('ResourceMetaDrawer')
    expect(folderDetailSource).not.toContain('ResourceSidecarActions')
    expect(folderDetailSource).not.toContain('getFolderChildPreviewRows')
    expect(folderDetailSource).not.toContain('resolveFilesSidecarOwnerTarget')
    expect(folderDetailSource).not.toContain('getFilesEntrySemanticLabel')
    expect(folderDetailSource).not.toContain('getFilesEntryOpenMode')
    expect(folderDetailSource).not.toContain('setMetaDrawerOpen')
    expect(folderDetailSource).toContain("from '../editor/FileEditorSheet'")
    expect(folderDetailSource).not.toContain("from '../../components/FileEditorSheet'")
    expect(folderDetailSource).toContain("from './FolderChildOperationSheet'")
    expect(folderDetailSource).toContain("from './useFolderDetailViewController'")
    expect(folderDetailSource).toContain("from './useFolderDetailColumnController'")
    expect(folderDetailSource).toContain("from './useFolderDetailNavigationController'")
    expect(folderDetailSource).toContain("from './useFolderDetailSelectionController'")
    expect(folderDetailSource).toContain("from './useFolderDetailUploadController'")
    expect(folderDetailSource).toContain("from './useFolderDetailOperationController'")
    expect(folderDetailSource).not.toContain('useFilesStore')
    expect(folderDetailSource).not.toContain('getVisibleFolderChildren')
    expect(folderDetailSource).not.toContain('sortFolderEntries')
    expect(folderDetailSource).not.toContain('FOLDER_VIEW_MODE_OPTIONS')
    expect(folderDetailSource).not.toContain('列表视图')
    expect(folderDetailSource).not.toContain('分栏视图')
    expect(folderDetailSource).not.toContain('图标视图')
    expect(folderDetailSource).not.toContain('新建文件夹')
    expect(folderDetailSource).not.toContain('新建 Markdown 文件')
    expect(folderDetailSource).not.toContain('选择上传文件')
    expect(folderDetailSource).not.toContain('上传文件')
    expect(folderDetailSource).toContain('viewModeOptions.map')
    expect(folderDetailSource).toContain('option.active')
    expect(folderDetailSource).toContain('toolbarChrome.createFolderLabel')
    expect(folderDetailSource).toContain('toolbarChrome.createMarkdownLabel')
    expect(folderDetailSource).toContain('toolbarChrome.uploadInputLabel')
    expect(folderDetailSource).toContain('toolbarChrome.uploadLabel')
    expect(folderDetailSource).toContain('contentState')
    expect(folderDetailSource).toContain('contentState.emptyState.message')
    expect(folderDetailSource).not.toContain('当前容器没有可浏览子项。')
    expect(folderDetailSource).not.toContain('hasVisibleChildren')
    expect(folderDetailSource).not.toContain('hasVisibleChildren ?')
    expect(folderDetailSource).not.toContain("viewMode === 'columns'")
    expect(folderDetailSource).not.toContain('visibleChildren.length')
    expect(folderDetailSource).not.toContain('selectedChildren.length')
    expect(folderDetailSource).not.toContain('columnPreviewSiblings.length')
    expect(folderDetailSource).toContain('visibleChildCount')
    expect(folderDetailSource).not.toContain('selectedChildCount')
    expect(folderDetailSource).not.toContain('已选择')
    expect(folderDetailSource).not.toContain('复制所选 URI')
    expect(folderDetailSource).not.toContain('删除所选项')
    expect(folderDetailSource).toContain('folderSelection.batchSelectionLabel')
    expect(folderDetailSource).toContain('folderSelection.batchSelectionActions.copyLabel')
    expect(folderDetailSource).toContain('folderSelection.batchSelectionActions.deleteLabel')
    expect(folderDetailSource).toContain('columnPreviewChildCount')
    expect(folderDetailSource).not.toMatch(/\n\s*const visibleChildren = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const sortedChildren = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const \[viewMode, setViewMode\] = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const \[sort, setSort\] = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const setSortKey = /)
    expect(folderDetailSource).not.toContain('copyFilesText')
    expect(folderDetailSource).not.toContain('resolveFolderChildOpenDecision')
    expect(folderDetailSource).not.toContain('setSheetChild')
    expect(folderDetailSource).not.toMatch(/\n\s*const sheetChild = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const openChild = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const copyChildUri = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const copySelectedChildUris = /)
    expect(folderDetailSource).not.toContain('contextMenuSelectionTimerRef')
    expect(folderDetailSource).not.toContain('selectionAnchorUri')
    expect(folderDetailSource).not.toContain('setSelectedChildUri')
    expect(folderDetailSource).not.toContain('setSelectedChildUris')
    expect(folderDetailSource).not.toContain('setSelectionAnchorUri')
    expect(folderDetailSource).not.toContain('event?.shiftKey')
    expect(folderDetailSource).not.toContain('event?.metaKey')
    expect(folderDetailSource).not.toContain('event?.ctrlKey')
    expect(folderDetailSource).not.toContain('setColumnContainerPath')
    expect(folderDetailSource).not.toContain('setColumnSelectionByContainer')
    expect(folderDetailSource).not.toContain('setColumnPreviewTarget')
    expect(folderDetailSource).not.toMatch(/\n\s*const columnContainerPath = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const columnSelectionByContainer = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const columnPreviewTarget = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const selectColumnChild = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const prepareColumnChildContextMenuSelection = /)
    expect(folderDetailSource).not.toContain('useCreateBlobResource')
    expect(folderDetailSource).not.toContain('useCreateFolderResource')
    expect(folderDetailSource).not.toContain('useCreateRawTextResource')
    expect(folderDetailSource).not.toContain('useCopyFileResource')
    expect(folderDetailSource).not.toContain('useMoveFileResource')
    expect(folderDetailSource).not.toContain('useDeleteFileResource')
    expect(folderDetailSource).not.toContain('getFolderChildOperationValidationMessage')
    expect(folderDetailSource).not.toContain('normalizeMarkdownFileName')
    expect(folderDetailSource).not.toContain('buildFolderChildCopyName')
    expect(folderDetailSource).not.toContain('resolveFolderChildTransferDestination')
    expect(folderDetailSource).not.toContain('Untitled folder')
    expect(folderDetailSource).not.toContain('Untitled.md')
    expect(folderDetailSource).not.toMatch(/\n\s*const openFolderOperation = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const openTransferOperation = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const closeFolderOperation = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const deleteChildren = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const confirmFolderOperation = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const isTextUpload = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const uploadFiles = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const uploadPickedFiles = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const handleUploadDragOver = /)
    expect(folderDetailSource).not.toMatch(/\n\s*const handleUploadDrop = /)
    expect(folderDetailSource).not.toContain('uploadedFile.text()')
    expect(folderDetailSource).not.toContain("event.dataTransfer.types.includes('Files')")

    expect(folderColumnViewSource).toMatch(/\nexport function FolderColumnPanel\(/)
    expect(folderColumnViewSource).toMatch(/\nexport function FolderDescendantColumn\(/)
    expect(folderColumnViewSource).toContain("from './useFolderColumnPanelController'")
    expect(folderColumnViewSource).toContain('useFolderColumnPanelController')
    expect(folderColumnViewSource).toContain('hasSortedRows')
    expect(folderColumnViewSource).toContain('entryCount')
    expect(folderColumnViewSource).not.toContain('sortedRows.length')
    expect(folderColumnViewSource).not.toContain('entries.length')
    expect(folderColumnViewSource).toContain("from './useFolderDescendantColumnController'")
    expect(folderColumnViewSource).toContain('useFolderDescendantColumnController')
    expect(folderColumnViewSource).toContain('descendantColumn.contentState')
    expect(folderColumnViewSource).toContain('descendantColumn.chrome.ariaLabel')
    expect(folderColumnViewSource).toContain('descendantColumn.chrome.loadingMessage')
    expect(folderColumnViewSource).toContain('descendantColumn.chrome.unavailableMessage')
    expect(folderColumnViewSource).not.toContain('descendantColumn.isLoading')
    expect(folderColumnViewSource).not.toContain('descendantColumn.error')
    expect(folderColumnViewSource).not.toContain('!descendantColumn.parentFile')
    expect(folderColumnViewSource).not.toContain('正在加载...')
    expect(folderColumnViewSource).not.toContain('无法读取子文件夹。')
    expect(folderColumnViewSource).not.toContain("child.kind === 'container'")
    expect(folderColumnViewSource).not.toContain('useFileDetail')
    expect(folderColumnViewSource).not.toContain('getVisibleFolderChildren')
    expect(folderColumnViewSource).not.toContain('sortFolderEntries')
    expect(folderColumnViewSource).not.toContain("from './FileEditorSheet'")
    expect(folderColumnViewSource).not.toContain("from './FolderChildOperationSheet'")
    expect(folderColumnPanelControllerSource).toContain('export function useFolderColumnPanelController')
    expect(folderColumnPanelControllerSource).toContain('projectFolderColumnPanelModel')
    expect(folderColumnPanelControllerSource).not.toContain('sortFolderEntries')
    expect(folderColumnPanelControllerSource).not.toContain('projectFolderColumnRow')
    expect(folderColumnPanelControllerSource).not.toContain('hasSortedRows')
    expect(folderColumnPanelControllerSource).not.toContain('entryCount')
    expect(folderColumnPanelControllerSource).not.toContain('ContextMenu')
    expect(folderColumnPanelControllerSource).not.toMatch(/\nfunction FolderColumnPanel\b/)
    expect(folderColumnPanelControllerSource).not.toContain('<FolderColumnPanel')

    expect(folderChildViewsSource).toMatch(/\nexport function FolderChildCollectionView\(/)
    expect(folderChildViewsSource).toContain('collectionChrome.ariaLabel')
    expect(folderChildViewsSource).toContain('collectionChrome.sortHeaders.map')
    expect(folderChildViewsSource).not.toContain('Folder list view')
    expect(folderChildViewsSource).not.toContain('Folder icon view')
    expect(folderChildViewsSource).not.toContain('按${label}排序')
    expect(folderChildViewsSource).not.toContain('label="名称"')
    expect(folderChildViewsSource).not.toContain('label="类型"')
    expect(folderChildViewsSource).not.toContain('label="修改"')
    expect(folderChildViewsSource).not.toContain('label="大小"')
    expect(folderChildViewsSource).not.toContain('projectFolderChildCollectionRow')
    expect(folderChildViewsSource).not.toContain("child.kind === 'container'")
    expect(folderChildViewsSource).not.toContain('getFilesEntrySemanticLabel')
    expect(folderChildViewsSource).not.toContain('formatBytes')
    expect(folderChildViewsSource).toContain('projectFolderChildKeyboardNavigationPlan')
    expect(folderChildViewsSource).not.toContain('const currentIndex = rows.findIndex')
    expect(folderChildViewsSource).not.toContain("event.key === 'Home'")
    expect(folderChildViewsSource).not.toContain("event.key === 'ArrowUp'")
    expect(folderChildViewsSource).not.toMatch(/\n\s*const nextIndex = /)
    expect(folderChildViewsSource).not.toContain('formatDateTime')
    expect(folderChildViewsSource).not.toContain("from './FileEditorSheet'")
    expect(folderChildViewsSource).not.toContain("from './FolderChildOperationSheet'")
    expect(folderChildPreviewSource).toContain('export function FolderChildPreview')
    expect(folderChildPreviewSource).toContain("from './useFolderChildPreviewController'")
    expect(folderChildPreviewSource).toContain('ResourceMetaDrawer')
    expect(folderChildPreviewSource).toContain('ResourceSidecarActions')
    expect(folderChildPreviewSource).toContain('preview.chrome.ariaLabel')
    expect(folderChildPreviewSource).toContain('preview.chrome.openSelectedLabel')
    expect(folderChildPreviewSource).not.toContain('Folder child preview')
    expect(folderChildPreviewSource).not.toContain('打开选中项')
    expect(folderChildPreviewSource).not.toContain('getFolderChildPreviewRows')
    expect(folderChildPreviewSource).not.toContain('resolveFilesSidecarOwnerTarget')
    expect(folderChildPreviewControllerSource).toContain('export function useFolderChildPreviewController')
    expect(folderChildPreviewControllerSource).toContain("from '../../domain/folder/folder-child-preview-model'")
    expect(folderChildPreviewControllerSource).toContain('projectFolderChildPreviewModel')
    expect(folderChildPreviewControllerSource).not.toContain('getFolderChildPreviewRows')
    expect(folderChildPreviewControllerSource).not.toContain('resolveFilesSidecarOwnerTarget')
    expect(folderChildPreviewControllerSource).not.toContain('getFilesEntrySemanticLabel')
    expect(folderChildPreviewControllerSource).not.toContain('getFilesEntryOpenMode')
    expect(folderChildPreviewControllerSource).not.toContain('formatBytes')
    expect(folderChildPreviewControllerSource).not.toContain('formatDateTime')
    expect(folderChildPreviewControllerSource).not.toMatch(/\nfunction getFolderChildPreviewSummary\(/)
    expect(folderChildPreviewControllerSource).not.toContain("heading: child ? '选中项' : '文件夹预览'")
    expect(folderChildPreviewControllerSource).not.toContain('ResourceMetaDrawer')
    expect(folderChildPreviewControllerSource).not.toContain('ResourceSidecarActions')
    expect(folderChildPreviewControllerSource).not.toContain('<')
    expect(folderChildPreviewModelSource).toContain('chrome: FOLDER_CHILD_PREVIEW_CHROME')
    expect(folderChildPreviewModelSource).toContain('Folder child preview')
    expect(folderChildPreviewModelSource).toContain('打开选中项')
    expect(folderViewControllerSource).toContain('export function useFolderDetailViewController')
    expect(folderViewControllerSource).toContain('projectFolderDetailViewModel')
    expect(folderViewControllerSource).toContain('createFolderDetailViewState')
    expect(folderViewControllerSource).toContain('projectFolderDetailSortKey')
    expect(folderViewControllerSource).toContain('projectFolderDetailViewMode')
    expect(folderViewControllerSource).toContain('viewMode')
    expect(folderViewControllerSource).toContain('viewModel')
    expect(folderViewControllerSource).toContain('setSortKey')
    expect(folderViewControllerSource).toMatch(/\n\s*const \[viewState, setViewState\] = useState\(createFolderDetailViewState\)/)
    expect(folderViewControllerSource).not.toMatch(/\n\s*const \[viewMode, setViewMode\] = useState/)
    expect(folderViewControllerSource).not.toMatch(/\n\s*const \[sort, setSort\] = useState/)
    expect(folderViewControllerSource).not.toContain('getVisibleFolderChildren')
    expect(folderViewControllerSource).not.toContain('sortFolderEntries')
    expect(folderViewControllerSource).not.toContain('projectFolderChildCollectionRow')
    expect(folderViewControllerSource).not.toContain('projectFolderDetailContentState')
    expect(folderViewControllerSource).not.toContain('FOLDER_DETAIL_VIEW_MODE_OPTIONS')
    expect(folderViewControllerSource).not.toContain('FOLDER_DETAIL_TOOLBAR_CHROME')
    expect(folderViewControllerSource).not.toContain('sortedChildren.map')
    expect(folderViewControllerSource).not.toContain('visibleChildren.length')
    expect(folderViewControllerSource).not.toContain('option.mode === viewMode')
    expect(folderViewControllerSource).not.toContain('FolderChildCollectionView')
    expect(folderViewControllerSource).not.toContain('FolderColumnPanel')
    expect(folderViewControllerSource).not.toContain('FileEditorSheet')
    expect(folderViewControllerSource).not.toContain('FolderChildOperationSheet')
    expect(folderViewControllerSource).not.toContain('ResourceMetaDrawer')
    expect(folderColumnControllerSource).toContain('export function useFolderDetailColumnController')
    expect(folderColumnControllerSource).toContain('columnContainerPath')
    expect(folderColumnControllerSource).toContain('columnSelectionByContainer')
    expect(folderColumnControllerSource).toContain('columnPreviewTarget')
    expect(folderColumnControllerSource).toContain('columnPreviewChildCount')
    expect(folderColumnControllerSource).toContain('createFolderColumnState')
    expect(folderColumnControllerSource).toContain('projectFolderColumnStateAfterSelection')
    expect(folderColumnControllerSource).toContain('projectFolderColumnStateAfterPrune')
    expect(folderColumnControllerSource).toContain('projectFolderDetailColumnModel')
    expect(folderColumnControllerSource).not.toContain('setColumnContainerPath')
    expect(folderColumnControllerSource).not.toContain('setColumnSelectionByContainer')
    expect(folderColumnControllerSource).not.toContain('setColumnPreviewTarget')
    expect(folderColumnControllerSource).not.toMatch(/useState<string\[\]>\(\[\]\)/)
    expect(folderColumnControllerSource).not.toMatch(/useState<Record<string, string>>\(\{\}\)/)
    expect(folderColumnControllerSource).not.toContain('Object.fromEntries')
    expect(folderColumnControllerSource).not.toMatch(/columnContainerPath\.slice/)
    expect(folderColumnControllerSource).not.toContain('columnPreviewTarget?.siblingEntries ?? visibleChildren')
    expect(folderColumnControllerSource).not.toContain('columnSelectionByContainer[file.uri] ?? selectedChildUri')
    expect(folderColumnControllerSource).toContain('selectColumnChild')
    expect(folderColumnControllerSource).toContain('prepareColumnChildContextMenuSelection')
    expect(folderColumnControllerSource).not.toContain('useCopyFileResource')
    expect(folderColumnControllerSource).not.toContain('useDeleteFileResource')
    expect(folderColumnControllerSource).not.toContain('FolderChildOperationSheet')
    expect(folderColumnControllerSource).not.toContain('FileEditorSheet')
    expect(folderDescendantColumnControllerSource).toContain('export function useFolderDescendantColumnController')
    expect(folderDescendantColumnControllerSource).toContain('useFileDetail')
    expect(folderDescendantColumnControllerSource).toContain('projectFolderDescendantColumnModel')
    expect(folderDescendantColumnControllerSource).not.toContain('getVisibleFolderChildren')
    expect(folderDescendantColumnControllerSource).not.toContain('projectFolderDescendantColumnState')
    expect(folderDescendantColumnControllerSource).not.toContain('folderColumnNameFromUri')
    expect(folderDescendantColumnControllerSource).not.toContain('Folder column ${title}')
    expect(folderDescendantColumnControllerSource).not.toContain('FolderColumnPanel')
    expect(folderDescendantColumnControllerSource).not.toContain('ContextMenu')
    expect(folderNavigationControllerSource).toContain('export function useFolderDetailNavigationController')
    expect(folderNavigationControllerSource).toContain('useFilesStore')
    expect(folderNavigationControllerSource).toContain('copyFilesText')
    expect(folderNavigationControllerSource).toContain("from './folder-navigation-workflow-model'")
    expect(folderNavigationControllerSource).toContain('planFolderChildOpenEffect')
    expect(folderNavigationControllerSource).toContain('projectFolderChildCopyText')
    expect(folderNavigationControllerSource).toContain('projectSelectedFolderChildCopyText')
    expect(folderNavigationControllerSource).toContain('shouldClearFolderChildSheet')
    expect(folderNavigationControllerSource).not.toContain("from '../../domain/folder/folder-child-open'")
    expect(folderNavigationControllerSource).not.toContain('resolveFolderChildOpenDecision')
    expect(folderNavigationControllerSource).not.toContain('selectedChildren.map')
    expect(folderNavigationControllerSource).not.toContain('!childUriSet.has(sheetChild.uri)')
    expect(folderNavigationControllerSource).toContain('sheetChild')
    expect(folderNavigationControllerSource).not.toContain('FolderChildOperationSheet')
    expect(folderNavigationControllerSource).not.toContain('FolderChildCollectionView')
    expect(folderNavigationControllerSource).not.toContain('FolderColumnPanel')
    expect(folderNavigationControllerSource).not.toContain('FileEditorSheet')
    expect(folderModelSource).toContain('export type FolderChildCollectionChrome')
    expect(folderModelSource).toContain('export function projectFolderChildCollectionChrome')
    expect(folderModelSource).toContain('export function projectFolderDescendantColumnModel')
    expect(folderModelSource).toContain('Folder list view')
    expect(folderModelSource).toContain('Folder icon view')
    expect(folderModelSource).toContain('按名称排序')
    expect(folderModelSource).toContain('无法读取子文件夹。')
    expect(folderSelectionControllerSource).toContain('export function useFolderDetailSelectionController')
    expect(folderSelectionControllerSource).toContain("from '../../domain/folder/folder-detail-model'")
    expect(folderSelectionControllerSource).toContain('createFolderChildSelectionState')
    expect(folderSelectionControllerSource).toContain('projectFolderChildContextMenuSelectionState')
    expect(folderSelectionControllerSource).toContain('projectFolderChildSelectionProjection')
    expect(folderSelectionControllerSource).toContain('projectFolderChildSelectionState')
    expect(folderSelectionControllerSource).toContain('projectFolderChildSelectionStateFromPlan')
    expect(folderSelectionControllerSource).toContain('projectFolderChildSelectedChildUriPatch')
    expect(folderSelectionControllerSource).toContain('pruneFolderChildSelectionState')
    expect(folderSelectionControllerSource).toContain('removeFolderChildSelectionUris')
    expect(folderSelectionControllerSource).toContain('contextMenuSelectionTimerRef')
    expect(folderSelectionControllerSource).toContain('selectionAnchorUri')
    expect(folderSelectionControllerSource).toContain('selectedChildCount')
    expect(folderSelectionControllerSource).toContain('batchSelectionLabel')
    expect(folderSelectionControllerSource).toContain('batchSelectionActions')
    expect(folderSelectionControllerSource).not.toContain('visibleChildren.map')
    expect(folderSelectionControllerSource).not.toContain('visibleChildren.find')
    expect(folderSelectionControllerSource).not.toContain('sortedChildren.filter')
    expect(folderSelectionControllerSource).not.toContain('sortedChildren.slice')
    expect(folderSelectionControllerSource).not.toContain('new Set([child.uri])')
    expect(folderSelectionControllerSource).not.toContain('toggleFolderChildSelectionUri')
    expect(folderSelectionControllerSource).not.toContain('projectFolderChildRangeSelectionUris')
    expect(folderSelectionControllerSource).not.toMatch(/\n\s*const \[selectedChildUri, setSelectedChildUri\]/)
    expect(folderSelectionControllerSource).not.toMatch(/\n\s*const \[selectedChildUris, setSelectedChildUris\]/)
    expect(folderSelectionControllerSource).not.toMatch(/\n\s*const \[selectionAnchorUri, setSelectionAnchorUri\]/)
    expect(folderSelectionControllerSource).not.toContain('setSelectedChildUri(')
    expect(folderSelectionControllerSource).not.toContain('setSelectedChildUris(')
    expect(folderSelectionControllerSource).not.toContain('setSelectionAnchorUri(')
    expect(folderSelectionControllerSource).not.toContain('selectedChildren.length')
    expect(folderSelectionControllerSource).not.toContain('useCopyFileResource')
    expect(folderSelectionControllerSource).not.toContain('useDeleteFileResource')
    expect(folderSelectionControllerSource).not.toContain('useToast')
    expect(folderSelectionControllerSource).not.toContain('FileEditorSheet')
    expect(folderUploadControllerSource).toContain('export function useFolderDetailUploadController')
    expect(folderUploadControllerSource).toContain("from '../../domain/folder/folder-upload-model'")
    expect(folderUploadControllerSource).toContain('projectFolderUploadResourcePlan')
    expect(folderUploadControllerSource).toContain('useCreateBlobResource')
    expect(folderUploadControllerSource).toContain('useCreateRawTextResource')
    expect(folderUploadControllerSource).toContain('uploadedFile.text()')
    expect(folderUploadControllerSource).toContain("event.dataTransfer.types.includes('Files')")
    expect(folderUploadControllerSource).not.toMatch(/\nfunction isTextUpload\(/)
    expect(folderUploadControllerSource).not.toContain("uploadedFile.name.split(/[\\\\/]/)")
    expect(folderUploadControllerSource).not.toContain("fileName.toLowerCase().endsWith('.md')")
    expect(folderUploadControllerSource).not.toContain("uploadedFile.type")
    expect(folderUploadControllerSource).not.toContain('FolderChildOperationSheet')
    expect(folderUploadControllerSource).not.toContain('FileEditorSheet')
    expect(folderOperationControllerSource).toContain('export function useFolderDetailOperationController')
    expect(folderOperationControllerSource).toContain('useCreateFolderResource')
    expect(folderOperationControllerSource).toContain('useCreateRawTextResource')
    expect(folderOperationControllerSource).toContain('useCopyFileResource')
    expect(folderOperationControllerSource).toContain('useMoveFileResource')
    expect(folderOperationControllerSource).toContain('useDeleteFileResource')
    expect(folderOperationControllerSource).toContain('getFolderChildOperationValidationMessage')
    expect(folderOperationControllerSource).toContain('createFolderChildOperationState')
    expect(folderOperationControllerSource).toContain('projectFolderChildOperationOpened')
    expect(folderOperationControllerSource).toContain('projectFolderChildOperationReset')
    expect(folderOperationControllerSource).toContain('projectFolderChildOperationValuePatch')
    expect(folderOperationControllerSource).not.toContain('getFolderChildOperationInitialValue')
    expect(folderOperationControllerSource).toContain('canSubmitFolderChildOperationSheet')
    expect(folderOperationControllerSource).toContain('operationConfirmDisabled')
    expect(folderOperationControllerSource).toContain('planFolderChildOperationSubmit')
    expect(folderOperationControllerSource).not.toContain('const [operation, setOperation]')
    expect(folderOperationControllerSource).not.toContain('const [operationValue, setOperationValue]')
    expect(folderOperationControllerSource).not.toContain('projectFolderChildOperationDestination')
    expect(folderOperationControllerSource).not.toContain('planFolderChildCreateMarkdownResource')
    expect(folderOperationControllerSource).not.toContain("from '../../domain/folder/folder-child-open'")
    expect(folderOperationControllerSource).not.toContain("from '../../domain/folder/folder-detail-model'")
    expect(folderOperationControllerSource).not.toContain('normalizeMarkdownFileName')
    expect(folderOperationControllerSource).not.toContain('buildFolderChildCopyName')
    expect(folderOperationControllerSource).not.toContain('resolveFolderChildTransferDestination')
    expect(folderOperationControllerSource).not.toContain("mimeType: 'text/markdown'")
    expect(folderOperationControllerSource).not.toContain("currentOperation.type === 'copy'")
    expect(folderOperationControllerSource).not.toContain("currentOperation.type === 'move'")
    expect(folderOperationControllerSource).not.toMatch(/from ['"].*FolderChildOperationSheet['"]/)
    expect(folderOperationControllerSource).not.toContain('<FolderChildOperationSheet')
    expect(folderOperationControllerSource).not.toContain('FileEditorSheet')
    expect(folderColumnViewShimSource).toMatch(/^export \* from '..\/features\/folder\/FolderDetailColumnView'\n?$/)
    expect(folderChildViewsShimSource).toMatch(/^export \* from '..\/features\/folder\/FolderDetailChildViews'\n?$/)
  })
})
