import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const detailPanePath = 'src/modules/files/features/detail/FileDetailPane.tsx'
const folderDetailPath = 'src/modules/files/features/folder/FolderDetailPreview.tsx'
const operationSheetPath = 'src/modules/files/features/folder/FolderChildOperationSheet.tsx'
const operationControllerPath = 'src/modules/files/features/folder/useFolderDetailOperationController.ts'
const operationSheetShimPath = 'src/modules/files/components/FolderChildOperationSheet.tsx'
const operationModelPath = 'src/modules/files/domain/folder/folder-operation-model.ts'

describe('FolderChildOperationSheet architecture boundary', () => {
  it('keeps folder child operation dialog out of the detail-pane container module', () => {
    const detailPaneSource = readFileSync(detailPanePath, 'utf8')
    const folderDetailSource = existsSync(folderDetailPath)
      ? readFileSync(folderDetailPath, 'utf8')
      : ''

    expect(existsSync(folderDetailPath)).toBe(true)
    expect(existsSync(operationSheetPath)).toBe(true)
    expect(existsSync(operationControllerPath)).toBe(true)
    expect(existsSync(operationModelPath)).toBe(true)
    expect(existsSync(operationSheetShimPath)).toBe(true)
    if (
      !existsSync(folderDetailPath)
      || !existsSync(operationSheetPath)
      || !existsSync(operationControllerPath)
      || !existsSync(operationModelPath)
      || !existsSync(operationSheetShimPath)
    ) return

    const operationSheetSource = readFileSync(operationSheetPath, 'utf8')
    const operationControllerSource = readFileSync(operationControllerPath, 'utf8')
    const operationModelSource = readFileSync(operationModelPath, 'utf8')
    const operationSheetShimSource = readFileSync(operationSheetShimPath, 'utf8')

    expect(detailPaneSource).not.toContain('FolderChildOperationSheet')
    expect(folderDetailSource).toContain("from './FolderChildOperationSheet'")
    expect(folderDetailSource).toContain("from './useFolderDetailOperationController'")
    expect(folderDetailSource).not.toContain("from '../../domain/folder/folder-operation-model'")
    expect(folderDetailSource).not.toContain('getFolderChildOperationValidationMessage')
    expect(folderDetailSource).not.toContain('useCreateFolderResource')
    expect(folderDetailSource).not.toContain('useCreateRawTextResource')
    expect(folderDetailSource).not.toContain('useCopyFileResource')
    expect(folderDetailSource).not.toContain('useMoveFileResource')
    expect(folderDetailSource).not.toContain('useDeleteFileResource')
    expect(folderDetailSource).not.toContain('目标和原文件相同')
    expect(folderDetailSource).not.toContain('不能移动到其他 Pod')
    expect(folderDetailSource).not.toContain('名称不能包含路径')
    expect(folderDetailSource).not.toContain('同名项目已存在')
    expect(folderDetailSource).not.toContain("from '../../components/FolderChildOperationSheet'")
    expect(detailPaneSource).not.toMatch(/\nfunction FolderChildOperationSheet\(/)
    expect(folderDetailSource).not.toMatch(/\nfunction FolderChildOperationSheet\(/)
    expect(operationSheetSource).toMatch(/\nexport function FolderChildOperationSheet\(/)
    expect(operationSheetSource).toContain("from '../../domain/folder/folder-operation-model'")
    expect(operationSheetSource).toContain('projectFolderChildOperationSheetModel')
    expect(operationSheetSource).toContain('projectFolderChildOperationConfirmChrome')
    expect(operationSheetSource).not.toContain('canSubmitFolderChildOperationSheet')
    expect(operationSheetSource).toContain('confirmDisabled')
    expect(operationSheetSource).toContain('confirmChrome.label')
    expect(operationSheetSource).not.toContain('处理中')
    expect(operationSheetSource).not.toMatch(/\nexport type FolderChildOperation =/)
    expect(operationSheetSource).not.toContain('operation.children.length')
    expect(operationSheetSource).not.toContain('trim().length')
    expect(operationSheetSource).not.toContain('switch (operation.type)')
    expect(operationSheetSource).not.toContain("case 'rename'")
    expect(operationSheetSource).not.toContain('useFileDetail')
    expect(operationSheetSource).not.toContain('useFilesStore')
    expect(operationSheetSource).not.toContain('FileDetailPane')
    expect(operationControllerSource).toContain("from '../../domain/folder/folder-operation-model'")
    expect(operationControllerSource).toContain('getFolderChildOperationValidationMessage')
    expect(operationControllerSource).toContain('createFolderChildOperationState')
    expect(operationControllerSource).toContain('projectFolderChildOperationOpened')
    expect(operationControllerSource).toContain('projectFolderChildOperationReset')
    expect(operationControllerSource).toContain('projectFolderChildOperationValuePatch')
    expect(operationControllerSource).not.toContain('getFolderChildOperationInitialValue')
    expect(operationControllerSource).toContain('canSubmitFolderChildOperationSheet')
    expect(operationControllerSource).toContain('operationConfirmDisabled')
    expect(operationControllerSource).toContain('planFolderChildOperationSubmit')
    expect(operationControllerSource).not.toContain('const [operation, setOperation]')
    expect(operationControllerSource).not.toContain('const [operationValue, setOperationValue]')
    expect(operationControllerSource).not.toContain('setOperationValue(value ??')
    expect(operationControllerSource).not.toContain('setOperation(null)')
    expect(operationControllerSource).not.toContain('projectFolderChildOperationDestination')
    expect(operationControllerSource).not.toContain('planFolderChildCreateMarkdownResource')
    expect(operationControllerSource).toContain('useCreateFolderResource')
    expect(operationControllerSource).toContain('useCreateRawTextResource')
    expect(operationControllerSource).toContain('useCopyFileResource')
    expect(operationControllerSource).toContain('useMoveFileResource')
    expect(operationControllerSource).toContain('useDeleteFileResource')
    expect(operationControllerSource).not.toContain("from '../../domain/folder/folder-child-open'")
    expect(operationControllerSource).not.toContain("from '../../domain/folder/folder-detail-model'")
    expect(operationControllerSource).not.toContain('buildFolderChildCopyName')
    expect(operationControllerSource).not.toContain('buildFolderChildRenameDestination')
    expect(operationControllerSource).not.toContain('resolveFolderChildTransferDestination')
    expect(operationControllerSource).not.toContain('normalizeMarkdownFileName')
    expect(operationControllerSource).not.toContain("trimmedValue.includes('/')")
    expect(operationControllerSource).not.toContain("mimeType: 'text/markdown'")
    expect(operationControllerSource).not.toContain("currentOperation.type === 'copy'")
    expect(operationControllerSource).not.toContain("currentOperation.type === 'move'")
    expect(operationControllerSource).not.toMatch(/from ['"].*FolderChildOperationSheet['"]/)
    expect(operationControllerSource).not.toContain('<FolderChildOperationSheet')
    expect(operationModelSource).toContain('export type FolderChildOperation')
    expect(operationModelSource).toContain('export function getFolderChildOperationValidationMessage')
    expect(operationModelSource).toContain('export function projectFolderChildOperationSheetModel')
    expect(operationModelSource).toContain('export function projectFolderChildOperationConfirmChrome')
    expect(operationModelSource).toContain('export function canSubmitFolderChildOperationSheet')
    expect(operationModelSource).toContain('export function getFolderChildOperationInitialValue')
    expect(operationModelSource).toContain('export function createFolderChildOperationState')
    expect(operationModelSource).toContain('export function projectFolderChildOperationOpened')
    expect(operationModelSource).toContain('export function projectFolderChildOperationReset')
    expect(operationModelSource).toContain('export function projectFolderChildOperationValuePatch')
    expect(operationModelSource).toContain('export function projectFolderChildOperationDestination')
    expect(operationModelSource).toContain('export function planFolderChildCreateMarkdownResource')
    expect(operationModelSource).toContain('export function planFolderChildOperationSubmit')
    expect(operationModelSource).not.toContain("from '../../features")
    expect(operationModelSource).not.toContain('useToast')
    expect(operationSheetShimSource).toMatch(/^export \* from '..\/features\/folder\/FolderChildOperationSheet'\n?$/)
  })
})
