import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const previewPath = 'src/modules/files/features/structured/StructuredTablePreview.tsx'
const kanbanPath = 'src/modules/files/features/structured/StructuredKanbanView.tsx'
const kanbanViewControllerPath = 'src/modules/files/features/structured/useStructuredKanbanViewController.ts'
const kanbanViewModelPath = 'src/modules/files/features/structured/structured-kanban-view-model.ts'
const kanbanMoveControllerPath = 'src/modules/files/features/structured/useStructuredKanbanMoveController.ts'
const kanbanMoveModelPath = 'src/modules/files/features/structured/structured-kanban-move-model.ts'
const kanbanShimPath = 'src/modules/files/components/StructuredKanbanView.tsx'
const whiteboardPath = 'src/modules/files/features/structured/StructuredWhiteboardView.tsx'
const whiteboardViewControllerPath = 'src/modules/files/features/structured/useStructuredWhiteboardViewController.ts'
const whiteboardViewModelPath = 'src/modules/files/features/structured/structured-whiteboard-view-model.ts'
const whiteboardRelationControllerPath = 'src/modules/files/features/structured/useStructuredWhiteboardRelationController.ts'
const whiteboardRelationModelPath = 'src/modules/files/features/structured/structured-whiteboard-relation-model.ts'
const whiteboardShimPath = 'src/modules/files/components/StructuredWhiteboardView.tsx'
const subjectPeekPath = 'src/modules/files/features/structured/StructuredSubjectPeek.tsx'
const subjectPeekActionsPath = 'src/modules/files/features/structured/StructuredSubjectPeekActions.tsx'
const subjectPeekActionsModelPath = 'src/modules/files/features/structured/structured-subject-peek-actions-model.ts'
const subjectPeekBodyControllerPath = 'src/modules/files/features/structured/useStructuredSubjectPeekBodyController.ts'
const subjectPeekBodyModelPath = 'src/modules/files/features/structured/structured-subject-peek-body-model.ts'
const subjectPeekShimPath = 'src/modules/files/components/StructuredSubjectPeek.tsx'
const subjectPeekModelPath = 'src/modules/files/domain/structured/structured-subject-peek.ts'
const lockedVocabPath = 'src/modules/files/features/structured/LockedVocabTablePreview.tsx'
const lockedVocabControllerPath = 'src/modules/files/features/structured/useLockedVocabPreviewController.ts'
const lockedVocabPreviewModelPath = 'src/modules/files/features/structured/locked-vocab-preview-model.ts'
const lockedVocabRegistryTableControllerPath = 'src/modules/files/features/structured/useLockedVocabRegistryTableController.ts'
const lockedVocabRegistryTableModelPath = 'src/modules/files/features/structured/locked-vocab-registry-table-model.ts'
const lockedVocabShimPath = 'src/modules/files/components/LockedVocabTablePreview.tsx'
const addPredicateMenuPath = 'src/modules/files/features/structured/AddPredicateMenu.tsx'
const addPredicateMenuControllerPath = 'src/modules/files/features/structured/useAddPredicateMenuController.ts'
const addPredicateMenuModelPath = 'src/modules/files/features/structured/structured-add-predicate-menu-model.ts'
const predicateColumnHeaderPath = 'src/modules/files/features/structured/StructuredPredicateColumnHeader.tsx'
const pendingPredicateColumnsPath = 'src/modules/files/features/structured/useStructuredPendingPredicateColumns.ts'
const pendingPredicateColumnsModelPath = 'src/modules/files/features/structured/structured-pending-predicate-columns-model.ts'
const vocabProposalWorkflowControllerPath = 'src/modules/files/features/structured/useStructuredVocabProposalWorkflowController.ts'
const vocabProposalWorkflowModelPath = 'src/modules/files/features/structured/structured-vocab-proposal-workflow-model.ts'
const predicateDraftPath = 'src/modules/files/domain/structured/structured-predicate-draft.ts'
const projectionTablePath = 'src/modules/files/features/structured/StructuredProjectionTable.tsx'
const projectionTableColumnsPath = 'src/modules/files/features/structured/StructuredProjectionTableColumns.tsx'
const subjectNavigationControllerPath = 'src/modules/files/features/structured/useStructuredSubjectNavigationController.ts'
const subjectNavigationModelPath = 'src/modules/files/features/structured/structured-subject-navigation-model.ts'
const viewportControllerPath = 'src/modules/files/features/structured/useStructuredViewportController.ts'

describe('StructuredKanbanView architecture boundary', () => {
  it('keeps Kanban view and dnd dependencies out of the structured table preview container', () => {
    const previewSource = readFileSync(previewPath, 'utf8')

    expect(existsSync(kanbanPath)).toBe(true)
    expect(existsSync(kanbanViewControllerPath)).toBe(true)
    expect(existsSync(kanbanViewModelPath)).toBe(true)
    expect(existsSync(kanbanMoveControllerPath)).toBe(true)
    expect(existsSync(kanbanMoveModelPath)).toBe(true)
    if (!existsSync(kanbanPath) || !existsSync(kanbanViewControllerPath) || !existsSync(kanbanViewModelPath) || !existsSync(kanbanMoveControllerPath) || !existsSync(kanbanMoveModelPath)) return

    const kanbanSource = readFileSync(kanbanPath, 'utf8')
    const kanbanViewControllerSource = readFileSync(kanbanViewControllerPath, 'utf8')
    const kanbanViewModelSource = readFileSync(kanbanViewModelPath, 'utf8')
    const kanbanMoveControllerSource = readFileSync(kanbanMoveControllerPath, 'utf8')
    const kanbanMoveModelSource = readFileSync(kanbanMoveModelPath, 'utf8')
    const kanbanShimSource = readFileSync(kanbanShimPath, 'utf8')

    expect(previewSource).toContain("from './StructuredKanbanView'")
    expect(previewSource).not.toMatch(/\nfunction StructuredKanbanView\(/)
    expect(previewSource).not.toMatch(/\nfunction StructuredCard\(/)
    expect(previewSource).not.toContain('@dnd-kit/core')
    expect(previewSource).not.toContain('@dnd-kit/sortable')
    expect(previewSource).not.toContain('@dnd-kit/utilities')

    expect(kanbanSource).toMatch(/\nexport function StructuredKanbanView\(/)
    expect(kanbanSource).toContain('@dnd-kit/core')
    expect(kanbanSource).toContain('useStructuredKanbanViewController')
    expect(kanbanSource).not.toContain('projectStructuredKanban')
    expect(kanbanSource).not.toContain('useStructuredKanbanMoveController')
    expect(kanbanSource).not.toContain('useState')
    expect(kanbanSource).not.toContain('useStructuredCellCommitController')
    expect(kanbanSource).not.toContain('setPendingMoves')
    expect(kanbanSource).not.toContain('setDraggingSubject')
    expect(kanbanSource).not.toContain('setDragOverColumnId')
    expect(kanbanSource).not.toContain('columns.length > 0')
    expect(kanbanSource).not.toContain('column.cards.length')
    expect(kanbanSource).not.toContain('items={column.cards.map((card) => card.subject)}')
    expect(kanbanSource).toContain('kanban.chrome')
    expect(kanbanSource).toContain('column.ariaLabel')
    expect(kanbanSource).toContain('card.openAriaLabel')
    expect(kanbanSource).toContain('card.moveButtonAriaLabel')
    expect(kanbanSource).toContain('card.visibleTags')
    expect(kanbanSource).not.toContain('card.tags.slice(0, 3)')
    expect(kanbanSource).toContain('column.moveMenuItemLabel')
    expect(kanbanSource).not.toContain('移动到 {column.label}')
    expect(kanbanSource).not.toContain('没有可投影到 Kanban 的 subject。')
    expect(kanbanSource).not.toContain('aria-label="Kanban 分组 predicate"')
    expect(kanbanSource).not.toContain('`Kanban column ${column.label}`')
    expect(kanbanSource).not.toContain('`打开 subject ${card.subject}`')
    expect(kanbanSource).not.toContain('`Move ${card.subject}`')
    expect(kanbanSource).not.toContain('pendingMove.status')
    expect(kanbanSource).not.toContain('approval-staged')
    expect(kanbanSource).toContain('canMoveCardsInColumn')
    expect(kanbanSource).toContain('cardCountLabel')
    expect(kanbanSource).toContain('pendingMove.label')
    expect(kanbanSource).not.toMatch(/\n  const pendingMoves\b/)
    expect(kanbanSource).not.toMatch(/\n  const commitKanbanMove =/)
    expect(kanbanSource).not.toMatch(/\n  const reorderColumnSubjects =/)
    expect(kanbanSource).not.toContain('StructuredTablePreview')
    expect(kanbanSource).not.toContain('useFilesStore')
    expect(kanbanViewControllerSource).toContain('export function useStructuredKanbanViewController')
    expect(kanbanViewControllerSource).toContain("from './structured-kanban-view-model'")
    expect(kanbanViewControllerSource).toContain('projectStructuredKanbanSourceModel')
    expect(kanbanViewControllerSource).toContain('projectStructuredKanbanDisplayColumns')
    expect(kanbanViewControllerSource).toContain('projectStructuredKanbanCardBySubject')
    expect(kanbanViewControllerSource).toContain('projectStructuredKanbanDndDragEndPlan')
    expect(kanbanViewControllerSource).toContain('findStructuredKanbanColumnForSubject')
    expect(kanbanViewControllerSource).not.toContain('findStructuredKanbanTargetColumnForDndOverId')
    expect(kanbanViewControllerSource).toContain('createStructuredKanbanNativeDragState')
    expect(kanbanViewControllerSource).toContain('projectStructuredKanbanNativeDragStarted')
    expect(kanbanViewControllerSource).toContain('projectStructuredKanbanNativeDragOverColumn')
    expect(kanbanViewControllerSource).toContain('projectStructuredKanbanNativeDragLeftColumn')
    expect(kanbanViewControllerSource).toContain('projectStructuredKanbanNativeDragCleared')
    expect(kanbanViewControllerSource).toContain('projectStructuredKanbanMoveTargets')
    expect(kanbanViewControllerSource).toContain('hasStructuredKanbanMoveTargets')
    expect(kanbanViewControllerSource).toContain('useStructuredKanbanMoveController')
    expect(kanbanViewControllerSource).toContain('canMoveCardsInColumn')
    expect(kanbanViewModelSource).toContain('visibleTags')
    expect(kanbanViewModelSource).toContain('projectStructuredKanbanCardVisibleTags')
    expect(kanbanViewControllerSource).toContain('handleDndDragEnd')
    expect(kanbanViewControllerSource).not.toContain('function cardPendingMoveView')
    expect(kanbanViewControllerSource).not.toContain("from '../../domain/structured/structured-projections'")
    expect(kanbanViewControllerSource).not.toContain('cardCountLabel')
    expect(kanbanViewControllerSource).not.toMatch(/\bprojectStructuredKanban\(/)
    expect(kanbanViewControllerSource).not.toContain('localPredicateLabel')
    expect(kanbanViewControllerSource).not.toContain('projection.predicates.map')
    expect(kanbanViewControllerSource).not.toContain('column.cards.length')
    expect(kanbanViewControllerSource).not.toContain('flatMap((column)')
    expect(kanbanViewControllerSource).not.toContain('displayColumns.find')
    expect(kanbanViewControllerSource).not.toContain('setDraggingSubject')
    expect(kanbanViewControllerSource).not.toContain('setDragOverColumnId')
    expect(kanbanViewControllerSource).not.toContain('current === column.id ? null : current')
    expect(kanbanViewControllerSource).not.toContain('<DndContext')
    expect(kanbanViewControllerSource).not.toContain('<SortableContext')
    expect(kanbanViewControllerSource).not.toMatch(/\nfunction StructuredCard\(/)
    expect(kanbanViewControllerSource).not.toContain('<StructuredCard')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanSourceModel')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanDisplayColumns')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanChrome')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanColumnChrome')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanCardChrome')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanMoveTargetChrome')
    expect(kanbanViewModelSource).toContain('cardSubjects')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanCardBySubject')
    expect(kanbanViewModelSource).toContain('export function findStructuredKanbanColumnForSubject')
    expect(kanbanViewModelSource).toContain('export function findStructuredKanbanTargetColumnForDndOverId')
    expect(kanbanViewModelSource).toContain('export function createStructuredKanbanNativeDragState')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanNativeDragStarted')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanNativeDragOverColumn')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanNativeDragLeftColumn')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanNativeDragCleared')
    expect(kanbanViewModelSource).toContain('export function projectStructuredKanbanMoveTargets')
    expect(kanbanViewModelSource).toContain('export function hasStructuredKanbanMoveTargets')
    expect(kanbanViewModelSource).toContain('projectStructuredKanban')
    expect(kanbanViewModelSource).toContain('localPredicateLabel')
    expect(kanbanViewModelSource).toContain('projection.predicates.map')
    expect(kanbanViewModelSource).toContain('column.cards.length')
    expect(kanbanViewModelSource).toContain('displayColumns.find')
    expect(kanbanViewModelSource).toContain('cardCountLabel')
    expect(kanbanViewModelSource).not.toContain('useState')
    expect(kanbanViewModelSource).not.toContain('useMemo')
    expect(kanbanMoveControllerSource).toContain('export function useStructuredKanbanMoveController')
    expect(kanbanMoveControllerSource).toContain("from './structured-kanban-move-model'")
    expect(kanbanMoveControllerSource).toContain('projectStructuredKanbanMoveModel')
    expect(kanbanMoveControllerSource).toContain('projectStructuredKanbanPendingMoveView')
    expect(kanbanMoveControllerSource).toContain('projectStructuredKanbanColumnSubjectReorder')
    expect(kanbanMoveControllerSource).toContain('projectStructuredStagedKanbanPendingMoves')
    expect(kanbanMoveControllerSource).toContain('projectStructuredDiscardedKanbanPendingMoves')
    expect(kanbanMoveControllerSource).toContain('projectStructuredApprovalStagedKanbanPendingMoves')
    expect(kanbanMoveControllerSource).toContain('useStructuredCellCommitController')
    expect(kanbanMoveControllerSource).toContain('commitKanbanMove')
    expect(kanbanMoveControllerSource).toContain('pendingMoveViewForSubject')
    expect(kanbanMoveControllerSource).toContain('reorderColumnSubjects')
    expect(kanbanMoveControllerSource).not.toContain('localPredicateLabel')
    expect(kanbanMoveControllerSource).not.toContain('sourceColumns.map')
    expect(kanbanMoveControllerSource).not.toContain('displayColumns.find')
    expect(kanbanMoveControllerSource).not.toContain('currentSubjects')
    expect(kanbanMoveControllerSource).not.toContain('fromIndex')
    expect(kanbanMoveControllerSource).not.toContain('nextSubjects.splice')
    expect(kanbanMoveControllerSource).not.toContain('[card.subject]: {')
    expect(kanbanMoveControllerSource).not.toContain('delete next[card.subject]')
    expect(kanbanMoveControllerSource).not.toContain("status: 'approval-staged'")
    expect(kanbanMoveControllerSource).not.toContain('@dnd-kit/core')
    expect(kanbanMoveControllerSource).not.toMatch(/\nfunction StructuredCard\b/)
    expect(kanbanMoveControllerSource).not.toContain('<StructuredCard')
    expect(kanbanMoveModelSource).toContain('export function projectStructuredKanbanMoveModel')
    expect(kanbanMoveModelSource).toContain('export function projectStructuredKanbanPendingMoveView')
    expect(kanbanMoveModelSource).toContain('export function projectStructuredKanbanColumnSubjectReorder')
    expect(kanbanMoveModelSource).toContain('export function projectStructuredStagedKanbanPendingMoves')
    expect(kanbanMoveModelSource).toContain('export function projectStructuredDiscardedKanbanPendingMoves')
    expect(kanbanMoveModelSource).toContain('export function projectStructuredApprovalStagedKanbanPendingMoves')
    expect(kanbanMoveModelSource).toContain('localPredicateLabel')
    expect(kanbanMoveModelSource).toContain('sourceColumns.map')
    expect(kanbanMoveModelSource).toContain('displayColumns.find')
    expect(kanbanMoveModelSource).toContain('currentSubjects')
    expect(kanbanMoveModelSource).not.toContain('useState')
    expect(kanbanMoveModelSource).not.toContain('useMemo')
    expect(kanbanShimSource).toMatch(/^export \* from '..\/features\/structured\/StructuredKanbanView'\n?$/)
  })

  it('keeps the Whiteboard projection view out of the structured table preview container', () => {
    const previewSource = readFileSync(previewPath, 'utf8')

    expect(existsSync(whiteboardPath)).toBe(true)
    expect(existsSync(whiteboardViewControllerPath)).toBe(true)
    expect(existsSync(whiteboardViewModelPath)).toBe(true)
    expect(existsSync(whiteboardRelationControllerPath)).toBe(true)
    expect(existsSync(whiteboardRelationModelPath)).toBe(true)
    if (
      !existsSync(whiteboardPath)
      || !existsSync(whiteboardViewControllerPath)
      || !existsSync(whiteboardViewModelPath)
      || !existsSync(whiteboardRelationControllerPath)
      || !existsSync(whiteboardRelationModelPath)
    ) return

    const whiteboardSource = readFileSync(whiteboardPath, 'utf8')
    const whiteboardViewControllerSource = readFileSync(whiteboardViewControllerPath, 'utf8')
    const whiteboardViewModelSource = readFileSync(whiteboardViewModelPath, 'utf8')
    const whiteboardRelationControllerSource = readFileSync(whiteboardRelationControllerPath, 'utf8')
    const whiteboardRelationModelSource = readFileSync(whiteboardRelationModelPath, 'utf8')
    const whiteboardShimSource = readFileSync(whiteboardShimPath, 'utf8')

    expect(previewSource).toContain("from './StructuredWhiteboardView'")
    expect(previewSource).toContain('className="relative min-h-full p-2 space-y-2"')
    expect(previewSource).toContain('className="max-h-full overflow-y-auto overflow-x-hidden bg-background px-2 py-2"')
    expect(previewSource).not.toMatch(/\nfunction StructuredWhiteboardView\(/)
    expect(previewSource).not.toMatch(/\nfunction clampWhiteboardPosition\(/)
    expect(previewSource).not.toContain('projectStructuredWhiteboard')

    expect(whiteboardSource).toMatch(/\nexport function StructuredWhiteboardView\(/)
    expect(whiteboardSource).toContain('useStructuredWhiteboardViewController')
    expect(whiteboardSource).not.toContain('projectStructuredWhiteboard')
    expect(whiteboardSource).not.toContain('useStructuredWhiteboardRelationController')
    expect(whiteboardSource).not.toContain('useState')
    expect(whiteboardSource).not.toContain('useLayoutEffect')
    expect(whiteboardSource).not.toContain('setDraggingSubject')
    expect(whiteboardSource).not.toContain('suppressNextNodeOpenRef')
    expect(whiteboardSource).not.toContain('clampWhiteboardPosition')
    expect(whiteboardSource).not.toContain('resetAncestorHorizontalScroll')
    expect(whiteboardSource).not.toContain('setRelationEditorOpen')
    expect(whiteboardSource).not.toContain('setEditingRelationId')
    expect(whiteboardSource).not.toContain('setRelationFrom')
    expect(whiteboardSource).not.toContain('setRelationTo')
    expect(whiteboardSource).not.toContain('setRelationLabel')
    expect(whiteboardSource).not.toContain('nodes.find')
    expect(whiteboardSource).not.toContain('from.x')
    expect(whiteboardSource).not.toContain('from.y')
    expect(whiteboardSource).not.toContain('to.x')
    expect(whiteboardSource).not.toContain('to.y')
    expect(whiteboardSource).toContain('whiteboard.relationSegments.map')
    expect(whiteboardSource).toContain('strokeDasharray={relation.strokeDasharray}')
    expect(whiteboardSource).not.toContain("relation.source === 'visual' ?")
    expect(whiteboardSource).not.toContain('visualRelationChips.length')
    expect(whiteboardSource).toContain('hasVisualRelationChips')
    expect(whiteboardSource).toContain('whiteboard.chrome')
    expect(whiteboardSource).toContain('data-whiteboard-toolbar-scroll="actions"')
    expect(whiteboardSource).toContain('data-whiteboard-canvas-scroll="true"')
    expect(whiteboardSource).toContain('-mx-2')
    expect(whiteboardSource).toContain('min-h-[480px]')
    expect(whiteboardSource).toContain('border-y border-border/10')
    expect(whiteboardSource).not.toContain('rounded-md border border-border/20')
    expect(whiteboardSource).toContain('overflow-x-auto')
    expect(whiteboardSource).toContain('overflow-auto')
    expect(whiteboardSource).toContain('relationEditorChrome')
    expect(whiteboardSource).toContain('node.openAriaLabel')
    expect(whiteboardSource).toContain('node.removeAriaLabel')
    expect(whiteboardSource).not.toContain('aria-label="添加 subject 到白板"')
    expect(whiteboardSource).not.toContain('>Subject<')
    expect(whiteboardSource).not.toContain('可见 subject 已全部加入白板')
    expect(whiteboardSource).not.toContain('aria-label="添加视觉关系"')
    expect(whiteboardSource).not.toContain('>关系<')
    expect(whiteboardSource).not.toContain('aria-label="清空白板 subject"')
    expect(whiteboardSource).not.toContain('>清空<')
    expect(whiteboardSource).not.toContain('添加 subject 后会在白板中显示卡片。')
    expect(whiteboardSource).not.toContain('`打开 subject ${node.subject}`')
    expect(whiteboardSource).not.toContain('`从白板移除 ${node.subject}`')
    expect(whiteboardSource).not.toContain('aria-label="Relation from"')
    expect(whiteboardSource).not.toContain('aria-label="Relation to"')
    expect(whiteboardSource).not.toContain('aria-label="Relation label"')
    expect(whiteboardSource).not.toContain('placeholder="视觉关系"')
    expect(whiteboardSource).not.toContain("whiteboard.editingRelationId ? '保存视觉关系' : '创建视觉关系'")
    expect(whiteboardSource).not.toContain('aria-label="取消视觉关系"')
    expect(whiteboardSource).not.toMatch(/\n  const nextVisualRelationId\b/)
    expect(whiteboardSource).not.toMatch(/\n  const saveVisualRelation\b/)
    expect(whiteboardSource).not.toMatch(/\n  const removeVisualRelation\b/)
    expect(whiteboardSource).not.toContain('StructuredTablePreview')
    expect(whiteboardSource).not.toContain('useFilesStore')
    expect(whiteboardViewControllerSource).toContain('export function useStructuredWhiteboardViewController')
    expect(whiteboardViewControllerSource).toContain("from './structured-whiteboard-view-model'")
    expect(whiteboardViewControllerSource).toContain('projectStructuredWhiteboardViewModel')
    expect(whiteboardViewControllerSource).toContain('projectStructuredWhiteboardClampedPosition')
    expect(whiteboardViewControllerSource).toContain('useStructuredWhiteboardRelationController')
    expect(whiteboardViewControllerSource).not.toMatch(/\nfunction clampWhiteboardPosition\(/)
    expect(whiteboardViewControllerSource).toContain('resetAncestorHorizontalScroll')
    expect(whiteboardViewControllerSource).toContain('relationSegments')
    expect(whiteboardViewControllerSource).toContain('startNodeDrag')
    expect(whiteboardViewControllerSource).not.toContain("from '../../domain/structured/structured-projections'")
    expect(whiteboardViewControllerSource).not.toContain('projection.rows.filter((row) => !selectedSubjects.includes(row.subject))')
    expect(whiteboardViewControllerSource).not.toContain('new Map(nodes.map((node) => [node.subject, node]))')
    expect(whiteboardViewControllerSource).not.toContain('whiteboard.relations.flatMap')
    expect(whiteboardViewControllerSource).not.toContain('<svg')
    expect(whiteboardViewControllerSource).not.toContain('DropdownMenu')
    expect(whiteboardViewModelSource).toContain('export function projectStructuredWhiteboardViewModel')
    expect(whiteboardViewModelSource).toContain('export function projectStructuredWhiteboardChrome')
    expect(whiteboardViewModelSource).toContain('export function projectStructuredWhiteboardNodeChrome')
    expect(whiteboardViewModelSource).toContain('export function projectStructuredWhiteboardClampedPosition')
    expect(whiteboardViewModelSource).toContain('projectStructuredWhiteboard')
    expect(whiteboardViewModelSource).toContain('relationSegments')
    expect(whiteboardViewModelSource).toContain('strokeDasharray')
    expect(whiteboardViewModelSource).not.toContain('useStructuredWhiteboardRelationController')
    expect(whiteboardViewModelSource).not.toContain('useState')
    expect(whiteboardViewModelSource).not.toContain('useMemo')
    expect(whiteboardRelationControllerSource).toContain('export function useStructuredWhiteboardRelationController')
    expect(whiteboardRelationControllerSource).toContain("from './structured-whiteboard-relation-model'")
    expect(whiteboardRelationControllerSource).toContain('createStructuredWhiteboardRelationEditorState')
    expect(whiteboardRelationControllerSource).toContain('projectStructuredWhiteboardRelationEditorNew')
    expect(whiteboardRelationControllerSource).toContain('projectStructuredWhiteboardRelationEditorForRelation')
    expect(whiteboardRelationControllerSource).toContain('projectStructuredWhiteboardRelationEditorFromPatch')
    expect(whiteboardRelationControllerSource).toContain('projectStructuredWhiteboardRelationEditorSaved')
    expect(whiteboardRelationControllerSource).toContain('projectStructuredWhiteboardRelationModel')
    expect(whiteboardRelationControllerSource).toContain('projectStructuredWhiteboardRelationDraft')
    expect(whiteboardRelationControllerSource).toContain('projectStructuredWhiteboardVisualRelationsAfterRemove')
    expect(whiteboardRelationControllerSource).toContain('projectStructuredWhiteboardVisualRelationsAfterSave')
    expect(whiteboardRelationControllerSource).toContain('saveVisualRelation')
    expect(whiteboardRelationControllerSource).toContain('removeVisualRelation')
    expect(whiteboardRelationControllerSource).toContain('hasVisualRelationChips')
    expect(whiteboardRelationControllerSource).toContain('relationEditorChrome')
    expect(whiteboardRelationControllerSource).toMatch(/\n\s*const \[relationEditorState, setRelationEditorState\]/)
    expect(whiteboardRelationControllerSource).not.toMatch(/\n\s*const \[relationEditorOpen, setRelationEditorOpen\]/)
    expect(whiteboardRelationControllerSource).not.toMatch(/\n\s*const \[editingRelationId, setEditingRelationId\]/)
    expect(whiteboardRelationControllerSource).not.toMatch(/\n\s*const \[relationFrom, setRelationFrom\]/)
    expect(whiteboardRelationControllerSource).not.toMatch(/\n\s*const \[relationTo, setRelationTo\]/)
    expect(whiteboardRelationControllerSource).not.toMatch(/\n\s*const \[relationLabel, setRelationLabel\]/)
    expect(whiteboardRelationControllerSource).not.toContain('setRelationEditorOpen(')
    expect(whiteboardRelationControllerSource).not.toContain('setEditingRelationId(')
    expect(whiteboardRelationControllerSource).not.toContain('setRelationFrom(')
    expect(whiteboardRelationControllerSource).not.toContain('setRelationTo(')
    expect(whiteboardRelationControllerSource).not.toContain('setRelationLabel(')
    expect(whiteboardRelationControllerSource).not.toContain('nextVisualRelationId')
    expect(whiteboardRelationControllerSource).not.toContain('relationSubjectOptions.filter')
    expect(whiteboardRelationControllerSource).not.toContain('relationSubjectOptions.find')
    expect(whiteboardRelationControllerSource).not.toContain('visualRelations.filter')
    expect(whiteboardRelationControllerSource).not.toContain('visualRelations.map')
    expect(whiteboardRelationControllerSource).not.toContain('relation.label || relation.id')
    expect(whiteboardRelationControllerSource).not.toContain('visualRelationChips.length')
    expect(whiteboardRelationControllerSource).not.toContain('relationFrom.trim()')
    expect(whiteboardRelationControllerSource).not.toContain('projectStructuredWhiteboardInitialRelationDraft')
    expect(whiteboardRelationControllerSource).not.toContain('projectStructuredWhiteboardRelationDraftAfterFromChange')
    expect(whiteboardRelationControllerSource).not.toMatch(/\bprojectStructuredWhiteboard\(/)
    expect(whiteboardRelationControllerSource).not.toContain('DropdownMenu')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardRelationModel')
    expect(whiteboardRelationModelSource).toContain('export type StructuredWhiteboardRelationEditorState')
    expect(whiteboardRelationModelSource).toContain('export function createStructuredWhiteboardRelationEditorState')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardInitialRelationDraft')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardRelationDraftAfterFromChange')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardRelationEditorNew')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardRelationEditorForRelation')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardRelationEditorFromPatch')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardRelationEditorSaved')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardRelationDraft')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardRelationEditorChrome')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardVisualRelationsAfterRemove')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardVisualRelationsAfterSave')
    expect(whiteboardRelationModelSource).toContain('export function projectStructuredWhiteboardVisualRelationChips')
    expect(whiteboardRelationModelSource).toContain('nextVisualRelationId')
    expect(whiteboardRelationModelSource).toContain('relationSubjectOptions.filter')
    expect(whiteboardRelationModelSource).toContain('visualRelations.map')
    expect(whiteboardRelationModelSource).toContain('relation.label || relation.id')
    expect(whiteboardRelationModelSource).toContain('visualRelationChips.length')
    expect(whiteboardRelationModelSource).not.toContain('useState')
    expect(whiteboardRelationModelSource).not.toContain('useMemo')
    expect(whiteboardShimSource).toMatch(/^export \* from '..\/features\/structured\/StructuredWhiteboardView'\n?$/)
  })

  it('keeps the shared structured subject peek drawer out of the structured table preview container', () => {
    const previewSource = readFileSync(previewPath, 'utf8')
    const lockedVocabSource = readFileSync(lockedVocabPath, 'utf8')

    expect(existsSync(subjectPeekPath)).toBe(true)
    expect(existsSync(subjectPeekActionsPath)).toBe(true)
    expect(existsSync(subjectPeekActionsModelPath)).toBe(true)
    expect(existsSync(subjectPeekBodyControllerPath)).toBe(true)
    expect(existsSync(subjectPeekBodyModelPath)).toBe(true)
    expect(existsSync(subjectPeekShimPath)).toBe(true)
    if (!existsSync(subjectPeekPath) || !existsSync(subjectPeekActionsPath) || !existsSync(subjectPeekActionsModelPath) || !existsSync(subjectPeekBodyControllerPath) || !existsSync(subjectPeekBodyModelPath) || !existsSync(subjectPeekShimPath)) return

    const subjectPeekSource = readFileSync(subjectPeekPath, 'utf8')
    const subjectPeekActionsSource = readFileSync(subjectPeekActionsPath, 'utf8')
    const subjectPeekActionsModelSource = readFileSync(subjectPeekActionsModelPath, 'utf8')
    const subjectPeekBodyControllerSource = readFileSync(subjectPeekBodyControllerPath, 'utf8')
    const subjectPeekBodyModelSource = readFileSync(subjectPeekBodyModelPath, 'utf8')
    const subjectPeekShimSource = readFileSync(subjectPeekShimPath, 'utf8')

    expect(previewSource).toContain("from './StructuredSubjectPeek'")
    expect(previewSource).toContain("from './StructuredSubjectPeekActions'")
    expect(previewSource).not.toContain("from '../../components/StructuredSubjectPeek'")
    expect(previewSource).not.toMatch(/\nfunction StructuredSubjectPeekDrawer\(/)
    expect(previewSource).not.toMatch(/\nfunction StructuredSubjectPeekBody\(/)
    expect(previewSource).not.toContain("subjectPeek?.kind === 'resource'")
    expect(previewSource).not.toContain("subjectPeek?.kind === 'external'")
    expect(previewSource).not.toContain('打开承载文件')

    expect(lockedVocabSource).toContain("from './StructuredSubjectPeekActions'")
    expect(lockedVocabSource).not.toContain('termPeekTargetsCurrentFile ?')
    expect(lockedVocabSource).not.toContain('打开承载文件')
    expect(lockedVocabSource).not.toContain('关闭')

    expect(subjectPeekSource).toMatch(/\nexport function StructuredSubjectPeekDrawer\(/)
    expect(subjectPeekSource).toMatch(/\nfunction StructuredSubjectPeekBody\(/)
    expect(subjectPeekSource).toContain('useStructuredSubjectPeekBodyController')
    expect(subjectPeekSource).not.toContain('useState')
    expect(subjectPeekSource).not.toContain('localPredicateLabel')
    expect(subjectPeekSource).not.toContain('normalizeStructuredCellResourceValue')
    expect(subjectPeekSource).not.toContain('displayStructuredFactValue')
    expect(subjectPeekSource).not.toContain('StructuredTablePreview')
    expect(subjectPeekSource).toContain('peekBody.chrome.summary.ariaLabel')
    expect(subjectPeekSource).toContain('peekBody.chrome.sourceLinkedSection.heading')
    expect(subjectPeekSource).toContain('peekBody.chrome.predicateSection.heading')
    expect(subjectPeekSource).toContain('peekBody.chrome.backlinkSection.heading')
    expect(subjectPeekSource).toContain('peekBody.chrome.termDefinitionSection.heading')
    expect(subjectPeekSource).toContain('peekBody.chrome.sourceSection.heading')
    expect(subjectPeekSource).toContain('peekBody.chrome.technicalDetails.ariaLabel')
    expect(subjectPeekSource).toContain('peekBody.technicalDetailsToggle.stateLabel')
    expect(subjectPeekSource).not.toContain('Subject card summary')
    expect(subjectPeekSource).not.toContain('来源与同步信息')
    expect(subjectPeekSource).not.toContain('来源与同步')
    expect(subjectPeekSource).not.toContain('>属性<')
    expect(subjectPeekSource).not.toContain('>反向链接<')
    expect(subjectPeekSource).not.toContain('>term 定义<')
    expect(subjectPeekSource).not.toContain('aria-label="查看 URI 详情"')
    expect(subjectPeekSource).not.toContain('>更多信息<')
    expect(subjectPeekSource).not.toContain("peekBody.technicalDetailsOpen ? '收起' : 'URI'")
    expect(subjectPeekActionsSource).toMatch(/\nexport function StructuredSubjectPeekActions\(/)
    expect(subjectPeekActionsSource).toContain('projectStructuredSubjectPeekActions')
    expect(subjectPeekActionsSource).toContain('className={action.className}')
    expect(subjectPeekActionsSource).toContain('ResourceSidecarActions')
    expect(subjectPeekActionsSource).not.toContain('function actionButtonClass')
    expect(subjectPeekActionsSource).not.toContain("action.variant === 'primary'")
    expect(subjectPeekActionsSource).not.toContain('useState')
    expect(subjectPeekActionsSource).not.toContain('StructuredTablePreview')
    expect(subjectPeekActionsSource).not.toContain('LockedVocabTablePreview')
    expect(subjectPeekActionsModelSource).toContain('export function projectStructuredSubjectPeekActions')
    expect(subjectPeekActionsModelSource).toContain('className')
    expect(subjectPeekActionsModelSource).not.toContain('<button')
    expect(subjectPeekActionsModelSource).not.toContain('ResourceSidecarActions')
    expect(subjectPeekBodyControllerSource).toContain('export function useStructuredSubjectPeekBodyController')
    expect(subjectPeekBodyControllerSource).toContain("from './structured-subject-peek-body-model'")
    expect(subjectPeekBodyControllerSource).toContain('projectStructuredSubjectPeekBodyModel')
    expect(subjectPeekBodyControllerSource).not.toContain('localPredicateLabel')
    expect(subjectPeekBodyControllerSource).not.toContain('normalizeStructuredCellResourceValue')
    expect(subjectPeekBodyControllerSource).not.toContain('displayStructuredFactValue')
    expect(subjectPeekBodyControllerSource).not.toContain('StructuredSubjectPeekDrawer')
    expect(subjectPeekBodyControllerSource).not.toContain('<button')
    expect(subjectPeekBodyModelSource).toContain('export function projectStructuredSubjectPeekBodyModel')
    expect(subjectPeekBodyModelSource).toContain('localPredicateLabel')
    expect(subjectPeekBodyModelSource).toContain('normalizeStructuredCellResourceValue')
    expect(subjectPeekBodyModelSource).toContain('displayStructuredFactValue')
    expect(subjectPeekBodyModelSource).not.toContain('useState')
    expect(subjectPeekBodyModelSource).not.toContain('useEffect')
    expect(subjectPeekShimSource).toMatch(/^export \* from '..\/features\/structured\/StructuredSubjectPeek'\n?$/)
  })

  it('keeps structured subject peek facts and source-linked targeting in a pure model module', () => {
    const previewSource = readFileSync(previewPath, 'utf8')
    const controllerSource = existsSync(subjectNavigationControllerPath)
      ? readFileSync(subjectNavigationControllerPath, 'utf8')
      : ''

    expect(existsSync(subjectPeekModelPath)).toBe(true)
    if (!existsSync(subjectPeekModelPath)) return

    const modelSource = readFileSync(subjectPeekModelPath, 'utf8')

    expect(controllerSource).toContain("from '../../domain/structured/structured-subject-peek'")
    expect(previewSource).not.toContain("from '../../domain/structured/structured-subject-peek'")
    expect(previewSource).not.toMatch(/\nfunction deriveSubjectPeekFacts\(/)
    expect(previewSource).not.toMatch(/\nfunction resolveStructuredSourceLinkedCardOpenTarget\(/)
    expect(previewSource).not.toContain('STRUCTURED_TITLE_PREDICATES')

    expect(modelSource).toContain('export function deriveStructuredSubjectPeekFacts')
    expect(modelSource).toContain('export function resolveStructuredSourceLinkedCardOpenTarget')
    expect(modelSource).not.toContain('useFilesStore')
  })

  it('keeps structured subject navigation, route, and scroll restoration in a controller', () => {
    expect(existsSync(subjectNavigationControllerPath)).toBe(true)
    expect(existsSync(subjectNavigationModelPath)).toBe(true)
    expect(existsSync(viewportControllerPath)).toBe(true)
    if (!existsSync(subjectNavigationControllerPath) || !existsSync(subjectNavigationModelPath) || !existsSync(viewportControllerPath)) return

    const previewSource = readFileSync(previewPath, 'utf8')
    const controllerSource = readFileSync(subjectNavigationControllerPath, 'utf8')
    const navigationModelSource = readFileSync(subjectNavigationModelPath, 'utf8')
    const viewportControllerSource = readFileSync(viewportControllerPath, 'utf8')

    expect(previewSource).toContain('useStructuredSubjectNavigationController')
    expect(previewSource).toContain('useStructuredViewportController')
    expect(previewSource).toContain('structuredViewport.chrome.viewport.ariaLabel')
    expect(previewSource).not.toContain('aria-label="Structured resource viewport"')
    expect(previewSource).not.toContain('createFilesStructuredSubjectRouteState')
    expect(previewSource).not.toContain('pushStructuredSubjectRoute')
    expect(previewSource).not.toContain('openStructuredSubjectResource')
    expect(previewSource).not.toContain('clearStructuredScrollRestoration')
    expect(previewSource).not.toContain('setSubjectPeek')
    expect(previewSource).not.toMatch(/\n  const subjectPeek = useState/)
    expect(previewSource).not.toMatch(/\n  const \[subjectPeek/)
    expect(previewSource).not.toMatch(/\n  const pushSubjectRoute\b/)
    expect(previewSource).not.toMatch(/\n  const navigateStructuredSubject\b/)
    expect(previewSource).not.toMatch(/\n  const openSubjectPeek\b/)
    expect(previewSource).not.toMatch(/\n  const openAlternativeViewSubject\b/)
    expect(previewSource).not.toMatch(/\n  const openPeekedSubjectResource\b/)
    expect(previewSource).not.toMatch(/\n  const openPeekedSource\b/)
    expect(previewSource).not.toContain('useRef')
    expect(previewSource).not.toContain('useEffect')
    expect(previewSource).not.toContain('lastStructuredScrollTopRef')
    expect(previewSource).not.toContain('structuredViewportRef')
    expect(previewSource).not.toContain('scrollLeft = 0')
    expect(previewSource).not.toContain('event.currentTarget.scrollTop')
    expect(controllerSource).toContain('export function useStructuredSubjectNavigationController')
    expect(controllerSource).toContain('createFilesStructuredSubjectRouteState')
    expect(controllerSource).toContain('pushStructuredSubjectRoute')
    expect(controllerSource).toContain('openStructuredSubjectResource')
    expect(controllerSource).toContain('clearStructuredScrollRestoration')
    expect(controllerSource).toContain('deriveStructuredSubjectPeekFacts')
    expect(controllerSource).toContain("from './structured-subject-navigation-model'")
    expect(controllerSource).toContain('projectStructuredAlternativeSubjectOpenRequest')
    expect(controllerSource).toContain('projectStructuredScrollRestorationTargetSignature')
    expect(controllerSource).toContain('resolveStructuredSamePodSourceResourceUri')
    expect(controllerSource).not.toContain('resolveStructuredSubjectOpenTarget')
    expect(controllerSource).not.toContain('resolveSamePodSourceResourceUri')
    expect(controllerSource).not.toContain('tableProjection.rows.map((row, index)')
    expect(controllerSource).not.toContain('StructuredProjectionTable')
    expect(controllerSource).not.toContain('StructuredSubjectPeekDrawer')
    expect(navigationModelSource).toContain('export function projectStructuredAlternativeSubjectOpenRequest')
    expect(navigationModelSource).toContain('export function projectStructuredScrollRestorationTargetSignature')
    expect(navigationModelSource).toContain('export function resolveStructuredSamePodSourceResourceUri')
    expect(navigationModelSource).toContain('resolveStructuredSubjectOpenTarget')
    expect(navigationModelSource).not.toContain('useState')
    expect(navigationModelSource).not.toContain('useEffect')
    expect(navigationModelSource).not.toContain('useFilesStore')
    expect(viewportControllerSource).toContain('export function useStructuredViewportController')
    expect(viewportControllerSource).toContain('projectStructuredViewportChrome')
    expect(viewportControllerSource).toContain('useRef')
    expect(viewportControllerSource).toContain('useEffect')
    expect(viewportControllerSource).toContain('scrollLeft = 0')
    expect(viewportControllerSource).not.toContain('createFilesStructuredSubjectRouteState')
    expect(viewportControllerSource).not.toContain('useFilesStore')
  })

  it('keeps the locked vocab registry preview out of the structured data table container', () => {
    const previewSource = readFileSync(previewPath, 'utf8')

    expect(existsSync(lockedVocabPath)).toBe(true)
    expect(existsSync(lockedVocabControllerPath)).toBe(true)
    expect(existsSync(lockedVocabPreviewModelPath)).toBe(true)
    expect(existsSync(lockedVocabRegistryTableControllerPath)).toBe(true)
    expect(existsSync(lockedVocabRegistryTableModelPath)).toBe(true)
    if (!existsSync(lockedVocabPath) || !existsSync(lockedVocabControllerPath) || !existsSync(lockedVocabPreviewModelPath) || !existsSync(lockedVocabRegistryTableControllerPath) || !existsSync(lockedVocabRegistryTableModelPath)) return

    const lockedVocabSource = readFileSync(lockedVocabPath, 'utf8')
    const lockedVocabControllerSource = readFileSync(lockedVocabControllerPath, 'utf8')
    const lockedVocabPreviewModelSource = readFileSync(lockedVocabPreviewModelPath, 'utf8')
    const lockedVocabRegistryTableControllerSource = readFileSync(lockedVocabRegistryTableControllerPath, 'utf8')
    const lockedVocabRegistryTableModelSource = readFileSync(lockedVocabRegistryTableModelPath, 'utf8')
    const lockedVocabShimSource = readFileSync(lockedVocabShimPath, 'utf8')

    expect(previewSource).not.toMatch(/\nexport function LockedVocabTablePreview\(/)
    expect(previewSource).not.toMatch(/\nfunction LockedVocabRegistryTable\(/)
    expect(previewSource).not.toContain('LOCKED_VOCAB_REGISTRY_COLUMNS')

    expect(lockedVocabSource).toMatch(/\nexport function LockedVocabTablePreview\(/)
    expect(lockedVocabSource).toMatch(/\nfunction LockedVocabRegistryTable\(/)
    expect(lockedVocabSource).toContain('useLockedVocabPreviewController')
    expect(lockedVocabSource).toContain('useLockedVocabRegistryTableController')
    expect(lockedVocabSource).not.toContain('useRawTextResource')
    expect(lockedVocabSource).not.toContain('useFilesRouteBridge')
    expect(lockedVocabSource).not.toContain('useFilesStore')
    expect(lockedVocabSource).not.toContain('useState')
    expect(lockedVocabSource).not.toContain('useMemo')
    expect(lockedVocabSource).not.toContain('LOCKED_VOCAB_REGISTRY_COLUMNS')
    expect(lockedVocabSource).not.toContain('LOCKED_VOCAB_REGISTRY_COPY')
    expect(lockedVocabSource).not.toContain('词表定义表')
    expect(lockedVocabSource).not.toContain('定义表只读；修改通过待确认提案进入审批。')
    expect(lockedVocabSource).toContain('lockedVocab.chrome.viewport.ariaLabel')
    expect(lockedVocabSource).toContain('lockedVocab.chrome.header.title')
    expect(lockedVocabSource).toContain('lockedVocab.chrome.header.countLabel')
    expect(lockedVocabSource).toContain('lockedVocab.chrome.header.readOnlyNote')
    expect(lockedVocabSource).toContain('lockedVocab.chrome.header.badge.label')
    expect(lockedVocabSource).not.toContain('placeholder="搜索定义"')
    expect(lockedVocabSource).not.toContain('没有匹配的定义')
    expect(lockedVocabSource).not.toContain("row[column.key] || '—'")
    expect(lockedVocabSource).toContain('table.chrome.searchField.placeholder')
    expect(lockedVocabSource).toContain('table.chrome.emptyState.label')
    expect(lockedVocabSource).toContain('table.chrome.fallbackCell.label')
    expect(lockedVocabSource).not.toContain('const filteredRows')
    expect(lockedVocabSource).not.toContain('filteredRows.length')
    expect(lockedVocabSource).not.toContain('projectionWarnings.length')
    expect(lockedVocabSource).toContain('hasFilteredRows')
    expect(lockedVocabSource).toContain('primaryProjectionWarning')
    expect(lockedVocabSource).not.toContain('pushStructuredSubjectRoute')
    expect(lockedVocabSource).not.toContain('createFilesStructuredSubjectRouteState')
    expect(lockedVocabSource).not.toContain('deriveStructuredSubjectPeekFacts')
    expect(lockedVocabSource).not.toContain('projectLockedVocabRegistryRows')
    expect(lockedVocabRegistryTableControllerSource).toContain('export function useLockedVocabRegistryTableController')
    expect(lockedVocabRegistryTableControllerSource).toContain("from './locked-vocab-registry-table-model'")
    expect(lockedVocabRegistryTableControllerSource).toContain('projectLockedVocabRegistryTableModel')
    expect(lockedVocabRegistryTableControllerSource).not.toContain('LOCKED_VOCAB_REGISTRY_COLUMNS')
    expect(lockedVocabRegistryTableControllerSource).not.toContain('rows.filter')
    expect(lockedVocabRegistryTableControllerSource).not.toContain('columns.some')
    expect(lockedVocabRegistryTableControllerSource).toContain('hasFilteredRows')
    expect(lockedVocabRegistryTableControllerSource).toContain('chrome')
    expect(lockedVocabRegistryTableControllerSource).not.toContain('LockedVocabTablePreview')
    expect(lockedVocabRegistryTableControllerSource).not.toContain('<table')
    expect(lockedVocabRegistryTableControllerSource).not.toContain('StructuredSubjectPeekDrawer')
    expect(lockedVocabRegistryTableModelSource).toContain('export const LOCKED_VOCAB_REGISTRY_COLUMNS')
    expect(lockedVocabRegistryTableModelSource).toContain('chrome')
    expect(lockedVocabRegistryTableModelSource).toContain('export function projectLockedVocabRegistryTableModel')
    expect(lockedVocabRegistryTableModelSource).toContain('rows.filter')
    expect(lockedVocabRegistryTableModelSource).toContain('columns.some')
    expect(lockedVocabRegistryTableModelSource).not.toContain('useState')
    expect(lockedVocabRegistryTableModelSource).not.toContain('useMemo')
    expect(lockedVocabControllerSource).toContain('export function useLockedVocabPreviewController')
    expect(lockedVocabControllerSource).toContain('useRawTextResource')
    expect(lockedVocabControllerSource).toContain('useFilesRouteBridge')
    expect(lockedVocabControllerSource).toContain('useFilesStore')
    expect(lockedVocabControllerSource).toContain('pushStructuredSubjectRoute')
    expect(lockedVocabControllerSource).toContain('projectLockedVocabPreviewChrome')
    expect(lockedVocabControllerSource).toContain('chrome')
    expect(lockedVocabControllerSource).toContain('createFilesStructuredSubjectRouteState')
    expect(lockedVocabControllerSource).toContain('deriveStructuredSubjectPeekFacts')
    expect(lockedVocabControllerSource).toContain('projectLockedVocabRegistryRows')
    expect(lockedVocabControllerSource).toContain('primaryProjectionWarning')
    expect(lockedVocabControllerSource).not.toContain('LockedVocabRegistryTable')
    expect(lockedVocabControllerSource).not.toContain('StructuredSubjectPeekDrawer')
    expect(lockedVocabPreviewModelSource).toContain('export function projectLockedVocabPreviewChrome')
    expect(lockedVocabPreviewModelSource).not.toContain('useState')
    expect(lockedVocabPreviewModelSource).not.toContain('useMemo')
    expect(lockedVocabSource).not.toContain('StructuredTablePreview')
    expect(lockedVocabShimSource).toMatch(/^export \* from '..\/features\/structured\/LockedVocabTablePreview'\n?$/)
  })

  it('keeps predicate definition drafting and the add-predicate menu out of the structured table container', () => {
    const previewSource = readFileSync(previewPath, 'utf8')
    const projectionTableSource = existsSync(projectionTablePath)
      ? readFileSync(projectionTablePath, 'utf8')
      : ''
    const projectionTableColumnsSource = existsSync(projectionTableColumnsPath)
      ? readFileSync(projectionTableColumnsPath, 'utf8')
      : ''
    const predicateColumnHeaderSource = existsSync(predicateColumnHeaderPath)
      ? readFileSync(predicateColumnHeaderPath, 'utf8')
      : ''
    const pendingPredicateColumnsSource = existsSync(pendingPredicateColumnsPath)
      ? readFileSync(pendingPredicateColumnsPath, 'utf8')
      : ''
    const pendingPredicateColumnsModelSource = existsSync(pendingPredicateColumnsModelPath)
      ? readFileSync(pendingPredicateColumnsModelPath, 'utf8')
      : ''
    const vocabProposalWorkflowControllerSource = existsSync(vocabProposalWorkflowControllerPath)
      ? readFileSync(vocabProposalWorkflowControllerPath, 'utf8')
      : ''
    const vocabProposalWorkflowModelSource = existsSync(vocabProposalWorkflowModelPath)
      ? readFileSync(vocabProposalWorkflowModelPath, 'utf8')
      : ''

    expect(existsSync(addPredicateMenuPath)).toBe(true)
    expect(existsSync(addPredicateMenuControllerPath)).toBe(true)
    expect(existsSync(addPredicateMenuModelPath)).toBe(true)
    expect(existsSync(projectionTableColumnsPath)).toBe(true)
    expect(existsSync(predicateColumnHeaderPath)).toBe(true)
    expect(existsSync(pendingPredicateColumnsPath)).toBe(true)
    expect(existsSync(pendingPredicateColumnsModelPath)).toBe(true)
    expect(existsSync(vocabProposalWorkflowControllerPath)).toBe(true)
    expect(existsSync(vocabProposalWorkflowModelPath)).toBe(true)
    expect(existsSync(predicateDraftPath)).toBe(true)
    if (!existsSync(addPredicateMenuPath) || !existsSync(addPredicateMenuControllerPath) || !existsSync(addPredicateMenuModelPath) || !existsSync(projectionTableColumnsPath) || !existsSync(predicateColumnHeaderPath) || !existsSync(pendingPredicateColumnsPath) || !existsSync(pendingPredicateColumnsModelPath) || !existsSync(vocabProposalWorkflowControllerPath) || !existsSync(vocabProposalWorkflowModelPath) || !existsSync(predicateDraftPath)) return

    const addMenuSource = readFileSync(addPredicateMenuPath, 'utf8')
    const addPredicateMenuControllerSource = readFileSync(addPredicateMenuControllerPath, 'utf8')
    const addPredicateMenuModelSource = readFileSync(addPredicateMenuModelPath, 'utf8')
    const draftSource = readFileSync(predicateDraftPath, 'utf8')

    expect(previewSource).not.toContain("from '../../domain/structured/structured-predicate-draft'")
    expect(projectionTableSource).toContain("from './StructuredProjectionTableColumns'")
    expect(projectionTableSource).not.toContain("from './StructuredPredicateColumnHeader'")
    expect(projectionTableSource).not.toContain("from './AddPredicateMenu'")
    expect(projectionTableColumnsSource).toContain("from './StructuredPredicateColumnHeader'")
    expect(projectionTableColumnsSource).not.toContain("from './AddPredicateMenu'")
    expect(predicateColumnHeaderSource).toContain("from './AddPredicateMenu'")
    expect(projectionTableSource).not.toContain("from '../structured-predicate-draft'")
    expect(pendingPredicateColumnsSource).not.toContain("from '../../domain/structured/structured-predicate-draft'")
    expect(pendingPredicateColumnsSource).toContain("from './structured-pending-predicate-columns-model'")
    expect(pendingPredicateColumnsModelSource).toContain("from '../../domain/structured/structured-predicate-draft'")
    expect(vocabProposalWorkflowControllerSource).not.toContain("from '../../domain/structured/structured-predicate-draft'")
    expect(vocabProposalWorkflowControllerSource).toContain("from './structured-vocab-proposal-workflow-model'")
    expect(vocabProposalWorkflowModelSource).toContain("from '../../domain/structured/structured-predicate-draft'")
    expect(previewSource).not.toMatch(/\nfunction AddPredicateMenu\(/)
    expect(previewSource).not.toMatch(/\ntype PredicateDefinitionDraft = /)
    expect(previewSource).not.toMatch(/\nfunction classUriFromDraft\(/)
    expect(previewSource).not.toMatch(/\nfunction predicateUriFromDraft\(/)
    expect(previewSource).not.toContain('PREDICATE_VALUE_TYPE_OPTIONS')

    expect(addMenuSource).toMatch(/\nexport function AddPredicateMenu\(/)
    expect(addMenuSource).toContain("from './useAddPredicateMenuController'")
    expect(addMenuSource).toContain('useAddPredicateMenuController')
    expect(addMenuSource).not.toContain('useState')
    expect(addMenuSource).not.toContain('useEffect')
    expect(addMenuSource).toContain('menu.chrome.trigger.ariaLabel')
    expect(addMenuSource).toContain('menu.chrome.trigger.label')
    expect(addMenuSource).toContain('menu.chrome.searchField.ariaLabel')
    expect(addMenuSource).toContain('menu.chrome.searchField.placeholder')
    expect(addMenuSource).toContain('menu.chrome.emptyState.label')
    expect(addMenuSource).toContain('row.selectAriaLabel')
    expect(addMenuSource).toContain('menu.chrome.createPanel.heading')
    expect(addMenuSource).toContain('menu.chrome.createPanel.description')
    expect(addMenuSource).toContain('menu.chrome.definitionByline.ariaLabel')
    expect(addMenuSource).toContain('menu.chrome.termSection.label')
    expect(addMenuSource).toContain('menu.chrome.localNameField.ariaLabel')
    expect(addMenuSource).toContain('menu.chrome.localNameField.placeholder')
    expect(addMenuSource).toContain('menu.chrome.labelField.ariaLabel')
    expect(addMenuSource).toContain('menu.chrome.labelField.placeholder')
    expect(addMenuSource).toContain('menu.chrome.valueSection.label')
    expect(addMenuSource).toContain('menu.chrome.valueTypes.ariaLabel')
    expect(addMenuSource).toContain('menu.chrome.valueTypes.optionAriaLabelPrefix')
    expect(addMenuSource).toContain('menu.chrome.enumOptionsField.ariaLabel')
    expect(addMenuSource).toContain('menu.chrome.enumOptionsField.placeholder')
    expect(addMenuSource).toContain('menu.chrome.descriptionField.ariaLabel')
    expect(addMenuSource).toContain('menu.chrome.descriptionField.placeholder')
    expect(addMenuSource).toContain('menu.definitionDetailsToggle.ariaLabel')
    expect(addMenuSource).toContain('menu.definitionDetailsToggle.expanded')
    expect(addMenuSource).toContain('menu.definitionDetailsToggle.label')
    expect(addMenuSource).toContain('menu.definitionDetailsToggle.indicator')
    expect(addMenuSource).toContain('menu.chrome.shapeFields.namespace.ariaLabel')
    expect(addMenuSource).toContain('menu.chrome.shapeFields.uri.placeholder')
    expect(addMenuSource).toContain('menu.chrome.shapeFields.classScope.placeholder')
    expect(addMenuSource).toContain('menu.chrome.shapeFields.required.label')
    expect(addMenuSource).toContain('menu.chrome.shapeFields.minCount.srLabel')
    expect(addMenuSource).toContain('menu.chrome.shapeFields.maxCount.placeholder')
    expect(addMenuSource).toContain('menu.chrome.shapeFields.editor.options')
    expect(addMenuSource).toContain('menu.chrome.submitButton.label')
    expect(addMenuSource).not.toContain('aria-label="+ predicate"')
    expect(addMenuSource).not.toContain('aria-label="选择或创建 predicate"')
    expect(addMenuSource).not.toContain('placeholder="选择已有 predicate 或创建"')
    expect(addMenuSource).not.toContain('没有匹配的 predicate')
    expect(addMenuSource).not.toContain('选择 predicate ${row.label}')
    expect(addMenuSource).not.toContain('aria-label="新建 predicate"')
    expect(addMenuSource).not.toContain('提交后以 * 参与当前表格')
    expect(addMenuSource).not.toContain('aria-label="predicate 定义"')
    expect(addMenuSource).not.toContain('aria-label="predicate term"')
    expect(addMenuSource).not.toContain('placeholder="summary"')
    expect(addMenuSource).not.toContain('aria-label="predicate 标签"')
    expect(addMenuSource).not.toContain('placeholder="Summary"')
    expect(addMenuSource).not.toContain('aria-label="predicate value types"')
    expect(addMenuSource).not.toContain('aria-label={`类型 ${option.value}`}')
    expect(addMenuSource).not.toContain('aria-label="predicate 枚举选项"')
    expect(addMenuSource).not.toContain('placeholder="Ready, Blocked"')
    expect(addMenuSource).not.toContain('aria-label="predicate 描述"')
    expect(addMenuSource).not.toContain('说明这个 predicate 的用途')
    expect(addMenuSource).not.toContain('收起 shape 和高级信息')
    expect(addMenuSource).not.toContain('展开 shape 和高级信息')
    expect(addMenuSource).not.toContain('aria-label="predicate namespace"')
    expect(addMenuSource).not.toContain('placeholder="udfs"')
    expect(addMenuSource).not.toContain('aria-label="predicate URI"')
    expect(addMenuSource).not.toContain('placeholder="https://example.com/vocab/summary"')
    expect(addMenuSource).not.toContain('aria-label="predicate class scope"')
    expect(addMenuSource).not.toContain('placeholder="udfs:Workspace"')
    expect(addMenuSource).not.toContain('aria-label="predicate 必填"')
    expect(addMenuSource).not.toContain('aria-label="predicate 最小数量"')
    expect(addMenuSource).not.toContain('placeholder="最小"')
    expect(addMenuSource).not.toContain('aria-label="predicate 最大数量"')
    expect(addMenuSource).not.toContain('placeholder="最大"')
    expect(addMenuSource).not.toContain('aria-label="predicate editor type"')
    expect(addMenuSource).not.toContain('<option value="input">input</option>')
    expect(addMenuSource).not.toContain('提交待确认 predicate *')
    expect(addMenuSource).not.toContain('createPredicateDefinitionDraft')
    expect(addMenuSource).not.toContain('predicateUriFromDraft')
    expect(addMenuSource).not.toContain('stripPredicateIriDelimiters')
    expect(addMenuSource).not.toContain('DEFAULT_PREDICATE_NAMESPACE')
    expect(addMenuSource).not.toContain('StructuredTablePreview')
    expect(addMenuSource).not.toContain('PREDICATE_VALUE_TYPE_OPTIONS')
    expect(addMenuSource).not.toContain('visibleExistingPredicates.length')
    expect(addMenuSource).not.toContain('predicateSearch.trim')
    expect(addMenuSource).not.toContain('menu.draft.type === option.value')
    expect(addMenuSource).not.toContain("menu.draft.type === 'enum'")
    expect(addMenuSource).toContain('createTriggerLabel')
    expect(addMenuSource).toContain('submitDisabled')
    expect(addMenuSource).not.toContain('disabled={!menu.resolvedUri}')
    expect(addMenuSource).toContain('uriPreview')
    expect(addMenuSource).not.toContain('menu.resolvedUri ?')
    expect(addMenuSource).not.toContain('URI 预览 · 填写 ns 和 term 后生成')
    expect(addMenuSource).toContain('valueTypeRows')
    expect(addMenuSource).toContain('showEnumOptionsEditor')
    expect(addMenuSource).toContain('hasVisibleExistingPredicates')
    expect(addPredicateMenuControllerSource).toContain('export function useAddPredicateMenuController')
    expect(addPredicateMenuControllerSource).toContain("from './structured-add-predicate-menu-model'")
    expect(addPredicateMenuControllerSource).toContain('createAddPredicateMenuState')
    expect(addPredicateMenuControllerSource).toContain('projectAddPredicateMenuClassScopeHydrated')
    expect(addPredicateMenuControllerSource).toContain('projectAddPredicateMenuCreateOpened')
    expect(addPredicateMenuControllerSource).toContain('projectAddPredicateMenuDefinitionDetailsToggled')
    expect(addPredicateMenuControllerSource).toContain('projectAddPredicateMenuPredicateSearchPatch')
    expect(addPredicateMenuControllerSource).toContain('projectAddPredicateMenuStateDraftPatch')
    expect(addPredicateMenuControllerSource).toContain('planAddPredicateMenuSubmitted')
    expect(addPredicateMenuControllerSource).toContain('projectAddPredicateMenuExistingPredicateRows')
    expect(addPredicateMenuControllerSource).toContain('projectAddPredicateMenuChrome')
    expect(addPredicateMenuControllerSource).toContain('projectAddPredicateMenuDefinitionDetailsToggle')
    expect(addPredicateMenuControllerSource).toContain('projectAddPredicateMenuCreateTriggerLabel')
    expect(addPredicateMenuControllerSource).toContain('projectAddPredicateMenuUriPreview')
    expect(addPredicateMenuControllerSource).toContain('projectAddPredicateMenuValueTypeRows')
    expect(addPredicateMenuControllerSource).toContain('shouldShowAddPredicateMenuEnumOptionsEditor')
    expect(addPredicateMenuControllerSource).toContain('canSubmitAddPredicateMenuDraft')
    expect(addPredicateMenuControllerSource).toMatch(/\n\s*const \[menuState, setMenuState\]/)
    expect(addPredicateMenuControllerSource).not.toMatch(/\n\s*const \[createOpen, setCreateOpen\]/)
    expect(addPredicateMenuControllerSource).not.toMatch(/\n\s*const \[definitionDetailsOpen, setDefinitionDetailsOpen\]/)
    expect(addPredicateMenuControllerSource).not.toMatch(/\n\s*const \[predicateSearch, setPredicateSearch\]/)
    expect(addPredicateMenuControllerSource).not.toMatch(/\n\s*const \[draft, setDraft\]/)
    expect(addPredicateMenuControllerSource).not.toContain('setDraft(createAddPredicateMenuDraft(classScope))')
    expect(addPredicateMenuControllerSource).not.toContain('setDefinitionDetailsOpen(false)')
    expect(addPredicateMenuControllerSource).not.toContain('setCreateOpen(false)')
    expect(addPredicateMenuControllerSource).not.toContain('{ ...current, ...patch }')
    expect(addPredicateMenuControllerSource).not.toContain('setDefinitionDetailsOpen((current) => !current)')
    expect(addPredicateMenuControllerSource).not.toContain('return { ...current, classScope }')
    expect(addPredicateMenuControllerSource).not.toContain('stripPredicateIriDelimiters')
    expect(addPredicateMenuControllerSource).not.toContain('DEFAULT_PREDICATE_NAMESPACE')
    expect(addPredicateMenuControllerSource).not.toContain('normalizedPredicateSearch')
    expect(addPredicateMenuControllerSource).not.toContain('definitionForPredicate')
    expect(addPredicateMenuControllerSource).not.toContain('curieMatch')
    expect(addPredicateMenuControllerSource).toContain('hasVisibleExistingPredicates')
    expect(addPredicateMenuControllerSource).not.toContain('DropdownMenu')
    expect(addPredicateMenuControllerSource).not.toContain('<input')
    expect(addPredicateMenuControllerSource).not.toContain('<button')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuExistingPredicateRows')
    expect(addPredicateMenuModelSource).toContain('export type AddPredicateMenuState')
    expect(addPredicateMenuModelSource).toContain('export function createAddPredicateMenuState')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuStateReset')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuClassScopeHydrated')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuPredicateSearchPatch')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuCreateOpened')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuStateDraftPatch')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuDefinitionDetailsToggled')
    expect(addPredicateMenuModelSource).toContain('export function planAddPredicateMenuSubmitted')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuChrome')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuDefinitionDetailsToggle')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuDefinitionDetailsOpenToggle')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuDraftClassScope')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuDraftPatch')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuDraftSeed')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuCreateTriggerLabel')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuUriPreview')
    expect(addPredicateMenuModelSource).toContain('export function projectAddPredicateMenuValueTypeRows')
    expect(addPredicateMenuModelSource).toContain('export function shouldShowAddPredicateMenuEnumOptionsEditor')
    expect(addPredicateMenuModelSource).toContain('export function canSubmitAddPredicateMenuDraft')
    expect(addPredicateMenuModelSource).toContain('createPredicateDefinitionDraft')
    expect(addPredicateMenuModelSource).toContain('predicateUriFromDraft')
    expect(addPredicateMenuModelSource).toContain('stripPredicateIriDelimiters')
    expect(addPredicateMenuModelSource).toContain('DEFAULT_PREDICATE_NAMESPACE')
    expect(addPredicateMenuModelSource).not.toContain('useState')
    expect(addPredicateMenuModelSource).not.toContain('useEffect')
    expect(addPredicateMenuModelSource).not.toContain('DropdownMenu')
    expect(draftSource).toContain('export type PredicateDefinitionDraft')
    expect(draftSource).toContain('export function predicateShapeFromDraft')
    expect(draftSource).not.toContain('useFilesStore')
  })

  it('keeps the TanStack projection table out of the structured preview container', () => {
    const previewSource = readFileSync(previewPath, 'utf8')

    expect(existsSync(projectionTablePath)).toBe(true)
    if (!existsSync(projectionTablePath)) return

    const projectionTableSource = readFileSync(projectionTablePath, 'utf8')
    const projectionTableColumnsSource = existsSync(projectionTableColumnsPath)
      ? readFileSync(projectionTableColumnsPath, 'utf8')
      : ''

    expect(previewSource).toContain("from './StructuredProjectionTable'")
    expect(previewSource).not.toMatch(/\nexport function StructuredProjectionTable\(/)
    expect(previewSource).not.toMatch(/\ntype StructuredProjectionTableRow = /)
    expect(previewSource).not.toContain('useReactTable')
    expect(previewSource).not.toContain('STRUCTURED_CELL_POPOVER_WIDTH')

    expect(projectionTableSource).toMatch(/\nexport function StructuredProjectionTable\(/)
    expect(projectionTableSource).toContain('useReactTable')
    expect(projectionTableSource).toContain('CompactTableShell')
    expect(projectionTableSource).toContain('buildStructuredProjectionTableColumns')
    expect(projectionTableSource).not.toContain('StructuredPredicateColumnHeader')
    expect(projectionTableColumnsSource).toContain('StructuredPredicateColumnHeader')
    expect(projectionTableSource).not.toContain('AddPredicateMenu')
    expect(projectionTableSource).not.toContain('StructuredTablePreview')
    expect(projectionTableSource).not.toContain('useFilesStore')
  })
})
