import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const previewPath = 'src/modules/files/features/structured/StructuredTablePreview.tsx'
const toolbarPath = 'src/modules/files/features/structured/StructuredResourceToolbar.tsx'
const toolbarModelPath = 'src/modules/files/features/structured/structured-resource-toolbar-model.ts'
const previewHeaderModelPath = 'src/modules/files/features/structured/structured-resource-preview-header-model.ts'
const classScopeMenuControllerPath = 'src/modules/files/features/structured/useStructuredClassScopeMenuController.ts'
const classScopeMenuModelPath = 'src/modules/files/features/structured/structured-class-scope-menu-model.ts'
const resourceViewBarPath = 'src/modules/files/ui/ResourceViewBar.tsx'
const toolbarShimPath = 'src/modules/files/components/StructuredResourceToolbar.tsx'

describe('StructuredResourceToolbar architecture boundary', () => {
  it('keeps structured byline tools out of the structured resource preview container', () => {
    const previewSource = readFileSync(previewPath, 'utf8')

    expect(existsSync(toolbarPath)).toBe(true)
    expect(existsSync(toolbarModelPath)).toBe(true)
    expect(existsSync(previewHeaderModelPath)).toBe(true)
    expect(existsSync(classScopeMenuControllerPath)).toBe(true)
    expect(existsSync(classScopeMenuModelPath)).toBe(true)
    expect(existsSync(resourceViewBarPath)).toBe(true)
    if (!existsSync(toolbarPath) || !existsSync(toolbarModelPath) || !existsSync(previewHeaderModelPath) || !existsSync(classScopeMenuControllerPath) || !existsSync(classScopeMenuModelPath) || !existsSync(resourceViewBarPath)) return

    const toolbarSource = readFileSync(toolbarPath, 'utf8')
    const toolbarModelSource = readFileSync(toolbarModelPath, 'utf8')
    const previewHeaderModelSource = readFileSync(previewHeaderModelPath, 'utf8')
    const classScopeMenuControllerSource = readFileSync(classScopeMenuControllerPath, 'utf8')
    const classScopeMenuModelSource = readFileSync(classScopeMenuModelPath, 'utf8')
    const resourceViewBarSource = readFileSync(resourceViewBarPath, 'utf8')
    const toolbarShimSource = readFileSync(toolbarShimPath, 'utf8')

    expect(previewSource).toContain("from './StructuredResourceToolbar'")
    expect(previewSource).toContain("from './structured-resource-preview-header-model'")
    expect(previewSource).toContain('projectStructuredResourcePreviewHeaderModel')
    expect(previewSource).not.toMatch(/\nfunction StructuredResourceToolbar\(/)
    expect(previewSource).not.toContain('aria-label="结构化表工具"')
    expect(previewSource).not.toContain('classCreateOpen')
    expect(previewSource).not.toContain('classDefinitionOpen')
    expect(previewSource).not.toContain('classDraftUri')
    expect(previewSource).not.toContain('ListFilter')
    expect(previewSource).not.toContain("from '../../domain/structured/structured-table-vocab'")
    expect(previewSource).not.toContain('localPredicateLabel')
    expect(previewSource).not.toContain('classDefinition?.label || pendingClassScopeProposal?.label')

    expect(toolbarSource).toMatch(/\nexport function StructuredResourceToolbar\(/)
    expect(toolbarSource).toContain('ariaLabel={toolbarModel.byline.ariaLabel}')
    expect(toolbarSource).toContain('aria-label={toolbarModel.structuredTools.ariaLabel}')
    expect(toolbarSource).toContain('data-control-placement="structured-byline"')
    expect(toolbarSource).toContain("from '../../ui/ResourceViewBar'")
    expect(toolbarSource).toContain('<ResourceViewBar')
    expect(toolbarSource).toContain('flex h-10 min-w-0 items-center gap-1 overflow-hidden border-b border-border/30')
    expect(toolbarSource).toContain('data-structured-toolbar-scroll="view-actions"')
    expect(toolbarSource).toContain('data-structured-toolbar-scroll="subject-tools"')
    expect(toolbarSource).toContain('order-1 flex min-w-0 items-center gap-0.5 overflow-x-auto')
    expect(toolbarSource).toContain('order-[3] ml-auto flex h-7 w-7')
    expect(toolbarSource).not.toContain('max-w-[72%]')
    expect(toolbarSource).toContain('DropdownMenu')
    expect(toolbarSource).toContain('ListFilter')
    expect(toolbarSource).toContain('Search')
    expect(toolbarSource).toContain('Tags')
    expect(toolbarSource).toContain("from './structured-resource-toolbar-model'")
    expect(toolbarSource).toContain('projectStructuredResourceToolbarModel')
    expect(toolbarSource).toContain("from './useStructuredClassScopeMenuController'")
    expect(toolbarSource).not.toContain("from '../../domain/structured/structured-table-vocab'")
    expect(toolbarSource).not.toContain('结构化资源信息')
    expect(toolbarSource).not.toContain('localPredicateLabel')
    expect(toolbarSource).not.toContain('function structuredSortToolLabel')
    expect(toolbarSource).not.toContain('visiblePendingClassProposals.map')
    expect(toolbarSource).not.toContain('const proposalLabel')
    expect(toolbarSource).not.toContain('打开 class 审批记录')
    expect(toolbarSource).not.toContain('放弃 class')
    expect(toolbarSource).not.toContain('审批记录已准备')
    expect(toolbarSource).not.toContain('提交待确认 class *')
    expect(toolbarSource).toContain('proposal.discardButtonLabel')
    expect(toolbarSource).not.toContain('当前 class')
    expect(toolbarSource).not.toContain('const hasActiveFilters =')
    expect(toolbarSource).not.toContain('schemaPredicateControls.length')
    expect(toolbarSource).not.toContain('VIEW_LABELS')
    expect(toolbarSource).not.toContain('Record<StructuredResourceViewMode, string>')
    expect(toolbarSource).not.toContain('activeViewTabs.map')
    expect(toolbarSource).not.toContain('extraViewOptions.map')
    expect(toolbarSource).not.toContain('viewMode === row.value')
    expect(toolbarSource).not.toContain('aria-label="+ 视图"')
    expect(toolbarSource).toContain('toolbarModel.extraViewTrigger.label')
    expect(toolbarSource).not.toContain('placeholder="搜索 subject"')
    expect(toolbarSource).not.toContain('aria-label="筛选"')
    expect(toolbarSource).not.toContain('aria-label="排序"')
    expect(toolbarSource).not.toContain('aria-label="隐藏 predicate"')
    expect(toolbarSource).not.toContain('predicate 类型')
    expect(toolbarSource).toContain('onShowNamespacesChange')
    expect(toolbarSource).toContain('onTogglePredicateVisibility')
    expect(toolbarSource).not.toContain('词表定义')
    expect(toolbarSource).not.toContain('classDefinition?.label')
    expect(toolbarSource).not.toContain('classDefinition?.uri')
    expect(toolbarSource).not.toContain('classDefinition?.description')
    expect(toolbarSource).not.toContain('classDefinition?.status')
    expect(toolbarSource).not.toContain("selectedClassName\n                          ?")
    expect(toolbarSource).not.toContain('No class selected')
    expect(toolbarSource).not.toContain('不同 class 不混排')
    expect(toolbarSource).not.toContain('先选择或创建 class')
    expect(toolbarSource).not.toContain('此视图只展示该 class')
    expect(toolbarSource).not.toContain("structuredSortKey ? 'text-primary'")
    expect(toolbarSource).not.toContain("structuredSortKey && structuredSortDirection === 'desc'")
    expect(toolbarSource).not.toContain(') : structuredSortKey ? (')
    expect(toolbarSource).not.toContain('{row.label} 升序')
    expect(toolbarSource).not.toContain('{row.label} 降序')
    expect(toolbarSource).not.toContain("onSort(row.sortKey, 'asc')")
    expect(toolbarSource).not.toContain("onSort(row.sortKey, 'desc')")
    expect(toolbarSource).not.toContain("showNamespaces ? '隐藏命名空间' : '显示命名空间'")
    expect(toolbarSource).not.toContain('onShowNamespacesChange(!showNamespaces)')
    expect(toolbarSource).not.toContain('namespaceSwitchChecked ?')
    expect(toolbarSource).not.toContain('namespaceSwitchChecked &&')
    expect(toolbarSource).not.toContain('predicateTypeFilters')
    expect(toolbarSource).not.toContain('vocabTermFilters')
    expect(toolbarSource).not.toContain("filter === 'all'")
    expect(toolbarSource).not.toContain("filter === 'relation'")
    expect(toolbarSource).not.toContain('`${filter} predicate`')
    expect(toolbarSource).not.toContain('全部词表定义')
    expect(toolbarSource).not.toContain('已定义 predicate')
    expect(toolbarSource).not.toContain('仅观察到 predicate')
    expect(toolbarSource).not.toContain('全部命名空间')
    expect(toolbarSource).not.toContain('有校验提醒的 subject')
    expect(toolbarSource).not.toContain('有待确认更改的 subject')
    expect(toolbarSource).not.toContain('有 Ingest 更新的 subject')
    expect(toolbarSource).not.toContain('checked={warningRowsOnly}')
    expect(toolbarSource).not.toContain('checked={pendingWritesOnly}')
    expect(toolbarSource).not.toContain('checked={sourceUpdatesOnly}')
    expect(toolbarSource).not.toContain('availablePredicateNamespaces.map')
    expect(toolbarSource).not.toContain("from 'react'")
    expect(toolbarSource).not.toContain('useState')
    expect(toolbarSource).not.toContain('useEffect')
    expect(toolbarSource).not.toContain('setClassDraftUri')
    expect(toolbarSource).not.toContain('setClassCreateOpen')
    expect(toolbarSource).not.toContain('setClassDefinitionOpen')
    expect(toolbarSource).not.toContain('const submitClassDraft')
    expect(toolbarSource).not.toContain('aria-label="创建 class"')
    expect(toolbarSource).not.toContain('<span>创建 class</span>')
    expect(toolbarSource).not.toContain("classCreateOpen ? '收起' : '展开'")
    expect(toolbarSource).not.toContain('class URI')
    expect(toolbarSource).not.toContain('新 class URI')
    expect(toolbarSource).not.toContain('placeholder="udfs:Note"')
    expect(toolbarSource).not.toContain('aria-label="定义"')
    expect(toolbarSource).not.toContain('<span>定义</span>')
    expect(toolbarSource).not.toContain("classDefinitionOpen ? '收起' : '查看'")
    expect(toolbarSource).not.toContain('useFilesStore')
    expect(toolbarSource).not.toContain('StructuredTablePreview')
    expect(classScopeMenuControllerSource).toContain('export function useStructuredClassScopeMenuController')
    expect(classScopeMenuControllerSource).toContain("from './structured-class-scope-menu-model'")
    expect(classScopeMenuControllerSource).toContain('createStructuredClassScopeMenuState')
    expect(classScopeMenuControllerSource).toContain('projectStructuredClassScopeMenuDraftUri')
    expect(classScopeMenuControllerSource).toContain('projectStructuredClassScopeMenuCreateOpenToggle')
    expect(classScopeMenuControllerSource).toContain('projectStructuredClassScopeMenuDefinitionOpenToggle')
    expect(classScopeMenuControllerSource).toContain('projectStructuredClassScopeMenuSubmittedDraft')
    expect(classScopeMenuControllerSource).toContain('useState')
    expect(classScopeMenuControllerSource).toContain('useEffect')
    expect(classScopeMenuControllerSource).toContain('submitClassDraft')
    expect(classScopeMenuControllerSource).not.toContain('setClassDraftUri')
    expect(classScopeMenuControllerSource).not.toContain('setClassCreateOpen')
    expect(classScopeMenuControllerSource).not.toContain('setClassDefinitionOpen')
    expect(classScopeMenuControllerSource).not.toContain('setClassCreateOpen((current) => !current)')
    expect(classScopeMenuControllerSource).not.toContain('setClassDefinitionOpen((current) => !current)')
    expect(classScopeMenuControllerSource).not.toContain('DropdownMenu')
    expect(classScopeMenuControllerSource).not.toContain('StructuredResourceToolbar')
    expect(classScopeMenuModelSource).toContain('export function createStructuredClassScopeMenuState')
    expect(classScopeMenuModelSource).toContain('export function projectStructuredClassScopeMenuDraftUri')
    expect(classScopeMenuModelSource).toContain('export function projectStructuredClassScopeMenuCreateOpenToggle')
    expect(classScopeMenuModelSource).toContain('export function projectStructuredClassScopeMenuDefinitionOpenToggle')
    expect(classScopeMenuModelSource).toContain('export function projectStructuredClassScopeMenuSubmittedDraft')
    expect(classScopeMenuModelSource).not.toContain('useState')
    expect(classScopeMenuModelSource).not.toContain('useEffect')
    expect(toolbarModelSource).toContain('export function projectStructuredResourceToolbarModel')
    expect(toolbarModelSource).toContain("from '../../domain/structured/structured-table-vocab'")
    expect(toolbarModelSource).toContain('byline')
    expect(toolbarModelSource).toContain('showSortTool')
    expect(toolbarModelSource).toContain('sortTool')
    expect(toolbarModelSource).toContain('sortOptionRows')
    expect(toolbarModelSource).toContain('showNamespaceSwitch')
    expect(toolbarModelSource).toContain('namespaceSwitch')
    expect(toolbarModelSource).toContain('showPredicateVisibilityTool')
    expect(toolbarModelSource).toContain('activeViewTabRows')
    expect(toolbarModelSource).toContain('structuredTools')
    expect(toolbarModelSource).toContain('classScopeMenu')
    expect(toolbarModelSource).toContain('filterTool')
    expect(toolbarModelSource).toContain('predicateVisibilityTool')
    expect(toolbarModelSource).toContain('classCreateControl')
    expect(toolbarModelSource).toContain('classDefinitionControl')
    expect(toolbarModelSource).toContain('discardButtonLabel')
    expect(toolbarModelSource).toContain('extraViewOptionRows')
    expect(toolbarModelSource).toContain('extraViewTrigger')
    expect(toolbarModelSource).toContain('classDefinitionPanel')
    expect(toolbarModelSource).toContain('predicateTypeFilterRows')
    expect(toolbarModelSource).toContain('vocabTermFilterRows')
    expect(toolbarModelSource).toContain('namespaceFilterRows')
    expect(toolbarModelSource).toContain('filterSectionLabels')
    expect(toolbarModelSource).toContain('searchField')
    expect(toolbarModelSource).toContain('subjectFilterRows')
    expect(toolbarModelSource).not.toContain('<DropdownMenu')
    expect(toolbarModelSource).not.toContain('<Input')
    expect(resourceViewBarSource).toContain('export function ResourceViewBar')
    expect(resourceViewBarSource).not.toContain('@inrupt')
    expect(resourceViewBarSource).not.toContain('rdf')
    expect(resourceViewBarSource).not.toContain('pod')
    expect(previewHeaderModelSource).toContain('export function projectStructuredResourcePreviewHeaderModel')
    expect(previewHeaderModelSource).toContain("from '../../domain/structured/structured-table-vocab'")
    expect(previewHeaderModelSource).not.toContain('<StructuredResourceToolbar')
    expect(previewHeaderModelSource).not.toContain('<DropdownMenu')
    expect(toolbarShimSource).toMatch(/^export \* from '..\/features\/structured\/StructuredResourceToolbar'\n?$/)
  })
})
