import {
  XPOD_AI,
  XPOD_CREDENTIAL,
  aiConfigModelRef,
  aiConfigProviderRef,
  aiModelTable,
  aiProviderTable,
  buildAIConfigMutationPlan,
  buildAIConfigProviderStateMap,
  buildWatchThreadMetadata,
  buildWatchTranscriptMessages,
  credentialTable,
  ContactType,
  extractChatIdFromChatRef,
  extractThreadIdFromThreadRef,
  agentTable,
  approvalResource,
  auditResource,
  applySolidComunicaPatches,
  chatTable,
  contactTable,
  drizzle,
  eq,
  getAIConfigProviderFamilyIds,
  getAIConfigProviderMetadata,
  getDefaultAIConfigCredentialId,
  getBuiltinModels as getSharedBuiltinModels,
  grantResource,
  inboxNotificationTable,
  initSolidTables,
  solidSchema,
  messageTable,
  sessionTable,
  normalizeAIConfigProviderId,
  normalizeAIConfigModelId,
  normalizeAIConfigResourceId,
  sameAIConfigProviderFamily,
  selectAIConfigCredential,
  sessionRepository,
  threadTable,
  type ApprovalInsert,
  type ApprovalRow,
  type AuditInsert,
  type AuditRow,
  type AIConfigModel,
  type AIConfigProviderState,
  type AIModelRow,
  type AIProviderRow,
  type CredentialRow,
  type GrantInsert,
  type GrantRow,
  type InboxNotificationInsert,
  type ChatInsert,
  type MessageRow,
  type MessageInsert,
  type ModelMetadata,
  type SessionInsert,
  type SessionRow,
  type SessionStatus,
  type SessionType,
  type SolidDatabase,
  type ThreadInsert,
  type ThreadRow,
  type WatchEventLogEntry,
  type WatchSessionRecord,
} from '@undefineds.co/models'

export {
  ContactType,
  extractChatIdFromChatRef,
  extractThreadIdFromThreadRef,
  agentTable,
  approvalResource,
  auditResource,
  applySolidComunicaPatches,
  aiConfigModelRef,
  aiConfigProviderRef,
  aiModelTable,
  aiProviderTable,
  buildAIConfigMutationPlan,
  buildAIConfigProviderStateMap,
  buildWatchThreadMetadata,
  buildWatchTranscriptMessages,
  chatTable,
  contactTable,
  credentialTable,
  drizzle,
  eq,
  getAIConfigProviderFamilyIds,
  getAIConfigProviderMetadata,
  getDefaultAIConfigCredentialId,
  grantResource,
  inboxNotificationTable,
  solidSchema,
  initSolidTables,
  messageTable,
  sessionTable,
  normalizeAIConfigProviderId,
  normalizeAIConfigModelId,
  normalizeAIConfigResourceId,
  sameAIConfigProviderFamily,
  selectAIConfigCredential,
  sessionRepository,
  threadTable,
  XPOD_AI,
  XPOD_CREDENTIAL,
}
export type {
  ApprovalInsert,
  ApprovalRow,
  AuditInsert,
  AuditRow,
  AIConfigModel,
  AIConfigProviderState,
  AIModelRow,
  AIProviderRow,
  ChatInsert,
  CredentialRow,
  GrantInsert,
  GrantRow,
  InboxNotificationInsert,
  MessageInsert,
  MessageRow,
  ModelMetadata,
  SessionInsert,
  SessionRow,
  SessionStatus,
  SessionType,
  SolidDatabase,
  ThreadInsert,
  ThreadRow,
  WatchEventLogEntry,
  WatchSessionRecord,
}

export function getBuiltinModels(): ModelMetadata[] {
  return getSharedBuiltinModels()
}
