import {
  XPOD_AI,
  XPOD_CREDENTIAL,
  aiConfigModelUri,
  aiConfigProviderUri,
  aiModelTable,
  aiProviderTable,
  buildAIConfigMutationPlan,
  buildAIConfigProviderStateMap,
  buildWatchThreadMetadata,
  buildWatchTranscriptMessages,
  credentialTable,
  ContactType,
  agentTable,
  chatTable,
  contactTable,
  drizzle,
  eq,
  getAIConfigProviderFamilyIds,
  getAIConfigProviderMetadata,
  getDefaultAIConfigCredentialId,
  getBuiltinModels as getSharedBuiltinModels,
  findPodRowByStorageId,
  initSolidTables,
  whereByPodStorageId,
  solidSchema,
  messageTable,
  sessionTable,
  normalizeAIConfigProviderId,
  normalizeAIConfigResourceId,
  sameAIConfigProviderFamily,
  sessionRepository,
  threadTable,
  type AIConfigModel,
  type AIConfigProviderState,
  type AIModelRow,
  type AIProviderRow,
  type CredentialRow,
  type ChatInsert,
  type MessageRow,
  type MessageInsert,
  type ModelMetadata,
  type SessionInsert,
  type SessionRow,
  type SessionStatus,
  type SessionType,
  type SolidDatabase,
  type ThreadInsert,
  type ThreadRow,
  type WatchEventLogEntry,
  type WatchSessionRecord,
} from '@undefineds.co/models'

export {
  ContactType,
  agentTable,
  aiConfigModelUri,
  aiConfigProviderUri,
  aiModelTable,
  aiProviderTable,
  buildAIConfigMutationPlan,
  buildAIConfigProviderStateMap,
  buildWatchThreadMetadata,
  buildWatchTranscriptMessages,
  chatTable,
  contactTable,
  credentialTable,
  drizzle,
  eq,
  getAIConfigProviderFamilyIds,
  getAIConfigProviderMetadata,
  getDefaultAIConfigCredentialId,
  findPodRowByStorageId,
  solidSchema,
  initSolidTables,
  whereByPodStorageId,
  messageTable,
  sessionTable,
  normalizeAIConfigProviderId,
  normalizeAIConfigResourceId,
  sameAIConfigProviderFamily,
  sessionRepository,
  threadTable,
  XPOD_AI,
  XPOD_CREDENTIAL,
}
export type {
  AIConfigModel,
  AIConfigProviderState,
  AIModelRow,
  AIProviderRow,
  ChatInsert,
  CredentialRow,
  MessageInsert,
  MessageRow,
  ModelMetadata,
  SessionInsert,
  SessionRow,
  SessionStatus,
  SessionType,
  SolidDatabase,
  ThreadInsert,
  ThreadRow,
  WatchEventLogEntry,
  WatchSessionRecord,
}

export function getBuiltinModels(): ModelMetadata[] {
  return getSharedBuiltinModels()
}
