import {
  XPOD_AI,
  XPOD_CREDENTIAL,
  aiConfigModelUri,
  aiConfigProviderUri,
  aiModelTable,
  aiProviderTable,
  buildAIConfigMutationPlan,
  buildAIConfigProviderStateMap,
  credentialTable,
  ContactType,
  agentTable,
  chatTable,
  contactTable,
  drizzle,
  eq,
  getAIConfigProviderFamilyIds,
  getAIConfigProviderMetadata,
  getDefaultAIConfigCredentialId,
  getBuiltinModels as getSharedBuiltinModels,
  linxSchema,
  messageTable,
  normalizeAIConfigProviderId,
  normalizeAIConfigResourceId,
  sameAIConfigProviderFamily,
  threadTable,
  type AIConfigModel,
  type AIConfigProviderState,
  type AIModelRow,
  type AIProviderRow,
  type CredentialRow,
  type MessageRow,
  type ModelMetadata,
  type SolidDatabase,
  type ThreadRow,
} from '@linx/models'

export {
  ContactType,
  agentTable,
  aiConfigModelUri,
  aiConfigProviderUri,
  aiModelTable,
  aiProviderTable,
  buildAIConfigMutationPlan,
  buildAIConfigProviderStateMap,
  chatTable,
  contactTable,
  credentialTable,
  drizzle,
  eq,
  getAIConfigProviderFamilyIds,
  getAIConfigProviderMetadata,
  getDefaultAIConfigCredentialId,
  linxSchema,
  messageTable,
  normalizeAIConfigProviderId,
  normalizeAIConfigResourceId,
  sameAIConfigProviderFamily,
  threadTable,
  XPOD_AI,
  XPOD_CREDENTIAL,
}
export type {
  AIConfigModel,
  AIConfigProviderState,
  AIModelRow,
  AIProviderRow,
  CredentialRow,
  MessageRow,
  ModelMetadata,
  SolidDatabase,
  ThreadRow,
}

export function getBuiltinModels(): ModelMetadata[] {
  return getSharedBuiltinModels()
}
