import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const LINX_THEME = {
  $schema: 'https://raw.githubusercontent.com/badlogic/pi-mono/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json',
  name: 'linx',
  vars: {
    cyan: '#6DB9C8',
    blue: '#6F7FA8',
    green: '#b5bd68',
    red: '#cc6666',
    yellow: '#ffff00',
    gray: '#808080',
    dimGray: '#666666',
    darkGray: '#505050',
    accent: '#8B7AA8',
    selectedBg: '#2A2633',
    userMsgBg: '#4F3F68',
    toolPendingBg: '#282832',
    toolSuccessBg: '#283228',
    toolErrorBg: '#3c2828',
    customMsgBg: '#292631',
  },
  colors: {
    accent: 'accent',
    border: 'blue',
    borderAccent: 'cyan',
    borderMuted: 'darkGray',
    success: 'green',
    error: 'red',
    warning: 'yellow',
    muted: 'gray',
    dim: 'dimGray',
    text: '',
    thinkingText: 'gray',
    selectedBg: 'selectedBg',
    userMessageBg: 'userMsgBg',
    userMessageText: '#FFFFFF',
    customMessageBg: 'customMsgBg',
    customMessageText: '',
    customMessageLabel: '#8B7AA8',
    toolPendingBg: 'toolPendingBg',
    toolSuccessBg: 'toolSuccessBg',
    toolErrorBg: 'toolErrorBg',
    toolTitle: '',
    toolOutput: 'gray',
    mdHeading: '#f0c674',
    mdLink: '#81a2be',
    mdLinkUrl: 'dimGray',
    mdCode: 'accent',
    mdCodeBlock: 'green',
    mdCodeBlockBorder: 'gray',
    mdQuote: 'gray',
    mdQuoteBorder: 'gray',
    mdHr: 'gray',
    mdListBullet: 'accent',
    toolDiffAdded: 'green',
    toolDiffRemoved: 'red',
    toolDiffContext: 'gray',
    syntaxComment: '#6A9955',
    syntaxKeyword: '#569CD6',
    syntaxFunction: '#DCDCAA',
    syntaxVariable: '#9CDCFE',
    syntaxString: '#CE9178',
    syntaxNumber: '#B5CEA8',
    syntaxType: '#4EC9B0',
    syntaxOperator: '#D4D4D4',
    syntaxPunctuation: '#D4D4D4',
    thinkingOff: 'darkGray',
    thinkingMinimal: '#6e6e6e',
    thinkingLow: '#5f87af',
    thinkingMedium: '#81a2be',
    thinkingHigh: '#b294bb',
    thinkingXhigh: '#d183e8',
    bashMode: 'green',
  },
}

export function ensureLinxPiTheme(agentDir: string): string {
  const themesDir = join(agentDir, 'themes')
  mkdirSync(themesDir, { recursive: true })
  const themePath = join(themesDir, 'linx.json')
  writeFileSync(themePath, `${JSON.stringify(LINX_THEME, null, 2)}\n`)
  return themePath
}
