const XPOD_ACCOUNT_PATH = '/.account/account/'
const XPOD_CONSENT_PATH = '/.account/oidc/consent/'
const XPOD_PASSWORD_LOGIN_PATH = '/.account/login/password/'
const XPOD_PASSWORD_REGISTER_PATH = '/.account/login/password/register/'
const XPOD_PICK_WEBID_PATH = '/.account/oidc/pick-webid/'
const EMBEDDED_QUERY_KEY = 'embedded'
const EMBEDDED_QUERY_VALUE = '1'
const INSTALL_FLAG = '__LINX_XPOD_AUTH_ENHANCER__'
const PENDING_POD_KEY = 'linx:xpod:pending-pod-creation'
const PENDING_USERNAME_KEY = 'linx:xpod:pending-username'
const SUBMITTED_USERNAME_KEY = 'linx:xpod:submitted-username'

export interface ScriptInjectionTarget {
  getURL(): string
  executeJavaScript(code: string, userGesture?: boolean): Promise<unknown>
}

export function normalizeXpodPathname(pathname: string): string {
  if (!pathname) {
    return '/'
  }

  return pathname.endsWith('/') ? pathname : `${pathname}/`
}

export function isXpodAccountPageUrl(url: string): boolean {
  try {
    return normalizeXpodPathname(new URL(url).pathname) === XPOD_ACCOUNT_PATH
  } catch {
    return false
  }
}

export function isXpodConsentPageUrl(url: string): boolean {
  try {
    return normalizeXpodPathname(new URL(url).pathname) === XPOD_CONSENT_PATH
  } catch {
    return false
  }
}

export function isXpodPasswordRegisterPageUrl(url: string): boolean {
  try {
    return normalizeXpodPathname(new URL(url).pathname) === XPOD_PASSWORD_REGISTER_PATH
  } catch {
    return false
  }
}

export function isXpodPasswordLoginPageUrl(url: string): boolean {
  try {
    return normalizeXpodPathname(new URL(url).pathname) === XPOD_PASSWORD_LOGIN_PATH
  } catch {
    return false
  }
}

export function isXpodAuthPageUrl(url: string): boolean {
  return (
    isXpodAccountPageUrl(url)
    || isXpodConsentPageUrl(url)
    || isXpodPasswordLoginPageUrl(url)
    || isXpodPasswordRegisterPageUrl(url)
  )
}

export function addEmbeddedAuthQuery(url: string): string {
  try {
    const parsed = new URL(url)
    if (!isXpodAuthPageUrl(parsed.toString())) {
      return url
    }

    if (!parsed.searchParams.has(EMBEDDED_QUERY_KEY)) {
      parsed.searchParams.set(EMBEDDED_QUERY_KEY, EMBEDDED_QUERY_VALUE)
    }

    return parsed.toString()
  } catch {
    return url
  }
}

export function buildXpodAuthEnhancerScript(): string {
  return [
    '(() => {',
    `  const INSTALL_FLAG = ${JSON.stringify(INSTALL_FLAG)};`,
    '  if (globalThis[INSTALL_FLAG]) {',
    "    return 'already-installed';",
    '  }',
    '  globalThis[INSTALL_FLAG] = true;',
    `  const ACCOUNT_PATH = ${JSON.stringify(XPOD_ACCOUNT_PATH)};`,
    `  const CONSENT_PATH = ${JSON.stringify(XPOD_CONSENT_PATH)};`,
    `  const LOGIN_PATH = ${JSON.stringify(XPOD_PASSWORD_LOGIN_PATH)};`,
    `  const REGISTER_PATH = ${JSON.stringify(XPOD_PASSWORD_REGISTER_PATH)};`,
    `  const PICK_WEBID_PATH = ${JSON.stringify(XPOD_PICK_WEBID_PATH)};`,
    `  const PENDING_POD_KEY = ${JSON.stringify(PENDING_POD_KEY)};`,
    `  const PENDING_USERNAME_KEY = ${JSON.stringify(PENDING_USERNAME_KEY)};`,
    `  const SUBMITTED_USERNAME_KEY = ${JSON.stringify(SUBMITTED_USERNAME_KEY)};`,
    '  const PENDING_TTL_MS = 120000;',
    '  const POLL_INTERVAL_MS = 500;',
    '  const ACCOUNT_WAIT_MS = 15000;',
    '  const CONSENT_WAIT_MS = 20000;',
    '  const state = {',
    '    pendingConsentNavigationUrl: null,',
    '    consentPolling: false,',
    '    usernameCheckTimer: null,',
    '    usernameCheckSerial: 0,',
    '    registerSubmitUsername: null,',
    '  };',
    '  const wait = (ms) => new Promise((resolve) => window.setTimeout(resolve, ms));',
    '  const nativePushState = window.history.pushState.bind(window.history);',
    '  const nativeReplaceState = window.history.replaceState.bind(window.history);',
    '  const nativeFetch = window.fetch.bind(window);',
    '  const normalizePathname = (pathname) => {',
    "    if (!pathname) return '/';",
    "    return pathname.endsWith('/') ? pathname : `${pathname}/`;",
    '  };',
    '  const currentPathname = () => normalizePathname(window.location.pathname);',
    '  const normalizeUsername = (value) => value.trim().toLowerCase();',
    '  const isValidUsername = (value) => /^[a-z0-9](?:[a-z0-9-]{1,61}[a-z0-9])$/.test(value);',
    '  const getProvisionCode = () => {',
    '    const raw = window.sessionStorage.getItem("provisionCode");',
    '    return typeof raw === "string" && raw.trim() ? raw.trim() : null;',
    '  };',
    '  const shouldAttachProvisionCode = (resource, init) => {',
    '    if (!getProvisionCode()) return false;',
    '    if (currentPathname() !== ACCOUNT_PATH) return false;',
    '    const method = String(init?.method || (resource instanceof Request ? resource.method : "GET")).toUpperCase();',
    '    if (method !== "POST") return false;',
    '    try {',
    '      const target = resource instanceof Request ? resource.url : String(resource);',
    '      const parsed = new URL(target, window.location.href);',
    '      return parsed.origin === window.location.origin;',
    '    } catch {',
    '      return false;',
    '    }',
    '  };',
    '  const attachProvisionCodeToPodCreate = (resource, init) => {',
    '    if (!shouldAttachProvisionCode(resource, init)) return { resource, init };',
    '    const provisionCode = getProvisionCode();',
    '    const body = init?.body ?? (resource instanceof Request ? resource.body : null);',
    '    if (typeof body !== "string" || !body.trim().startsWith("{")) return { resource, init };',
    '    try {',
    '      const payload = JSON.parse(body);',
    '      if (!payload || typeof payload !== "object" || !("name" in payload)) return { resource, init };',
    '      payload.settings = { ...(payload.settings || {}), provisionCode };',
    '      return {',
    '        resource,',
    '        init: {',
    '          ...(init || {}),',
    '          method: init?.method || (resource instanceof Request ? resource.method : "POST"),',
    '          headers: init?.headers || (resource instanceof Request ? resource.headers : undefined),',
    '          body: JSON.stringify(payload),',
    '        },',
    '      };',
    '    } catch {',
    '      return { resource, init };',
    '    }',
    '  };',
    '  const getPendingUsername = () => {',
    '    const raw = window.sessionStorage.getItem(PENDING_USERNAME_KEY);',
    '    return typeof raw === "string" && raw.trim() ? raw.trim() : null;',
    '  };',
    '  const setPendingUsername = (value) => {',
    '    if (!value) {',
    '      window.sessionStorage.removeItem(PENDING_USERNAME_KEY);',
    '      return;',
    '    }',
    '    window.sessionStorage.setItem(PENDING_USERNAME_KEY, value);',
    '  };',
    '  const clearPendingUsername = () => {',
    '    window.sessionStorage.removeItem(PENDING_USERNAME_KEY);',
    '  };',
    '  const setNativeInputValue = (input, value) => {',
    '    if (!(input instanceof HTMLInputElement)) return;',
    '    const descriptor = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, "value");',
    '    descriptor?.set?.call(input, value);',
    '    input.dispatchEvent(new Event("input", { bubbles: true }));',
    '    input.dispatchEvent(new Event("change", { bubbles: true }));',
    '  };',
    '  const getPendingTimestamp = () => {',
    '    const raw = window.sessionStorage.getItem(PENDING_POD_KEY);',
    '    if (!raw) return null;',
    '    const value = Number(raw);',
    '    return Number.isFinite(value) ? value : null;',
    '  };',
    '  const clearPendingPodCreation = () => {',
    '    window.sessionStorage.removeItem(PENDING_POD_KEY);',
    '  };',
    '  const hasPendingPodCreation = () => {',
    '    const timestamp = getPendingTimestamp();',
    '    if (!timestamp) return false;',
    '    if (Date.now() - timestamp > PENDING_TTL_MS) {',
    '      clearPendingPodCreation();',
    '      return false;',
    '    }',
    '    return true;',
    '  };',
    '  const markPendingPodCreation = () => {',
    '    window.sessionStorage.setItem(PENDING_POD_KEY, String(Date.now()));',
    '  };',
    '  const getPendingConsentLink = () => {',
    '    const consentLink = Array.from(document.querySelectorAll("a")).find((link) => {',
    '      if (!(link instanceof HTMLAnchorElement)) return false;',
    '      try {',
    '        return normalizePathname(new URL(link.href, window.location.href).pathname) === CONSENT_PATH;',
    '      } catch {',
    '        return false;',
    '      }',
    '    });',
    '    if (consentLink instanceof HTMLAnchorElement) {',
    '      return consentLink;',
    '    }',
    '    return Array.from(document.querySelectorAll("button")).find((button) =>',
    '      button instanceof HTMLButtonElement',
    '      && /continue/i.test((button.textContent || "").trim()),',
    '    ) || null;',
    '  };',
    '  const getAccountPodElements = () => {',
    '    const addButton = Array.from(document.querySelectorAll("button")).find((button) =>',
    '      (button.textContent || "").trim() === "Add Pod",',
    '    );',
    '    const form = Array.from(document.querySelectorAll("form")).find((node) =>',
    '      node instanceof HTMLFormElement && node.querySelector(\'input[placeholder="my-pod"]\'),',
    '    );',
    '    const nameInput = form instanceof HTMLFormElement',
    '      ? form.querySelector(\'input[placeholder="my-pod"]\')',
    '      : null;',
    '    const emptyState = Array.from(document.querySelectorAll("p")).find((node) =>',
    '      (node.textContent || "").includes("No Pods found. Create one to get started."),',
    '    );',
    '    return { addButton, form, nameInput, emptyState, continueLink: getPendingConsentLink() };',
    '  };',
    '  const cleanupAccountPodHelperText = () => {',
    '    const { form } = getAccountPodElements();',
    '    if (!(form instanceof HTMLFormElement)) {',
    '      return;',
    '    }',
    '    for (const paragraph of Array.from(form.querySelectorAll("p"))) {',
    '      const text = (paragraph.textContent || "").trim();',
    '      if (!text) {',
    '        continue;',
    '      }',
    '      if (text.includes("/profile/card#me") || text.includes("WebID")) {',
    '        paragraph.remove();',
    '      }',
    '    }',
    '  };',
    '  const fetchWebIds = async () => {',
    '    try {',
    '      const response = await window.fetch(PICK_WEBID_PATH, {',
    '        headers: { Accept: "application/json" },',
    '        credentials: "include",',
    '      });',
    '      if (!response.ok) return [];',
    '      const payload = await response.json().catch(() => ({}));',
    '      if (!Array.isArray(payload.webIds)) return [];',
    '      return payload.webIds.filter((value) => typeof value === "string" && value.length > 0);',
    '    } catch (error) {',
    '      console.warn("[LinX] Failed to query WebIDs during auth enhancement:", error);',
    '      return [];',
    '    }',
    '  };',
    '  const waitForWebIds = async (timeoutMs) => {',
    '    const deadline = Date.now() + timeoutMs;',
    '    while (Date.now() < deadline) {',
    '      const webIds = await fetchWebIds();',
    '      if (webIds.length > 0) return webIds;',
    '      await wait(POLL_INTERVAL_MS);',
    '    }',
    '    return [];',
    '  };',
    '  const navigateWithinSpa = (targetUrl) => {',
    '    nativePushState({}, "", targetUrl);',
    '    window.dispatchEvent(new PopStateEvent("popstate"));',
    '  };',
    '  const isRegisterView = () => {',
    '    if (currentPathname() === REGISTER_PATH) {',
    '      return true;',
    '    }',
    '    if (currentPathname() !== LOGIN_PATH) {',
    '      return false;',
    '    }',
    '    const form = document.querySelector("form");',
    '    if (!(form instanceof HTMLFormElement)) {',
    '      return false;',
    '    }',
    '    const hasConfirmPassword = form.querySelector(\'input[name="confirmPassword"]\') instanceof HTMLInputElement;',
    '    const submitButton = Array.from(form.querySelectorAll(\'button[type="submit"], button\')).find((button) =>',
    '      /(sign up|create account)/i.test((button.textContent || "").trim()),',
    '    );',
    '    const title = Array.from(document.querySelectorAll("h1, h2")).find((node) =>',
    '      /create account/i.test((node.textContent || "").trim()),',
    '    );',
    '    return hasConfirmPassword || submitButton instanceof HTMLButtonElement || title instanceof HTMLElement;',
    '  };',
    '  const isCreatePodForm = (form) => {',
    '    if (!(form instanceof HTMLFormElement)) return false;',
    '    const nameInput = form.querySelector(\'input[placeholder="my-pod"]\');',
    '    if (!(nameInput instanceof HTMLInputElement) || !nameInput.value.trim()) return false;',
    '    return Array.from(form.querySelectorAll("button")).some((button) => /create/i.test(button.textContent || ""));',
    '  };',
    '  const getRegisterForm = () => {',
    '    const form = document.querySelector("form");',
    '    return form instanceof HTMLFormElement ? form : null;',
    '  };',
    '  const getRegisterUsernameInput = () => {',
    '    const form = getRegisterForm();',
    '    if (!(form instanceof HTMLFormElement)) {',
    '      return null;',
    '    }',
    '    const input = form.querySelector(\'input[name="username"]\');',
    '    return input instanceof HTMLInputElement ? input : null;',
    '  };',
    '  const ensureRegisterUsernameStatus = (input) => {',
    '    if (!(input instanceof HTMLInputElement)) {',
    '      return null;',
    '    }',
    '    const wrapper = input.closest("div");',
    '    if (!(wrapper instanceof HTMLElement)) {',
    '      return null;',
    '    }',
    '    let status = wrapper.querySelector(\'[data-linx-role="username-availability"]\');',
    '    if (!(status instanceof HTMLParagraphElement)) {',
    '      status = document.createElement("p");',
    '      status.dataset.linxRole = "username-availability";',
    '      status.className = "hidden px-1 text-[10px] leading-tight";',
    '      wrapper.appendChild(status);',
    '    }',
    '    return status;',
    '  };',
    '  const updateRegisterUsernameStatus = (input, mode, message) => {',
    '    const status = ensureRegisterUsernameStatus(input);',
    '    if (!(status instanceof HTMLParagraphElement)) {',
    '      return;',
    '    }',
    '    if (mode === "idle") {',
    '      status.textContent = "";',
    '      status.className = "hidden px-1 text-[10px] leading-tight";',
    '      return;',
    '    }',
    '    const tone = mode === "available"',
    '      ? "mt-0.5 px-1 text-[10px] leading-tight text-emerald-600"',
    '      : mode === "checking"',
    '        ? "mt-0.5 px-1 text-[10px] leading-tight text-muted-foreground"',
    '        : "mt-0.5 px-1 text-[10px] leading-tight text-destructive";',
    '    status.className = tone;',
    '    status.textContent = message;',
    '  };',
    '  const checkUsernameAvailability = async (input, force = false) => {',
    '    if (!(input instanceof HTMLInputElement)) {',
    '      return null;',
    '    }',
    '    const username = normalizeUsername(input.value);',
    '    if (!username) {',
    '      input.dataset.linxUsernameChecked = "";',
    '      input.dataset.linxUsernameState = "idle";',
    '      updateRegisterUsernameStatus(input, "idle", "");',
    '      return null;',
    '    }',
    '    if (!isValidUsername(username)) {',
    '      input.dataset.linxUsernameChecked = username;',
    '      input.dataset.linxUsernameState = "invalid";',
    '      updateRegisterUsernameStatus(input, "error", "Username 只能包含小写字母、数字和连字符。");',
    '      return false;',
    '    }',
    '    const cachedValue = input.dataset.linxUsernameChecked || "";',
    '    const cachedState = input.dataset.linxUsernameState || "";',
    '    if (!force && cachedValue === username && (cachedState === "available" || cachedState === "unavailable")) {',
    '      updateRegisterUsernameStatus(',
    '        input,',
    '        cachedState === "available" ? "available" : "error",',
    '        cachedState === "available" ? "Pod 地址可用" : "这个 Pod 地址已存在。",',
    '      );',
    '      return cachedState === "available";',
    '    }',
    '    const requestId = String(++state.usernameCheckSerial);',
    '    input.dataset.linxUsernameRequestId = requestId;',
    '    input.dataset.linxUsernameChecked = username;',
    '    input.dataset.linxUsernameState = "checking";',
    '    updateRegisterUsernameStatus(input, "checking", "正在检查可用性…");',
    '    try {',
    '      const targetUrl = new URL(`${username}/`, window.location.origin).toString();',
    '      const response = await window.fetch(targetUrl, {',
    '        method: "GET",',
    '        redirect: "manual",',
    '        credentials: "include",',
    '        headers: { Accept: "text/turtle, application/json;q=0.9, */*;q=0.1" },',
    '      });',
    '      if (input.dataset.linxUsernameRequestId !== requestId) {',
    '        return null;',
    '      }',
    '      const nextState = response.status === 404 ? "available" : "unavailable";',
    '      input.dataset.linxUsernameState = nextState;',
    '      updateRegisterUsernameStatus(',
    '        input,',
    '        nextState === "available" ? "available" : "error",',
    '        nextState === "available" ? "Pod 地址可用" : "这个 Pod 地址已存在。",',
    '      );',
    '      return nextState === "available";',
    '    } catch (error) {',
    '      if (input.dataset.linxUsernameRequestId !== requestId) {',
    '        return null;',
    '      }',
    '      input.dataset.linxUsernameState = "error";',
    '      updateRegisterUsernameStatus(input, "error", "暂时无法验证可用性。");',
    '      return null;',
    '    }',
    '  };',
    '  const scheduleUsernameAvailabilityCheck = (input) => {',
    '    if (!(input instanceof HTMLInputElement)) {',
    '      return;',
    '    }',
    '    if (state.usernameCheckTimer) {',
    '      window.clearTimeout(state.usernameCheckTimer);',
    '      state.usernameCheckTimer = null;',
    '    }',
    '    const username = normalizeUsername(input.value);',
    '    if (!username) {',
    '      input.dataset.linxUsernameChecked = "";',
    '      input.dataset.linxUsernameState = "idle";',
    '      updateRegisterUsernameStatus(input, "idle", "");',
    '      return;',
    '    }',
    '    if (!isValidUsername(username)) {',
    '      input.dataset.linxUsernameChecked = username;',
    '      input.dataset.linxUsernameState = "invalid";',
    '      updateRegisterUsernameStatus(input, "error", "Username 只能包含小写字母、数字和连字符。");',
    '      return;',
    '    }',
    '    state.usernameCheckTimer = window.setTimeout(() => {',
    '      state.usernameCheckTimer = null;',
    '      void checkUsernameAvailability(input);',
    '    }, 250);',
    '  };',
    '  const resubmitForm = (form) => {',
    '    window.setTimeout(() => {',
    '      if (!(form instanceof HTMLFormElement) || !form.isConnected) {',
    '        return;',
    '      }',
    '      if (typeof form.requestSubmit === "function") {',
    '        form.requestSubmit();',
    '        return;',
    '      }',
    '      const submitButton = Array.from(form.querySelectorAll(\'button[type="submit"], button\')).find((button) =>',
    '        button instanceof HTMLButtonElement && !button.disabled,',
    '      );',
    '      if (submitButton instanceof HTMLButtonElement) {',
    '        submitButton.click();',
    '      }',
    '    }, 0);',
    '  };',
    '  const ensureUsernameAvailabilityForSubmit = async (form, input) => {',
    '    if (!(form instanceof HTMLFormElement) || !(input instanceof HTMLInputElement)) {',
    '      return;',
    '    }',
    '    const username = normalizeUsername(input.value);',
    '    const available = await checkUsernameAvailability(input, true);',
    '    if (available === true) {',
    '      input.setCustomValidity("");',
    '      clearInlineAlert("auth-form");',
    '      form.dataset.linxValidatedUsername = username;',
    '      resubmitForm(form);',
    '      return;',
    '    }',
    '    const message = available === false',
    '      ? "这个 Pod 地址已存在，请换一个用户名。"',
    '      : "暂时无法验证 username 可用性，请稍后重试。";',
    '    input.setCustomValidity(message);',
    '    input.reportValidity();',
    '    showInlineAlert("auth-form", message);',
    '  };',
    '  const bindRegisterUsernameFieldBehavior = () => {',
    '    const input = getRegisterUsernameInput();',
    '    if (!(input instanceof HTMLInputElement)) {',
    '      return;',
    '    }',
    '    ensureRegisterUsernameStatus(input);',
    '    if (input.dataset.linxAvailabilityBound === "1") {',
    '      return;',
    '    }',
    '    input.dataset.linxAvailabilityBound = "1";',
    '    input.addEventListener("input", () => {',
    '      input.setCustomValidity("");',
    '      const nextValue = normalizeUsername(input.value);',
    '      if (nextValue !== input.value && document.activeElement !== input) {',
    '        input.value = nextValue;',
    '      }',
    '      scheduleUsernameAvailabilityCheck(input);',
    '    });',
    '    input.addEventListener("blur", () => {',
    '      const nextValue = normalizeUsername(input.value);',
    '      input.value = nextValue;',
    '      if (nextValue) {',
    '        void checkUsernameAvailability(input, true);',
    '      } else {',
    '        updateRegisterUsernameStatus(input, "idle", "");',
    '      }',
    '    });',
    '    if (input.value.trim()) {',
    '      scheduleUsernameAvailabilityCheck(input);',
    '    }',
    '  };',
    '  const ensureRegisterUsernameField = () => {',
    '    if (!isRegisterView()) {',
    '      return;',
    '    }',
    '    const form = document.querySelector("form");',
    '    if (!(form instanceof HTMLFormElement)) {',
    '      return;',
    '    }',
    '    if (form.querySelector(\'input[name="username"]\')) {',
    '      bindRegisterUsernameFieldBehavior();',
    '      return;',
    '    }',
    '    const emailInput = form.querySelector(\'input[name="email"]\');',
    '    const emailField = emailInput instanceof HTMLInputElement ? emailInput.closest("div") : null;',
    '    const fieldStack = emailField instanceof HTMLElement ? emailField.parentElement : form.querySelector("div.space-y-3");',
    '    if (!(fieldStack instanceof HTMLElement)) {',
    '      return;',
    '    }',
    '    const wrapper = document.createElement("div");',
    '    wrapper.className = "space-y-1";',
    '    wrapper.dataset.linxRole = "username-field";',
    '    const input = document.createElement("input");',
    '    input.name = "username";',
    '    input.type = "text";',
    '    input.required = true;',
    '    input.autocomplete = "username";',
    '    input.placeholder = "Username";',
    '    input.className = "block w-full px-4 py-2.5 bg-zinc-50 border border-zinc-200 rounded-xl text-sm placeholder:text-zinc-400 focus:border-[#7C4DFF] focus:outline-none transition-colors";',
    '    const pendingUsername = getPendingUsername();',
    '    if (pendingUsername) {',
    '      input.value = pendingUsername;',
    '    }',
    '    wrapper.appendChild(input);',
    '    if (emailField instanceof HTMLElement) {',
    '      emailField.insertAdjacentElement("afterend", wrapper);',
    '    } else {',
    '      fieldStack.prepend(wrapper);',
    '    }',
    '    bindRegisterUsernameFieldBehavior();',
    '  };',
    '  const maybeAutoCreatePod = () => {',
    '    if (currentPathname() !== ACCOUNT_PATH) {',
    '      return;',
    '    }',
    '    const username = getPendingUsername();',
    '    if (!username) {',
    '      return;',
    '    }',
    '    const { addButton, form, nameInput, emptyState } = getAccountPodElements();',
    '    if (!emptyState && !(form instanceof HTMLFormElement)) {',
    '      clearPendingUsername();',
    '      return;',
    '    }',
    '    if (!(form instanceof HTMLFormElement)) {',
    '      if (addButton instanceof HTMLButtonElement) {',
    '        addButton.click();',
    '      }',
    '      return;',
    '    }',
    '    if (!(nameInput instanceof HTMLInputElement)) {',
    '      return;',
    '    }',
    '    if (!nameInput.value.trim()) {',
    '      setNativeInputValue(nameInput, username);',
    '    }',
    '    if (normalizeUsername(nameInput.value) !== username) {',
    '      return;',
    '    }',
    '    clearPendingUsername();',
    '    markPendingPodCreation();',
    '    window.setTimeout(() => {',
    '      if (typeof form.requestSubmit === "function") {',
    '        form.requestSubmit();',
    '        return;',
    '      }',
    '      const submitButton = Array.from(form.querySelectorAll("button")).find((button) => /create/i.test(button.textContent || ""));',
    '      if (submitButton instanceof HTMLButtonElement) {',
    '        submitButton.click();',
    '      }',
    '    }, 0);',
    '  };',
    '  const maybeContinuePendingConsent = () => {',
    '    if (currentPathname() !== ACCOUNT_PATH || !hasPendingPodCreation()) {',
    '      return;',
    '    }',
    '    const { continueLink } = getAccountPodElements();',
    '    if (!(continueLink instanceof HTMLAnchorElement) && !(continueLink instanceof HTMLButtonElement)) {',
    '      return;',
    '    }',
    '    if (continueLink instanceof HTMLAnchorElement && interceptConsentNavigation(continueLink.href)) {',
    '      return;',
    '    }',
    '    continueLink.click();',
    '  };',
    '  const getConsentEmptyState = () => {',
    '    const paragraph = Array.from(document.querySelectorAll("p")).find((node) =>',
    '      (node.textContent || "").includes("You need to create a Pod first to get a WebID."),',
    '    );',
    '    const container = paragraph ? paragraph.closest("div") : null;',
    '    const createButton = container',
    '      ? Array.from(container.querySelectorAll("button")).find((button) =>',
    '          (button.textContent || "").trim().includes("Create Pod"),',
    '        )',
    '      : null;',
    '    return { paragraph, container, createButton };',
    '  };',
    '  const setButtonDisabled = (button, disabled) => {',
    '    if (!(button instanceof HTMLButtonElement)) return;',
    '    button.disabled = disabled;',
    '    button.style.pointerEvents = disabled ? "none" : "";',
    '    button.style.opacity = disabled ? "0.6" : "";',
    '  };',
    '  const getInlineAlertHost = (scope) => {',
    '    if (scope === "pod-form") {',
    '      const { form } = getAccountPodElements();',
    '      return form instanceof HTMLFormElement ? form : null;',
    '    }',
    '    const form = document.querySelector("form");',
    '    return form instanceof HTMLFormElement ? form : null;',
    '  };',
    '  const clearInlineAlert = (scope) => {',
    '    const host = getInlineAlertHost(scope);',
    '    if (!(host instanceof HTMLElement)) {',
    '      return;',
    '    }',
    '    const alert = host.querySelector(\'[data-linx-role="inline-alert"]\');',
    '    if (alert instanceof HTMLElement) {',
    '      alert.remove();',
    '    }',
    '    if (scope === "pod-form") {',
    '      const { nameInput } = getAccountPodElements();',
    '      if (nameInput instanceof HTMLInputElement) {',
    '        nameInput.classList.remove("border-destructive", "focus:border-destructive", "focus:ring-destructive/15");',
    '      }',
    '    }',
    '  };',
    '  const normalizeAlertMessage = (message) => {',
    '    const text = typeof message === "string" ? message.trim() : String(message ?? "").trim();',
    '    if (!text) {',
    '      return "操作失败，请稍后重试。";',
    '    }',
    '    if (text.includes("There already is a login for this e-mail address")) {',
    '      return "这个邮箱已经注册，请直接登录或换一个邮箱。";',
    '    }',
    '    if (text.includes("There already is a resource at")) {',
    '      return "这个 Pod 地址已存在，请换一个用户名或 Pod 名称。";',
    '    }',
    '    if (text.includes("Passwords do not match")) {',
    '      return "两次输入的密码不一致。";',
    '    }',
    '    if (text.includes("Failed to create pod")) {',
    '      return "Pod 创建失败，请稍后重试。";',
    '    }',
    '    if (text.includes("Login failed")) {',
    '      return "登录失败，请检查账号和密码。";',
    '    }',
    '    return text;',
    '  };',
    '  const handleAuthFormError = (message) => {',
    '    const normalized = normalizeAlertMessage(message);',
    '    if (!normalized || normalized === "操作失败，请稍后重试。") {',
    '      return false;',
    '    }',
    '    state.registerSubmitUsername = null;',
    '    window.sessionStorage.removeItem(SUBMITTED_USERNAME_KEY);',
    '    clearPendingUsername();',
    '    showInlineAlert("auth-form", normalized);',
    '    const errorNode = document.getElementById("error");',
    '    if (errorNode instanceof HTMLElement) {',
    '      errorNode.textContent = "";',
    '    }',
    '    const usernameInput = getRegisterUsernameInput();',
    '    if (usernameInput instanceof HTMLInputElement) {',
    '      usernameInput.setCustomValidity("");',
    '    }',
    '    return true;',
    '  };',
    '  const showInlineAlert = (scope, message) => {',
    '    const host = getInlineAlertHost(scope);',
    '    if (!(host instanceof HTMLElement)) {',
    '      return false;',
    '    }',
    '    clearInlineAlert(scope);',
    '    const alert = document.createElement("div");',
    '    alert.dataset.linxRole = "inline-alert";',
    '    alert.className = "mb-3 rounded-xl border border-destructive/20 bg-destructive/10 px-3 py-2 text-xs leading-relaxed text-destructive";',
    '    alert.textContent = normalizeAlertMessage(message);',
    '    host.insertAdjacentElement("afterbegin", alert);',
    '    if (scope === "pod-form") {',
    '      const { nameInput } = getAccountPodElements();',
    '      if (nameInput instanceof HTMLInputElement) {',
    '        nameInput.classList.add("border-destructive", "focus:border-destructive", "focus:ring-destructive/15");',
    '        nameInput.focus();',
    '        nameInput.select();',
    '      }',
    '    }',
    '    alert.scrollIntoView({ block: "nearest" });',
    '    return true;',
    '  };',
    '  const resolveAlertScope = () => {',
    '    if (currentPathname() === ACCOUNT_PATH && getInlineAlertHost("pod-form")) {',
    '      return "pod-form";',
    '    }',
    '    if ((currentPathname() === LOGIN_PATH || currentPathname() === REGISTER_PATH) && getInlineAlertHost("auth-form")) {',
    '      return "auth-form";',
    '    }',
    '    return null;',
    '  };',
    '  const updateConsentPendingUi = (mode) => {',
    '    const { paragraph, container, createButton } = getConsentEmptyState();',
    '    if (!(paragraph instanceof HTMLParagraphElement) || !(container instanceof HTMLDivElement) || !(createButton instanceof HTMLButtonElement)) {',
    '      return;',
    '    }',
    '    const hintId = "linx-xpod-pending-hint";',
    '    let hint = container.querySelector(`[data-linx-role="${hintId}"]`);',
    '    if (mode === "pending") {',
    '      paragraph.textContent = "正在完成 Pod 创建并准备 WebID…";',
    '      if (!createButton.dataset.linxOriginalText) {',
    '        createButton.dataset.linxOriginalText = createButton.textContent || "Create Pod";',
    '      }',
    '      createButton.textContent = "Preparing Pod…";',
    '      setButtonDisabled(createButton, true);',
    '      if (!(hint instanceof HTMLParagraphElement)) {',
    '        hint = document.createElement("p");',
    '        hint.dataset.linxRole = hintId;',
    '        hint.className = "text-zinc-400 text-[11px]";',
    '        container.appendChild(hint);',
    '      }',
    '      hint.textContent = "Pod 已创建，正在等待 WebID 就绪。";',
    '    } else {',
    '      paragraph.textContent = mode === "timeout"',
    '        ? "Pod 已创建，但 WebID 还未就绪。请稍候重试。"' ,
    '        : "You need to create a Pod first to get a WebID.";',
    '      createButton.textContent = createButton.dataset.linxOriginalText || "Create Pod";',
    '      setButtonDisabled(createButton, false);',
    '      if (hint instanceof HTMLElement) {',
    '        hint.remove();',
    '      }',
    '    }',
    '    const authorizeButton = Array.from(document.querySelectorAll("button")).find((button) =>',
    '      (button.textContent || "").trim().startsWith("Authorize"),',
    '    );',
    '    if (authorizeButton instanceof HTMLButtonElement) {',
    '      setButtonDisabled(authorizeButton, mode === "pending");',
    '    }',
    '  };',
    '  const originalAlert = typeof window.alert === "function" ? window.alert.bind(window) : null;',
    '  window.alert = (message) => {',
    '    const scope = resolveAlertScope();',
    '    if (scope === "pod-form") {',
    '      clearPendingPodCreation();',
    '      updateConsentPendingUi("reset");',
    '    }',
    '    if (scope && showInlineAlert(scope, message)) {',
    '      return;',
    '    }',
    '    originalAlert?.(normalizeAlertMessage(message));',
    '  };',
    '  const ensureConsentWebIdsReady = async () => {',
    '    if (state.consentPolling || currentPathname() !== CONSENT_PATH || !hasPendingPodCreation()) {',
    '      return;',
    '    }',
    '    if (document.querySelector(\'input[name="webId"]\')) {',
    '      clearPendingPodCreation();',
    '      return;',
    '    }',
    '    state.consentPolling = true;',
    '    updateConsentPendingUi("pending");',
    '    const webIds = await waitForWebIds(CONSENT_WAIT_MS);',
    '    state.consentPolling = false;',
    '    if (webIds.length > 0) {',
    '      clearPendingPodCreation();',
    '      return;',
    '    }',
    '    clearPendingPodCreation();',
    '    updateConsentPendingUi("timeout");',
    '  };',
    '  const scheduleConsentNavigation = (targetUrl) => {',
    '    if (state.pendingConsentNavigationUrl === targetUrl) {',
    '      return;',
    '    }',
    '    state.pendingConsentNavigationUrl = targetUrl;',
    '    void (async () => {',
    '      const webIds = await waitForWebIds(ACCOUNT_WAIT_MS);',
    '      if (webIds.length > 0) {',
    '        clearPendingPodCreation();',
    '      }',
    '      const nextUrl = state.pendingConsentNavigationUrl || targetUrl;',
    '      state.pendingConsentNavigationUrl = null;',
    '      navigateWithinSpa(nextUrl);',
    '    })();',
    '  };',
    '  const interceptConsentNavigation = (url) => {',
    '    if (!url || !hasPendingPodCreation()) {',
    '      return false;',
    '    }',
    '    try {',
    '      const nextUrl = new URL(String(url), window.location.href);',
    '      if (normalizePathname(nextUrl.pathname) !== CONSENT_PATH) {',
    '        return false;',
    '      }',
    '      console.info("[LinX] Delaying consent navigation until WebID is ready.");',
    '      scheduleConsentNavigation(nextUrl.toString());',
    '      return true;',
    '    } catch {',
    '      return false;',
    '    }',
    '  };',
    '  document.addEventListener("submit", (event) => {',
    '    const form = event.target;',
    '    clearInlineAlert("auth-form");',
    '    clearInlineAlert("pod-form");',
    '    if (isRegisterView()) {',
      '      if (!(form instanceof HTMLFormElement)) {',
    '        return;',
    '      }',
    '      const usernameInput = form.querySelector(\'input[name="username"]\');',
    '      if (!(usernameInput instanceof HTMLInputElement)) {',
    '        return;',
    '      }',
    '      const username = normalizeUsername(usernameInput.value);',
    '      usernameInput.value = username;',
    '      if (!isValidUsername(username)) {',
    '        event.preventDefault();',
    '        usernameInput.setCustomValidity("Username 只能包含小写字母、数字和连字符。");',
    '        usernameInput.reportValidity();',
    '        usernameInput.focus();',
    '        return;',
    '      }',
    '      if (form.dataset.linxValidatedUsername === username) {',
    '        form.dataset.linxValidatedUsername = "";',
    '        usernameInput.setCustomValidity("");',
    '        state.registerSubmitUsername = username;',
    '        window.sessionStorage.setItem(SUBMITTED_USERNAME_KEY, username);',
    '        return;',
    '      }',
    '      event.preventDefault();',
    '      usernameInput.setCustomValidity("");',
    '      void ensureUsernameAvailabilityForSubmit(form, usernameInput);',
    '      return;',
    '    }',
    '    if (currentPathname() !== ACCOUNT_PATH) {',
    '      return;',
    '    }',
    '    if (isCreatePodForm(form)) {',
    '      markPendingPodCreation();',
    '    }',
    '  }, true);',
    '  document.addEventListener("input", () => {',
    '    if (currentPathname() === ACCOUNT_PATH) {',
    '      clearInlineAlert("pod-form");',
    '      return;',
    '    }',
    '    if (currentPathname() === LOGIN_PATH || currentPathname() === REGISTER_PATH) {',
    '      clearInlineAlert("auth-form");',
    '    }',
    '  }, true);',
    '  document.addEventListener("change", (event) => {',
    '    const target = event.target;',
    '    if (!(target instanceof HTMLElement) || target.id !== "error") {',
    '      return;',
    '    }',
    '    if ((currentPathname() === LOGIN_PATH || currentPathname() === REGISTER_PATH) && target.textContent?.trim()) {',
    '      handleAuthFormError(target.textContent);',
    '    }',
    '  }, true);',
    '  window.history.pushState = function pushState(stateValue, unused, url) {',
    '    if (interceptConsentNavigation(url)) {',
    '      return;',
    '    }',
    '    return nativePushState(stateValue, unused, url);',
    '  };',
    '  window.history.replaceState = function replaceState(stateValue, unused, url) {',
    '    if (interceptConsentNavigation(url)) {',
    '      return;',
    '    }',
    '    return nativeReplaceState(stateValue, unused, url);',
    '  };',
    '  window.fetch = function linxFetch(resource, init) {',
    '    const next = attachProvisionCodeToPodCreate(resource, init);',
    '    return nativeFetch(next.resource, next.init);',
    '  };',
    '  const observer = new MutationObserver(() => {',
    '    if (isRegisterView()) {',
    '      ensureRegisterUsernameField();',
    '      const errorNode = document.getElementById("error");',
    '      if (errorNode instanceof HTMLElement && errorNode.textContent?.trim()) {',
    '        handleAuthFormError(errorNode.textContent);',
    '      }',
    '    }',
    '    if (currentPathname() === ACCOUNT_PATH) {',
    '      const submittedUsername = state.registerSubmitUsername || window.sessionStorage.getItem(SUBMITTED_USERNAME_KEY);',
    '      if (submittedUsername) {',
    '        setPendingUsername(submittedUsername);',
    '        state.registerSubmitUsername = null;',
    '        window.sessionStorage.removeItem(SUBMITTED_USERNAME_KEY);',
    '      }',
    '      cleanupAccountPodHelperText();',
    '      maybeAutoCreatePod();',
    '      maybeContinuePendingConsent();',
    '    }',
    '    if (currentPathname() === CONSENT_PATH && hasPendingPodCreation()) {',
    '      updateConsentPendingUi("pending");',
    '      void ensureConsentWebIdsReady();',
    '    }',
    '  });',
    '  observer.observe(document.documentElement, { childList: true, characterData: true, subtree: true });',
    '  if (isRegisterView()) {',
    '    ensureRegisterUsernameField();',
    '  }',
    '  if (currentPathname() === ACCOUNT_PATH) {',
    '    const submittedUsername = state.registerSubmitUsername || window.sessionStorage.getItem(SUBMITTED_USERNAME_KEY);',
    '    if (submittedUsername) {',
    '      setPendingUsername(submittedUsername);',
    '      state.registerSubmitUsername = null;',
    '      window.sessionStorage.removeItem(SUBMITTED_USERNAME_KEY);',
    '    }',
    '    cleanupAccountPodHelperText();',
    '    maybeAutoCreatePod();',
    '    maybeContinuePendingConsent();',
    '  }',
    '  if (currentPathname() === CONSENT_PATH && hasPendingPodCreation()) {',
    '    updateConsentPendingUi("pending");',
    '    void ensureConsentWebIdsReady();',
    '  }',
    "  return 'installed';",
    '})();',
  ].join('\n')
}

export async function installXpodAuthEnhancer(target: ScriptInjectionTarget): Promise<boolean> {
  if (!isXpodAuthPageUrl(target.getURL())) {
    return false
  }

  await target.executeJavaScript(buildXpodAuthEnhancerScript(), true)
  return true
}
