import { spawnSync } from 'node:child_process'
import { cpSync, existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { createRequire } from 'node:module'

const workspaceRoot = fileURLToPath(new URL('..', import.meta.url))
const distDir = fileURLToPath(new URL('../dist', import.meta.url))
const generatedDir = fileURLToPath(new URL('../src/generated', import.meta.url))
const packageJsonPath = fileURLToPath(new URL('../package.json', import.meta.url))
const skillsSourceDir = fileURLToPath(new URL('../../../skills', import.meta.url))
const skillsDistDir = fileURLToPath(new URL('../dist/skills', import.meta.url))
const require = createRequire(import.meta.url)
const tscBin = require.resolve('typescript/bin/tsc')
const compileArgs = [
  tscBin,
  '-p',
  'tsconfig.json',
  '--outDir',
  'dist',
  '--noEmitOnError',
  'false',
]

function sleep(ms) {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms)
}

function removeDirRobust(path) {
  if (!existsSync(path)) return

  const tombstone = `${path}.trash-${Date.now()}`
  try {
    renameSync(path, tombstone)
    rmSync(tombstone, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 })
    return
  } catch {
    // Fall through to direct retry. Rename can fail if another process already touched dist.
  }

  for (let attempt = 0; attempt < 5; attempt += 1) {
    try {
      rmSync(path, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 })
      return
    } catch (error) {
      if (attempt === 4) throw error
      sleep(100)
    }
  }
}

function writeGeneratedVersionModule() {
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'))
  const version = typeof packageJson.version === 'string' && packageJson.version.trim()
    ? packageJson.version.trim()
    : '0.0.0'

  mkdirSync(generatedDir, { recursive: true })
  writeFileSync(
    fileURLToPath(new URL('../src/generated/version.ts', import.meta.url)),
    [
      '// Generated by apps/cli/scripts/build.mjs. Keep a committed fallback for direct test compiles.',
      `export const LINX_CLI_VERSION = ${JSON.stringify(version)}`,
      '',
    ].join('\n'),
  )
}

function flattenNestedEmit() {
  const emittedRoot = fileURLToPath(new URL('../dist/apps/cli/src/', import.meta.url))

  if (!existsSync(emittedRoot)) {
    return
  }

  for (const [targetName, sourceName] of [
    ['index.js', 'apps/cli/src/index.js'],
    ['index.js.map', 'apps/cli/src/index.js.map'],
    ['watch-cli.js', 'apps/cli/src/watch-cli.js'],
    ['watch-cli.js.map', 'apps/cli/src/watch-cli.js.map'],
    ['generated', 'apps/cli/src/generated'],
    ['lib', 'apps/cli/src/lib'],
  ]) {
    const targetPath = fileURLToPath(new URL(`../dist/${targetName}`, import.meta.url))
    const sourcePath = fileURLToPath(new URL(`../dist/${sourceName}`, import.meta.url))
    rmSync(targetPath, { recursive: true, force: true })
    cpSync(sourcePath, targetPath, { recursive: true })
  }

  rmSync(fileURLToPath(new URL('../dist/apps', import.meta.url)), { recursive: true, force: true })
  rmSync(fileURLToPath(new URL('../dist/packages', import.meta.url)), { recursive: true, force: true })
}

function copyBundledSkills() {
  if (!existsSync(skillsSourceDir)) {
    return
  }

  cpSync(skillsSourceDir, skillsDistDir, {
    recursive: true,
    filter: (src) => !src.includes('/node_modules/') && !src.includes('/.git/'),
  })
}

removeDirRobust(distDir)
writeGeneratedVersionModule()

const compile = spawnSync(process.execPath, compileArgs, {
  cwd: workspaceRoot,
  stdio: 'inherit',
})

if (compile.error) {
  process.stderr.write(`[linx-cli] Failed to run TypeScript compiler: ${compile.error.message}\n`)
}

if ((compile.status ?? 1) !== 0) {
  process.exit(compile.status ?? 1)
}

flattenNestedEmit()
copyBundledSkills()
process.exit(0)
