/**
 * Web Server Module - Serves LinX Web UI
 */
import * as fs from 'fs'
import * as path from 'path'
import express, { Express, Request, Response } from 'express'
import { Server } from 'http'
import { getXpodModule } from './xpod'
import { getRuntimeThreadsModule } from './runtime-threads'
import { getPodMountModule } from './mount/module'
import type { PodMountRecord } from './mount/types'
import type { PodMountModule } from './mount/module'

interface SetupData {
  dataDir: string
  port: number
  autoStart: boolean
  deploymentMode: 'local' | 'standalone'
  domainSource?: 'cloud' | 'manual'
  network: {
    accessMode: 'auto' | 'tunnel'
    tunnelProvider?: 'cloudflare' | 'sakura'
    tunnelToken?: string
  }
  local?: {
    deviceId?: string
    subdomain?: string
  }
  standalone?: {
    customDomain?: string
    idpUrl?: string
  }
  publicDomain?: string
  autoDetectPublicIp?: boolean
  httpsCertPath?: string
}


function getConfigDir(): string {
  return path.join(process.env.HOME || '', 'Library', 'Application Support', 'LinX')
}

function getEnvPathInternal(): string {
  return path.join(getConfigDir(), '.env')
}

function getSetupFlagPath(): string {
  return path.join(getConfigDir(), '.setup-complete')
}


export function serializeMountForResponse(record: PodMountRecord) {
  return {
    id: record.id,
    label: record.label,
    source: record.source,
    status: record.status,
    finderVisible: record.finderVisible,
    podBaseUrls: record.podBaseUrls,
    podNames: record.podNames,
    mounts: record.mounts,
    createdAt: record.createdAt,
    updatedAt: record.updatedAt,
    lastUsedAt: record.lastUsedAt,
    lastError: record.lastError,
    mountId: record.id,
    mountPath: record.rootPath,
  }
}

export function serializeOwnerSessionStatus(module: Pick<PodMountModule, 'getLeaseStatus'>, record: Pick<PodMountRecord, 'ownerKey' | 'ownerWebId'> | null) {
  return record ? module.getLeaseStatus(record) : null
}

export class WebServerModule {
  private app: Express
  private server: Server | null = null

  constructor() {
    this.app = express()
    this.setupRoutes()
  }

  /**
   * Get the web app dist directory
   */
  private getWebDistDir(): string {
    // In development: apps/web/dist
    const devDist = path.join(__dirname, '..', '..', '..', 'web', 'dist')
    if (fs.existsSync(devDist)) {
      return devDist
    }

    // Packaged app
    const resourcesPath = (process as any).resourcesPath
    if (resourcesPath) {
      return path.join(resourcesPath, 'web')
    }

    console.warn('[WebServer] Web dist directory not found, using dev dist path')
    return devDist
  }

  /**
   * Generate .env file content
   */
  private generateEnvContent(data: SetupData): string {
    const { port, dataDir, deploymentMode, domainSource, network, local, standalone, publicDomain } = data

    // Build base URL
    let baseUrl: string
    if (publicDomain) {
      baseUrl = `https://${publicDomain}`
    } else if (deploymentMode === 'local' && local?.subdomain) {
      baseUrl = `https://${local.subdomain}.undefineds.xyz`
    } else if (deploymentMode === 'standalone' && standalone?.customDomain) {
      baseUrl = `https://${standalone.customDomain}`
    } else {
      baseUrl = `http://localhost:${port}`
    }

    const lines = [
      '# Generated by LinX Service',
      `XPOD_EDITION=local`,
      `CSS_EDITION=local`,
      `CSS_PORT=${port}`,
      `CSS_BASE_URL=${baseUrl}`,
      `CSS_LOGGING_LEVEL=info`,
      `CSS_SHOW_STACK_TRACE=true`,
      `CSS_ROOT_FILE_PATH=${dataDir}`,
      `CSS_SPARQL_ENDPOINT=sqlite:${path.join(dataDir, 'quadstore.sqlite')}`,
      `CSS_IDENTITY_DB_URL=sqlite:${path.join(dataDir, 'identity.sqlite')}`,
      `CSS_USAGE_DB_URL=sqlite:${path.join(dataDir, 'usage.sqlite')}`,
    ]

    // Device ID for DDNS
    if (local?.deviceId) {
      lines.push(`CSS_NODE_ID=${local.deviceId}`)
    }

    // LinX service metadata for runtime UX and future automation
    lines.push(`LINX_DEPLOYMENT_MODE=${deploymentMode}`)
    lines.push(`LINX_DOMAIN_SOURCE=${domainSource || 'manual'}`)
    if (data.publicDomain) lines.push(`LINX_PUBLIC_DOMAIN=${data.publicDomain}`)
    if (typeof data.autoDetectPublicIp === 'boolean') lines.push(`LINX_AUTO_DETECT_PUBLIC_IP=${data.autoDetectPublicIp}`)
    if (data.httpsCertPath) lines.push(`LINX_HTTPS_CERT_PATH=${data.httpsCertPath}`)
    if (local?.subdomain) lines.push(`LINX_SUBDOMAIN=${local.subdomain}`)
    if (local?.deviceId) lines.push(`LINX_DEVICE_ID=${local.deviceId}`)
    if (network.tunnelProvider) lines.push(`LINX_TUNNEL_PROVIDER=${network.tunnelProvider}`)

    // IdP URL for standalone mode
    if (deploymentMode === 'standalone' && standalone?.idpUrl) {
      lines.push(`CSS_OIDC_ISSUER=${standalone.idpUrl}`)
    }

    // Tunnel configuration
    if (network.accessMode === 'tunnel' && network.tunnelToken) {
      if (network.tunnelProvider === 'cloudflare') {
        lines.push(`CLOUDFLARE_TUNNEL_TOKEN=${network.tunnelToken}`)
      } else if (network.tunnelProvider === 'sakura') {
        lines.push(`SAKURA_TOKEN=${network.tunnelToken}`)
      }
    }

    return lines.join('\n')
  }

  /**
   * Setup routes
   */
  private setupRoutes(): void {
    const distDir = this.getWebDistDir()

    // API routes for service control
    this.app.use(express.json())

    // Check if setup is completed
    this.app.get('/api/setup/status', (_req: Request, res: Response) => {
      const setupCompleted = fs.existsSync(getSetupFlagPath())
      res.json({ setupCompleted })
    })

    // Get current .env config
    this.app.get('/api/setup/config', (_req: Request, res: Response) => {
      try {
        const envPath = getEnvPathInternal()
        if (fs.existsSync(envPath)) {
          const envContent = fs.readFileSync(envPath, 'utf-8')
          const env: Record<string, string> = {}

          for (const line of envContent.split('\n')) {
            const match = line.match(/^([A-Z_]+)=(.+)$/)
            if (match) {
              env[match[1]] = match[2]
            }
          }

          const tunnelProvider = env.LINX_TUNNEL_PROVIDER || (env.CLOUDFLARE_TUNNEL_TOKEN ? 'cloudflare' : env.SAKURA_TOKEN ? 'sakura' : '')

          res.json({
            dataDir: env.CSS_ROOT_FILE_PATH || path.join(getConfigDir(), 'pod'),
            port: parseInt(env.CSS_PORT || '5737', 10),
            baseUrl: env.CSS_BASE_URL || 'http://localhost:5737',
            deploymentMode: (env.LINX_DEPLOYMENT_MODE as 'local' | 'standalone') || 'local',
            domainSource: (env.LINX_DOMAIN_SOURCE as 'cloud' | 'manual') || 'manual',
            publicDomain: env.LINX_PUBLIC_DOMAIN || '',
            autoDetectPublicIp: env.LINX_AUTO_DETECT_PUBLIC_IP === 'true',
            httpsCertPath: env.LINX_HTTPS_CERT_PATH || '',
            subdomain: env.LINX_SUBDOMAIN || '',
            deviceId: env.LINX_DEVICE_ID || env.CSS_NODE_ID || '',
            tunnelProvider,
            hasTunnelToken: Boolean(env.CLOUDFLARE_TUNNEL_TOKEN || env.SAKURA_TOKEN),
          })
        } else {
          // Return defaults
          res.json({
            dataDir: path.join(getConfigDir(), 'pod'),
            port: 5737,
            baseUrl: 'http://localhost:5737',
            deploymentMode: 'local',
            domainSource: 'manual',
            publicDomain: '',
            autoDetectPublicIp: true,
            httpsCertPath: '',
            subdomain: '',
            deviceId: '',
            tunnelProvider: '',
            hasTunnelToken: false,
          })
        }
      } catch (error) {
        console.error('[WebServer] Failed to read config:', error)
        res.status(500).json({ error: 'Failed to read config' })
      }
    })

    // Save setup config - directly write .env file
    this.app.post('/api/setup', (req: Request, res: Response) => {
      try {
        const data = req.body as SetupData

        if (data.network?.accessMode === 'tunnel' && !data.network.tunnelProvider) {
          res.status(400).json({ error: 'tunnelProvider is required when accessMode=tunnel' })
          return
        }

        if (data.network?.accessMode === 'tunnel' && data.network.tunnelProvider && !data.network.tunnelToken) {
          const envPath = getEnvPathInternal()
          if (!fs.existsSync(envPath)) {
            res.status(400).json({ error: 'tunnelToken is required for new tunnel configuration' })
            return
          }

          const envContent = fs.readFileSync(envPath, 'utf-8')
          const env: Record<string, string> = {}
          for (const line of envContent.split('\n')) {
            const match = line.match(/^([A-Z_]+)=(.+)$/)
            if (match) {
              env[match[1]] = match[2]
            }
          }

          const tokenKey = data.network.tunnelProvider === 'cloudflare' ? 'CLOUDFLARE_TUNNEL_TOKEN' : 'SAKURA_TOKEN'
          const existingToken = env[tokenKey]
          if (!existingToken) {
            res.status(400).json({ error: 'tunnelToken is required for selected tunnel provider' })
            return
          }
          data.network.tunnelToken = existingToken
        }

        // Ensure config directory exists
        const configDir = getConfigDir()
        if (!fs.existsSync(configDir)) {
          fs.mkdirSync(configDir, { recursive: true })
        }

        // Ensure data directory exists
        if (!fs.existsSync(data.dataDir)) {
          fs.mkdirSync(data.dataDir, { recursive: true })
        }

        // Write .env file
        const envContent = this.generateEnvContent(data)
        const envPath = getEnvPathInternal()
        fs.writeFileSync(envPath, envContent)
        console.log('[WebServer] Generated .env file:', envPath)

        // Mark setup as complete
        fs.writeFileSync(getSetupFlagPath(), new Date().toISOString())

        res.json({ success: true, envPath: envPath })
      } catch (error) {
        console.error('[WebServer] Failed to save setup:', error)
        res.status(500).json({ error: 'Failed to save configuration' })
      }
    })

    // Get service status
    this.app.get('/api/service/status', (_req: Request, res: Response) => {
      const xpodStatus = getXpodModule().getStatus()
      const setupCompleted = fs.existsSync(getSetupFlagPath())

      res.json({
        pod: {
          port: xpodStatus.port || 5737,
          baseUrl: xpodStatus.baseUrl || 'http://localhost:5737',
          publicUrl: xpodStatus.publicUrl,
          running: xpodStatus.running,
        },
        setupCompleted,
        envPath: getEnvPathInternal(),
      })
    })

    // Service controls
    this.app.post('/api/service/start', async (_req: Request, res: Response) => {
      try {
        await getXpodModule().start()
        res.json({ success: true })
      } catch (error) {
        console.error('[WebServer] Failed to start xpod:', error)
        res.status(500).json({ error: 'Failed to start xpod' })
      }
    })

    this.app.post('/api/service/stop', async (_req: Request, res: Response) => {
      try {
        await getRuntimeThreadsModule().stopAllSessions()
        await getXpodModule().stop()
        res.json({ success: true })
      } catch (error) {
        console.error('[WebServer] Failed to stop xpod:', error)
        res.status(500).json({ error: 'Failed to stop xpod' })
      }
    })

    this.app.post('/api/service/restart', async (_req: Request, res: Response) => {
      try {
        await getXpodModule().restart()
        res.json({ success: true })
      } catch (error) {
        console.error('[WebServer] Failed to restart xpod:', error)
        res.status(500).json({ error: 'Failed to restart xpod' })
      }
    })


    this.app.get('/api/threads/:threadId/runtime', (req: Request, res: Response) => {
      const session = getRuntimeThreadsModule().getSessionByChatThread(req.params.threadId)
      if (!session) {
        res.status(404).json({ error: 'Runtime session not found' })
        return
      }
      res.json(session)
    })

    this.app.post('/api/threads/:threadId/runtime', async (req: Request, res: Response) => {
      try {
        const {
          title,
          workspace,
          tool,
        } = req.body ?? {}
        const threadId = req.params.threadId
        const normalizedWorkspace = workspace && typeof workspace === 'object'
          ? workspace as Record<string, any>
          : null

        const workspacePath = workspace && typeof workspace === 'object' && typeof workspace.path === 'string'
          ? workspace.path
          : undefined
        const hasWorkspacePath = typeof workspacePath === 'string' && workspacePath.trim().length > 0

        if (!threadId || !hasWorkspacePath) {
          res.status(400).json({ error: 'threadId and workspace.path are required' })
          return
        }

        const session = await getRuntimeThreadsModule().createSession({
          threadId,
          title: typeof title === 'string' && title.trim().length > 0 ? title : '运行时会话',
          workspace: normalizedWorkspace as any,
          tool,
        })
        res.json(session)
      } catch (error) {
        console.error('[WebServer] Failed to create thread-bound runtime session:', error)
        res.status(500).json({ error: 'Failed to create runtime session' })
      }
    })

    this.app.post('/api/threads/:threadId/runtime/start', async (req: Request, res: Response) => {
      try {
        const existing = getRuntimeThreadsModule().getSessionByChatThread(req.params.threadId)
        if (!existing) {
          res.status(404).json({ error: 'Runtime session not found' })
          return
        }
        const session = await getRuntimeThreadsModule().startSession(existing.id)
        res.json(session)
      } catch (error) {
        console.error('[WebServer] Failed to start thread-bound runtime session:', error)
        res.status(500).json({ error: error instanceof Error ? error.message : 'Failed to start runtime session' })
      }
    })

    this.app.post('/api/threads/:threadId/runtime/pause', async (req: Request, res: Response) => {
      try {
        const existing = getRuntimeThreadsModule().getSessionByChatThread(req.params.threadId)
        if (!existing) {
          res.status(404).json({ error: 'Runtime session not found' })
          return
        }
        const session = await getRuntimeThreadsModule().pauseSession(existing.id)
        res.json(session)
      } catch (error) {
        console.error('[WebServer] Failed to pause thread-bound runtime session:', error)
        res.status(500).json({ error: error instanceof Error ? error.message : 'Failed to pause runtime session' })
      }
    })

    this.app.post('/api/threads/:threadId/runtime/resume', async (req: Request, res: Response) => {
      try {
        const existing = getRuntimeThreadsModule().getSessionByChatThread(req.params.threadId)
        if (!existing) {
          res.status(404).json({ error: 'Runtime session not found' })
          return
        }
        const session = await getRuntimeThreadsModule().resumeSession(existing.id)
        res.json(session)
      } catch (error) {
        console.error('[WebServer] Failed to resume thread-bound runtime session:', error)
        res.status(500).json({ error: error instanceof Error ? error.message : 'Failed to resume runtime session' })
      }
    })

    this.app.post('/api/threads/:threadId/runtime/stop', async (req: Request, res: Response) => {
      try {
        const existing = getRuntimeThreadsModule().getSessionByChatThread(req.params.threadId)
        if (!existing) {
          res.status(404).json({ error: 'Runtime session not found' })
          return
        }
        const session = await getRuntimeThreadsModule().stopSession(existing.id)
        res.json(session)
      } catch (error) {
        console.error('[WebServer] Failed to stop thread-bound runtime session:', error)
        res.status(500).json({ error: error instanceof Error ? error.message : 'Failed to stop runtime session' })
      }
    })

    this.app.post('/api/threads/:threadId/runtime/message', async (req: Request, res: Response) => {
      try {
        const existing = getRuntimeThreadsModule().getSessionByChatThread(req.params.threadId)
        if (!existing) {
          res.status(404).json({ error: 'Runtime session not found' })
          return
        }
        const text = typeof req.body?.text === 'string' ? req.body.text.trim() : ''
        if (!text) {
          res.status(400).json({ error: 'text is required' })
          return
        }
        const session = await getRuntimeThreadsModule().sendSessionMessage(existing.id, text)
        res.json(session)
      } catch (error) {
        console.error('[WebServer] Failed to send thread-bound runtime session message:', error)
        res.status(500).json({ error: error instanceof Error ? error.message : 'Failed to send runtime session message' })
      }
    })

    this.app.post('/api/threads/:threadId/runtime/tool-calls/:requestId/respond', async (req: Request, res: Response) => {
      try {
        const existing = getRuntimeThreadsModule().getSessionByChatThread(req.params.threadId)
        if (!existing) {
          res.status(404).json({ error: 'Runtime session not found' })
          return
        }
        const output = typeof req.body?.output === 'string' ? req.body.output : ''
        if (!output.trim()) {
          res.status(400).json({ error: 'output is required' })
          return
        }
        const session = await getRuntimeThreadsModule().respondToSessionToolCall(existing.id, req.params.requestId, output)
        res.json(session)
      } catch (error) {
        console.error('[WebServer] Failed to respond thread-bound runtime tool call:', error)
        res.status(500).json({ error: error instanceof Error ? error.message : 'Failed to respond runtime tool call' })
      }
    })

    this.app.get('/api/threads/:threadId/runtime/log', (req: Request, res: Response) => {
      try {
        const existing = getRuntimeThreadsModule().getSessionByChatThread(req.params.threadId)
        if (!existing) {
          res.status(404).json({ error: 'Runtime session not found' })
          return
        }
        const log = getRuntimeThreadsModule().getSessionLog(existing.id)
        res.type('text/plain').send(log)
      } catch (error) {
        console.error('[WebServer] Failed to get thread-bound runtime session log:', error)
        res.status(500).json({ error: 'Failed to get runtime session log' })
      }
    })

    this.app.get('/api/threads/:threadId/runtime/events', (req: Request, res: Response) => {
      const runtimeSessions = getRuntimeThreadsModule()
      const session = runtimeSessions.getSessionByChatThread(req.params.threadId)
      if (!session) {
        res.status(404).json({ error: 'Runtime session not found' })
        return
      }

      res.setHeader('Content-Type', 'text/event-stream')
      res.setHeader('Cache-Control', 'no-cache, no-transform')
      res.setHeader('Connection', 'keep-alive')
      res.flushHeaders?.()

      const unsubscribe = runtimeSessions.subscribeSession(session.id, (event) => {
        res.write(`data: ${JSON.stringify(event)}\n\n`)
      })

      res.write(`data: ${JSON.stringify({ type: 'status', ts: Date.now(), threadId: session.id, status: session.status })}\n\n`)

      req.on('close', () => {
        unsubscribe()
        res.end()
      })
    })

    // Canonical Pod mount APIs (mount-first product contract)
    this.app.get('/api/mounts', (_req: Request, res: Response) => {
      const mountModule = getPodMountModule()
      res.json({
        items: mountModule.listForCurrentOwner().map((record) => serializeMountForResponse(record)),
        ownerSessionStatus: serializeOwnerSessionStatus(mountModule, mountModule.listForCurrentOwner()[0] ?? null),
      })
    })

    this.app.post('/api/mounts/current/ensure', async (req: Request, res: Response) => {
      try {
        const revealInFinder = req.body?.revealInFinder === true
        const mount = await getPodMountModule().ensureCurrent({ revealInFinder })
        const mountModule = getPodMountModule()
        res.json({
          ...serializeMountForResponse(mount),
          ownerSessionStatus: serializeOwnerSessionStatus(mountModule, mount),
        })
      } catch (error) {
        console.error('[WebServer] Failed to ensure current mount:', error)
        const message = error instanceof Error ? error.message : 'Failed to ensure current mount'
        const status = /No active Linx session/i.test(message)
          ? 404
          : /No authorized pod primitives/i.test(message)
            ? 400
            : 500
        res.status(status).json({ error: message })
      }
    })

    this.app.get('/api/mounts/current', (_req: Request, res: Response) => {
      try {
        const session = getPodMountModule().peekOwnerContext()
        if (!session?.ownerKey) {
          res.status(404).json({ error: 'No active Linx session available' })
          return
        }

        const mount = getPodMountModule().findLatestForOwner(session.ownerKey, session.ownerWebId)
        if (!mount) {
          res.status(404).json({ error: 'Current mount not found' })
          return
        }

        const mountModule = getPodMountModule()
        res.json({
          ...serializeMountForResponse(mount),
          ownerSessionStatus: serializeOwnerSessionStatus(mountModule, mount),
        })
      } catch (error) {
        console.error('[WebServer] Failed to get current mount:', error)
        res.status(500).json({ error: error instanceof Error ? error.message : 'Failed to get current mount' })
      }
    })

    this.app.get('/api/mounts/:id', (req: Request, res: Response) => {
      const mount = getPodMountModule().getForCurrentOwner(req.params.id)
      if (!mount) {
        res.status(404).json({ error: 'Mount not found' })
        return
      }
      const mountModule = getPodMountModule()
      res.json({
        ...serializeMountForResponse(mount),
        ownerSessionStatus: serializeOwnerSessionStatus(mountModule, mount),
      })
    })

    this.app.post('/api/mounts/current/reveal', async (_req: Request, res: Response) => {
      try {
        const mount = await getPodMountModule().revealCurrent()
        const mountModule = getPodMountModule()
        res.json({
          ...serializeMountForResponse(mount),
          ownerSessionStatus: serializeOwnerSessionStatus(mountModule, mount),
        })
      } catch (error) {
        console.error('[WebServer] Failed to reveal current mount:', error)
        const message = error instanceof Error ? error.message : 'Failed to reveal current mount'
        const status = /No active Linx session/i.test(message) ? 404 : 500
        res.status(status).json({ error: message })
      }
    })

    this.app.post('/api/mounts/:id/reveal', async (req: Request, res: Response) => {
      try {
        const mount = await getPodMountModule().revealForCurrentOwner(req.params.id)
        const mountModule = getPodMountModule()
        res.json({
          ...serializeMountForResponse(mount),
          ownerSessionStatus: serializeOwnerSessionStatus(mountModule, mount),
        })
      } catch (error) {
        console.error('[WebServer] Failed to reveal mount:', error)
        const message = error instanceof Error ? error.message : 'Failed to reveal mount'
        const status = /current owner/i.test(message) ? 404 : 500
        res.status(status).json({ error: message })
      }
    })

    this.app.delete('/api/mounts/:id', async (req: Request, res: Response) => {
      try {
        const mount = await getPodMountModule().removeForCurrentOwner(req.params.id)
        res.json({
          success: true,
          mount: serializeMountForResponse(mount),
          ownerSessionStatus: serializeOwnerSessionStatus(getPodMountModule(), mount),
        })
      } catch (error) {
        console.error('[WebServer] Failed to remove mount:', error)
        const message = error instanceof Error ? error.message : 'Failed to remove mount'
        const status = /current owner|Mount not found/i.test(message) ? 404 : 500
        res.status(status).json({ error: message })
      }
    })
    // Serve static files with injection
    if (fs.existsSync(distDir)) {
      // Inject __LINX_SERVICE__ into index.html
      this.app.get('/', (_req, res) => {
        const indexPath = path.join(distDir, 'index.html')
        let html = fs.readFileSync(indexPath, 'utf-8')

        // Inject service flag before </head>
        const injection = `<script>window.__LINX_SERVICE__ = true;</script>`
        html = html.replace('</head>', `${injection}</head>`)

        res.type('html').send(html)
      })

      this.app.use(express.static(distDir))

      // SPA fallback - also inject for deep links
      this.app.get('*', (req, res) => {
        // Skip API routes
        if (req.path.startsWith('/api/')) {
          res.status(404).json({ error: 'Not found' })
          return
        }

        const indexPath = path.join(distDir, 'index.html')
        let html = fs.readFileSync(indexPath, 'utf-8')

        const injection = `<script>window.__LINX_SERVICE__ = true;</script>`
        html = html.replace('</head>', `${injection}</head>`)

        res.type('html').send(html)
      })
    } else {
      // Development: proxy to Vite dev server
      console.log('[WebServer] Production build not found, running in dev mode')
      this.app.get('*', (_req, res) => {
        res.redirect('http://localhost:5174')
      })
    }
  }

  /**
   * Start the web server
   */
  async start(): Promise<void> {
    if (this.server) {
      console.log('[WebServer] Already running')
      return
    }

    return new Promise((resolve, reject) => {
      this.server = this.app.listen(5173, () => {
        console.log('[WebServer] Serving on http://localhost:5173')
        resolve()
      })

      this.server.on('error', (error: NodeJS.ErrnoException) => {
        if (error.code === 'EADDRINUSE') {
          console.error('[WebServer] Port 5173 is already in use')
        }
        reject(error)
      })
    })
  }

  /**
   * Stop the web server
   */
  async stop(): Promise<void> {
    if (!this.server) {
      return
    }

    return new Promise((resolve) => {
      this.server!.close(() => {
        this.server = null
        console.log('[WebServer] Stopped')
        resolve()
      })
    })
  }

  /**
   * Get server URL
   */
  getUrl(): string {
    return 'http://localhost:5173'
  }

  /**
   * Check if setup is completed
   */
  isSetupCompleted(): boolean {
    return fs.existsSync(getSetupFlagPath())
  }

  /**
   * Get .env file path
   */
  getEnvPath(): string {
    return getEnvPathInternal()
  }
}

// Singleton
let instance: WebServerModule | null = null

export function getWebServerModule(): WebServerModule {
  if (!instance) {
    instance = new WebServerModule()
  }
  return instance
}
