import { podTable, uri, string, timestamp, id } from '@undefineds.co/drizzle-solid'
import { RDF, ODRL, UDFS, DCTerms } from './namespaces'

export function buildGrantSubjectPath(grantId: string): string {
  return `/settings/autonomy/grants.ttl#${encodeURIComponent(grantId)}`
}

// Persistent delegation grant resource generated by "do not ask again" decisions.
// This is the durable "delegation" layer (distinct from one-off approvals and append-only audit entries).
export const grantResource = podTable(
  'grant',
  {
    id: id('id'),

    // Table-level type writes odrl:Policy. Keep the project-specific class as
    // an additional rdf:type, so readback treats RDF class membership as multi-valued.
    rdfType: uri('rdfType').array().predicate(RDF.type).notNull().default([UDFS.AutonomyGrant]),

    // Minimal ODRL surface (CP0): allow/deny action on target.
    target: uri('target').predicate(ODRL.target).notNull(),
    action: uri('action').predicate(ODRL.action).notNull(),

    // Extensions
    effect: string('effect').predicate(UDFS.effect).notNull(),
    riskCeiling: string('riskCeiling').predicate(UDFS.riskCeiling),

    // Delegation identity (WebID semantics)
    decisionBy: uri('decisionBy').predicate(UDFS.decisionBy).notNull(),
    decisionRole: string('decisionRole').predicate(UDFS.decisionRole).notNull(),
    onBehalfOf: uri('onBehalfOf').predicate(UDFS.onBehalfOf),

    // Lifecycle
    createdAt: timestamp('createdAt').predicate(DCTerms.created).notNull().defaultNow(),
    revokedAt: timestamp('revokedAt').predicate(UDFS.revokedAt),
  },
  {
    base: '/settings/autonomy/grants.ttl',
    type: ODRL.Policy,
    namespace: ODRL,
    subjectTemplate: '#{id}',
  },
)

// Compatibility alias. New model code should prefer `grantResource`.
export const grantTable = grantResource

export type GrantRow = typeof grantResource.$inferSelect
export type GrantInsert = typeof grantResource.$inferInsert
export type GrantUpdate = typeof grantResource.$inferUpdate
